package cu.uci.cesim.hce_back.estadisticas.model.entity.auto.configuracion;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

// Generated 22-ene-2010 11:07:30 by Hibernate Tools 3.2.4.GA


import org.hibernate.validator.constraints.Length;

import javax.persistence.*;
import java.util.Date;

/**
 * Entidad generated by hbm2java
 */
@Entity
@Table(name = "entidad", schema = "comun")
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "id")
public class Entidad_configuracion implements java.io.Serializable {

    private Long id;
    private Integer version;
    //eliminar
    //private TipoEstablecimientoSalud_configuracion tipoEstablecimientoSalud;

    private Long regionPdvsa;
    private Integer camasFuncionales;
    private Integer cantidadMedicos;
    private Integer cantidadEnfermeros;
    private Integer cantidadTrabajadores;

    private Long tipoEntidad;
    private Long municipio;
    private Long localidad;
    private Long estado;
    private String nombre;
    // eliminar
    //private Integer poblacionAreaInfluencia;
    private String direccion;
    private String telefonos;
    private String fax;
    private String correo;
    private Date fechaApertura;
    private Integer camasArquitectonicas;
    private Integer camasPresupuestadas;
    private boolean esPublico;
    private Boolean eliminado;
    private Long cid;
    //private boolean actual;
    private String logo;
    private String rif;
    private boolean pertenece_a_rhio;


    /**
     * @author yurien 17/03/2014
     * Se agrega la referencia a la instancia del HIS a la que pertenece la entidad
     **/
    private Long instanciaHis;

    private String idInstanciaHis;

    public Entidad_configuracion() {
    }

    public Entidad_configuracion(Long id, Long tipoEntidad,
                                 Long municipio,
                                 Long localidad, Long estado,
                                 boolean esPublico, boolean actual, boolean pertenece_a_rhio) {
        this.id = id;
        this.tipoEntidad = tipoEntidad;
        this.municipio = municipio;
        this.localidad = localidad;
        this.estado = estado;
        this.esPublico = esPublico;
        /*this.actual = actual;*/
        this.pertenece_a_rhio = pertenece_a_rhio;
    }

    public Entidad_configuracion(
            Long id,
            Long tipoEstablecimientoSalud,
            Long tipoEntidad,
            Long municipio,
            Long localidad,
            Long estado,
            String nombre,
            Integer poblacionAreaInfluencia,
            String direccion,
            String telefonos,
            String fax,
            String correo,
            Date fechaApertura,
            Integer camasArquitectonicas,
            Integer camasPresupuestadas,
            boolean esPublico,
            Boolean eliminado,
            Long cid,
            boolean actual,
            String logo,
            boolean pertenece_a_rhio) {
        this.id = id;
        //this.tipoEstablecimientoSalud = tipoEstablecimientoSalud;
        this.tipoEntidad = tipoEntidad;
        this.municipio = municipio;
        this.localidad = localidad;
        this.estado = estado;
        this.nombre = nombre;
        //this.poblacionAreaInfluencia = poblacionAreaInfluencia;
        this.direccion = direccion;
        this.telefonos = telefonos;
        this.fax = fax;
        this.correo = correo;
        this.fechaApertura = fechaApertura;
        this.camasArquitectonicas = camasArquitectonicas;
        this.camasPresupuestadas = camasPresupuestadas;
        this.esPublico = esPublico;
        this.eliminado = eliminado;
        this.cid = cid;
        /*this.actual = actual;*/
        this.logo = logo;
        this.pertenece_a_rhio = pertenece_a_rhio;
        this.instanciaHis = instanciaHis;
    }


    @Id
    @Column(name = "id", unique = true, nullable = false)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Version
    @Column(name = "version")
    public Integer getVersion() {
        return this.version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    @Column(name = "id_tipo_hospital", nullable = false)
    public Long getTipoEntidad() {
        return this.tipoEntidad;
    }

    public void setTipoEntidad(Long tipoEntidad) {
        this.tipoEntidad = tipoEntidad;
    }

    @Column(name = "id_municipio", nullable = false)
    public Long getMunicipio() {
        return this.municipio;
    }

    public void setMunicipio(Long municipio) {
        this.municipio = municipio;
    }

    @Column(name = "id_localidad")
    public Long getLocalidad() {
        return this.localidad;
    }

    public void setLocalidad(Long localidad) {
        this.localidad = localidad;
    }

    @Column(name = "id_estado", nullable = false)
    public Long getEstado() {
        return this.estado;
    }

    public void setEstado(Long estado) {
        this.estado = estado;
    }

    @Column(name = "nombre")
    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    @Column(name = "direccion", length = 100)
    @Length(max = 100)
    public String getDireccion() {
        return this.direccion;
    }

    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    @Column(name = "telefonos", length = 15)
    @Length(max = 15)
    public String getTelefonos() {
        return this.telefonos;
    }

    public void setTelefonos(String telefonos) {
        this.telefonos = telefonos;
    }

    @Column(name = "fax", length = 15)
    @Length(max = 15)
    public String getFax() {
        return this.fax;
    }

    public void setFax(String fax) {
        this.fax = fax;
    }

    /**
     * @author yurien 20/05/2014 Se modifica la cantidad de caracteres que
     * admite el correo de 25 a 100
     **/
    @Column(name = "correo", length = 100)
    @Length(max = 100)
    public String getCorreo() {
        return this.correo;
    }

    public void setCorreo(String correo) {
        this.correo = correo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "fecha_apertura", length = 13)
    public Date getFechaApertura() {
        return this.fechaApertura;
    }

    public void setFechaApertura(Date fechaApertura) {
        this.fechaApertura = fechaApertura;
    }

    @Column(name = "camas_arquitectonicas")
    public Integer getCamasArquitectonicas() {
        return this.camasArquitectonicas;
    }

    public void setCamasArquitectonicas(Integer camasArquitectonicas) {
        this.camasArquitectonicas = camasArquitectonicas;
    }

    @Column(name = "camas_presupuestadas")
    public Integer getCamasPresupuestadas() {
        return this.camasPresupuestadas;
    }

    public void setCamasPresupuestadas(Integer camasPresupuestadas) {
        this.camasPresupuestadas = camasPresupuestadas;
    }

    @Column(name = "es_publico", nullable = false)
    public boolean isEsPublico() {
        return this.esPublico;
    }

    public void setEsPublico(boolean esPublico) {
        this.esPublico = esPublico;
    }

    @Column(name = "eliminado")
    public Boolean getEliminado() {
        return this.eliminado;
    }

    public void setEliminado(Boolean eliminado) {
        this.eliminado = eliminado;
    }

    @Column(name = "cid")
    public Long getCid() {
        return this.cid;
    }

    public void setCid(Long cid) {
        this.cid = cid;
    }


    @Column(name = "logo", length = 30)
    @Length(max = 30)
    public String getLogo() {
        return this.logo;
    }

    public void setLogo(String logo) {
        this.logo = logo;
    }

    @Column(name = "pertenece_a_rhio", nullable = false)
    public boolean isPerteneceARhio() {
        return this.pertenece_a_rhio;
    }

    public void setPerteneceARhio(boolean pertenece_a_rhio) {
        this.pertenece_a_rhio = pertenece_a_rhio;
    }

    @Column(name = "id_region_pdvsa")
    public Long getRegionPdvsa() {
        return regionPdvsa;
    }

    public void setRegionPdvsa(Long regionPdvsa) {
        this.regionPdvsa = regionPdvsa;
    }

    @Column(name = "camas_funcionales")
    public Integer getCamasFuncionales() {
        return camasFuncionales;
    }

    public void setCamasFuncionales(Integer camasFuncionales) {
        this.camasFuncionales = camasFuncionales;
    }

    @Column(name = "cantidad_medicos")
    public Integer getCantidadMedicos() {
        return cantidadMedicos;
    }

    public void setCantidadMedicos(Integer cantidadMedicos) {
        this.cantidadMedicos = cantidadMedicos;
    }

    @Column(name = "cantidad_enfermeros")
    public Integer getCantidadEnfermeros() {
        return cantidadEnfermeros;
    }

    public void setCantidadEnfermeros(Integer cantidadEnfermeros) {
        this.cantidadEnfermeros = cantidadEnfermeros;
    }

    @Column(name = "cantidad_trabajadores")
    public Integer getCantidadTrabajadores() {
        return cantidadTrabajadores;
    }

    public void setCantidadTrabajadores(Integer cantidadTrabajadores) {
        this.cantidadTrabajadores = cantidadTrabajadores;
    }

    @Column(name = "rif", length = 20)
    @Length(max = 20)
    public String getRif() {
        return rif;
    }

    public void setRif(String rif) {
        this.rif = rif;
    }

    /**
     * @author yurien 17/03/2014
     * Se agrega la referencia a la instancia del HIS a la que pertenece la entidad
     **/
    @Column(name = "id_anillo_his")
    public Long getInstanciaHis() {
        return this.instanciaHis;
    }

    public void setInstanciaHis(Long instanciaHis) {
        this.instanciaHis = instanciaHis;
    }

    /*******************************************************************************/
    @Column(name = "id_instancia_his")
    public String getIdInstanciaHis() {
        return this.idInstanciaHis;
    }

    public void setIdInstanciaHis(String idInstanciaHis) {
        if (idInstanciaHis != null)
            idInstanciaHis = idInstanciaHis.trim();
        this.idInstanciaHis = idInstanciaHis;
    }


}
