package cu.uci.cesim.hce_back.estadisticas.model.entity.auto.configuracion;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

// Generated Oct 26, 2017 9:28:14 AM by Hibernate Tools 3.2.4.GA

import cu.uci.cesim.hce_back.estadisticas.model.entity.auto.Especialidad_estadisticas;
import cu.uci.cesim.hce_back.estadisticas.model.entity.auto.Servicio_estadisticas;

import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

/**
 * EstcategoriaProcedimientos generated by hbm2java
 */
@Entity
@Table(name = "estcategoria_procedimientos", schema = "estadisticas")
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "id")
public class EstcategoriaProcedimientos_estadisticas implements java.io.Serializable {

    private long id;
    private Integer version;
    private Especialidad_estadisticas especialidad;
    private ReporteTipoReporte_estadisticas reporteTipoReporte;
    private Servicio_estadisticas servicio;
    private String nombre;
    private Integer orden;
    private Long cid;
    private Boolean eliminado;

    private Set<ProcedimientosCategoria_estadisticas> procedimientosCategorias = new HashSet<ProcedimientosCategoria_estadisticas>(
            0);

    public EstcategoriaProcedimientos_estadisticas() {
    }

    public EstcategoriaProcedimientos_estadisticas(long id) {
        this.id = id;
    }

    public EstcategoriaProcedimientos_estadisticas(long id, Especialidad_estadisticas especialidad,
                                                   ReporteTipoReporte_estadisticas reporteTipoReporte, Servicio_estadisticas servicio,
                                                   String nombre, Long cid,
                                                   Set<ProcedimientosCategoria_estadisticas> procedimientosCategorias) {
        this.id = id;
        this.especialidad = especialidad;
        this.reporteTipoReporte = reporteTipoReporte;
        this.servicio = servicio;
        this.nombre = nombre;
        this.cid = cid;
        this.procedimientosCategorias = procedimientosCategorias;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @Version
    @Column(name = "version")
    public Integer getVersion() {
        return this.version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "especialidad")
    public Especialidad_estadisticas getEspecialidad() {
        return this.especialidad;
    }

    public void setEspecialidad(Especialidad_estadisticas especialidad) {
        this.especialidad = especialidad;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "tipo_reporte")
    public ReporteTipoReporte_estadisticas getReporteTipoReporte() {
        return this.reporteTipoReporte;
    }

    public void setReporteTipoReporte(ReporteTipoReporte_estadisticas reporteTipoReporte) {
        this.reporteTipoReporte = reporteTipoReporte;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "servicio")
    public Servicio_estadisticas getServicio() {
        return this.servicio;
    }

    public void setServicio(Servicio_estadisticas servicio) {
        this.servicio = servicio;
    }

    @Column(name = "nombre")
    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        if (nombre != null)
            nombre = nombre.trim();
        this.nombre = nombre;
    }

    @Column(name = "orden")
    public Integer getOrden() {
        return orden;
    }

    public void setOrden(Integer orden) {
        this.orden = orden;
    }

    @Column(name = "eliminado")
    public Boolean getEliminado() {
        return eliminado;
    }

    public void setEliminado(Boolean eliminado) {
        this.eliminado = eliminado;
    }

    @Column(name = "cid")
    public Long getCid() {
        return this.cid;
    }


    public void setCid(Long cid) {
        this.cid = cid;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "estcategoriaProcedimientos")
    public Set<ProcedimientosCategoria_estadisticas> getProcedimientosCategorias() {
        return this.procedimientosCategorias;
    }

    public void setProcedimientosCategorias(
            Set<ProcedimientosCategoria_estadisticas> procedimientosCategorias) {
        this.procedimientosCategorias = procedimientosCategorias;
    }

}
