package cu.uci.cesim.hce_back.estadisticas.model.entity.auto.configuracion;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

// Generated Oct 26, 2017 9:28:14 AM by Hibernate Tools 3.2.4.GA

import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

/**
 * ReporteTipoReporte generated by hbm2java
 */
@Entity
@Table(name = "reporte_tipo_reporte", schema = "epidemiologia")
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "id")
public class ReporteTipoReporte_estadisticas implements java.io.Serializable {

    private long id;
    private Integer version;
    private String valor;
    private String codigo;
    private Long cid;
    private Boolean eliminado;
    private Set<EstcategoriaEnfermedad_estadisticas> estcategoriaEnfermedads = new HashSet<EstcategoriaEnfermedad_estadisticas>(
            0);
    private Set<EstcategoriaProcedimientos_estadisticas> estcategoriaProcedimientoses = new HashSet<EstcategoriaProcedimientos_estadisticas>(
            0);

    //agrupacion de enfermedades
    private Set<agrupacion_enfermedades> agrupacion_enfermedades = new HashSet<agrupacion_enfermedades>(
            0);

    public ReporteTipoReporte_estadisticas() {
    }

    public ReporteTipoReporte_estadisticas(long id) {
        this.id = id;
    }

    public ReporteTipoReporte_estadisticas(long id, String valor, String codigo, Long cid,
                                           Boolean eliminado,
                                           Set<EstcategoriaEnfermedad_estadisticas> estcategoriaEnfermedads,
                                           Set<EstcategoriaProcedimientos_estadisticas> estcategoriaProcedimientoses) {
        this.id = id;
        this.valor = valor;
        this.codigo = codigo;
        this.cid = cid;
        this.eliminado = eliminado;
        this.estcategoriaEnfermedads = estcategoriaEnfermedads;
        this.estcategoriaProcedimientoses = estcategoriaProcedimientoses;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @Version
    @Column(name = "version")
    public Integer getVersion() {
        return this.version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    @Column(name = "valor")
    public String getValor() {
        return this.valor;
    }

    public void setValor(String valor) {
        if (valor != null)
            valor = valor.trim();
        this.valor = valor;
    }

    @Column(name = "codigo")
    public String getCodigo() {
        return this.codigo;
    }

    public void setCodigo(String codigo) {
        if (codigo != null)
            codigo = codigo.trim();
        this.codigo = codigo;
    }

    @Column(name = "cid")
    public Long getCid() {
        return this.cid;
    }

    public void setCid(Long cid) {
        this.cid = cid;
    }

    @Column(name = "eliminado")
    public Boolean getEliminado() {
        return this.eliminado;
    }

    public void setEliminado(Boolean eliminado) {
        this.eliminado = eliminado;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "reporteTipoReporte")
    public Set<EstcategoriaEnfermedad_estadisticas> getEstcategoriaEnfermedads() {
        return this.estcategoriaEnfermedads;
    }

    public void setEstcategoriaEnfermedads(
            Set<EstcategoriaEnfermedad_estadisticas> estcategoriaEnfermedads) {
        this.estcategoriaEnfermedads = estcategoriaEnfermedads;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "reporteTipoReporte")
    public Set<EstcategoriaProcedimientos_estadisticas> getEstcategoriaProcedimientoses() {
        return this.estcategoriaProcedimientoses;
    }

    public void setEstcategoriaProcedimientoses(
            Set<EstcategoriaProcedimientos_estadisticas> estcategoriaProcedimientoses) {
        this.estcategoriaProcedimientoses = estcategoriaProcedimientoses;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "reporteTipoReporte")
    public Set<agrupacion_enfermedades> getAgrupacion_enfermedades() {

        return agrupacion_enfermedades;
    }

    public void setAgrupacion_enfermedades(
            Set<agrupacion_enfermedades> agrupacion_enfermedades) {
        this.agrupacion_enfermedades = agrupacion_enfermedades;
    }

}
