package cu.uci.cesim.hce_back.estadisticas.model.entity.auto.ris;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

// Generated May 21, 2012 5:42:06 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.*;
import java.util.Date;


/**
 * CitaRis generated by hbm2java
 */
@Entity
@Table(name = "cita_ris", schema = "ris")
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "id")
public class CitaRis_RIS implements java.io.Serializable {

    private int id;
    private Solicitud_RIS solicitud;
    private Medico_RIS medico;
    private ServicioInEntidad_RIS servicioInEntidad;
    private EstadoCita_RIS estadoCita;
    private Date horaIni;
    private Date horaFin;
    private boolean isEmergency;
    private Date fecha;
    private Long cid;
    private String datosClinicos;
    private Estudio_RIS estudio;

    public CitaRis_RIS() {
    }

    public CitaRis_RIS(int id, Solicitud_RIS solicitud,
                       EstadoCita_RIS estadoCita, boolean isEmergency) {
        this.id = id;
        this.solicitud = solicitud;
        this.estadoCita = estadoCita;
        this.isEmergency = isEmergency;
    }

    public CitaRis_RIS(int id, Solicitud_RIS solicitud,
                       Medico_RIS medico,
                       ServicioInEntidad_RIS servicioInEntidad,
                       EstadoCita_RIS estadoCita, Date horaIni, Date horaFin,
                       boolean isEmergency, Date fecha, Long cid, String datosClinicos,
                       Estudio_RIS estudio) {
        this.id = id;
        this.solicitud = solicitud;
        this.medico = medico;
        this.servicioInEntidad = servicioInEntidad;
        this.estadoCita = estadoCita;
        this.horaIni = horaIni;
        this.horaFin = horaFin;
        this.isEmergency = isEmergency;
        this.fecha = fecha;
        this.cid = cid;
        this.datosClinicos = datosClinicos;
        this.estudio = estudio;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_solicitud", nullable = false)

    public Solicitud_RIS getSolicitud() {
        return this.solicitud;
    }

    public void setSolicitud(Solicitud_RIS solicitud) {
        this.solicitud = solicitud;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_medico")
    public Medico_RIS getMedico() {
        return this.medico;
    }

    public void setMedico(Medico_RIS medico) {
        this.medico = medico;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_servicio")
    public ServicioInEntidad_RIS getServicioInEntidad() {
        return this.servicioInEntidad;
    }

    public void setServicioInEntidad(
            ServicioInEntidad_RIS servicioInEntidad) {
        this.servicioInEntidad = servicioInEntidad;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_estado_cita", nullable = false)

    public EstadoCita_RIS getEstadoCita() {
        return this.estadoCita;
    }

    public void setEstadoCita(EstadoCita_RIS estadoCita) {
        this.estadoCita = estadoCita;
    }

    @Temporal(TemporalType.TIME)
    @Column(name = "hora_ini", length = 15)
    public Date getHoraIni() {
        return this.horaIni;
    }

    public void setHoraIni(Date horaIni) {
        this.horaIni = horaIni;
    }

    @Temporal(TemporalType.TIME)
    @Column(name = "hora_fin", length = 15)
    public Date getHoraFin() {
        return this.horaFin;
    }

    public void setHoraFin(Date horaFin) {
        this.horaFin = horaFin;
    }

    @Column(name = "is_emergency", nullable = false)

    public boolean isIsEmergency() {
        return this.isEmergency;
    }

    public void setIsEmergency(boolean isEmergency) {
        this.isEmergency = isEmergency;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "fecha", length = 13)
    public Date getFecha() {
        return this.fecha;
    }

    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    @Column(name = "cid")
    public Long getCid() {
        return this.cid;
    }

    public void setCid(Long cid) {
        this.cid = cid;
    }

    @Column(name = "datos_clinicos")
    public String getDatosClinicos() {
        return this.datosClinicos;
    }

    public void setDatosClinicos(String datosClinicos) {
        if (datosClinicos != null)
            datosClinicos = datosClinicos.trim();
        this.datosClinicos = datosClinicos;
    }

    @OneToOne(fetch = FetchType.LAZY, mappedBy = "citaRis")
    public Estudio_RIS getEstudio() {
        return this.estudio;
    }

    public void setEstudio(Estudio_RIS estudio) {
        this.estudio = estudio;
    }

}
