package cu.uci.cesim.hce_back.estadisticas.model.entity.auto.ris;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

// Generated May 21, 2012 5:42:06 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.*;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ConfigServicios generated by hbm2java
 */
@Entity
@Table(name = "config_servicios", schema = "ris")
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "id")
public class ConfigServicios_RIS implements java.io.Serializable {

    private int id;
    private Integer tipoServicio;
    private Integer turnosDuracion;
    private Date inicioManana;
    private Date finManana;
    private Date inicioTarde;
    private Date finTarde;
    private Long cid;
    private Set<HistorialConfigServicios_RIS> historialConfigServicioses = new HashSet<HistorialConfigServicios_RIS>(
            0);

    public ConfigServicios_RIS() {
    }

    public ConfigServicios_RIS(int id) {
        this.id = id;
    }

    public ConfigServicios_RIS(
            int id,
            Integer tipoServicio,
            Integer turnosDuracion,
            Date inicioManana,
            Date finManana,
            Date inicioTarde,
            Date finTarde,
            Long cid,
            Set<HistorialConfigServicios_RIS> historialConfigServicioses) {
        this.id = id;
        this.tipoServicio = tipoServicio;
        this.turnosDuracion = turnosDuracion;
        this.inicioManana = inicioManana;
        this.finManana = finManana;
        this.inicioTarde = inicioTarde;
        this.finTarde = finTarde;
        this.cid = cid;
        this.historialConfigServicioses = historialConfigServicioses;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Column(name = "tipo_servicio")
    public Integer getTipoServicio() {
        return this.tipoServicio;
    }

    public void setTipoServicio(Integer tipoServicio) {
        this.tipoServicio = tipoServicio;
    }

    @Column(name = "turnos_duracion")
    public Integer getTurnosDuracion() {
        return this.turnosDuracion;
    }

    public void setTurnosDuracion(Integer turnosDuracion) {
        this.turnosDuracion = turnosDuracion;
    }

    @Temporal(TemporalType.TIME)
    @Column(name = "inicio_manana", length = 15)
    public Date getInicioManana() {
        return this.inicioManana;
    }

    public void setInicioManana(Date inicioManana) {
        this.inicioManana = inicioManana;
    }

    @Temporal(TemporalType.TIME)
    @Column(name = "fin_manana", length = 15)
    public Date getFinManana() {
        return this.finManana;
    }

    public void setFinManana(Date finManana) {
        this.finManana = finManana;
    }

    @Temporal(TemporalType.TIME)
    @Column(name = "inicio_tarde", length = 15)
    public Date getInicioTarde() {
        return this.inicioTarde;
    }

    public void setInicioTarde(Date inicioTarde) {
        this.inicioTarde = inicioTarde;
    }

    @Temporal(TemporalType.TIME)
    @Column(name = "fin_tarde", length = 15)
    public Date getFinTarde() {
        return this.finTarde;
    }

    public void setFinTarde(Date finTarde) {
        this.finTarde = finTarde;
    }

    @Column(name = "cid")
    public Long getCid() {
        return this.cid;
    }

    public void setCid(Long cid) {
        this.cid = cid;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "configServicios")
    public Set<HistorialConfigServicios_RIS> getHistorialConfigServicioses() {
        return this.historialConfigServicioses;
    }

    public void setHistorialConfigServicioses(
            Set<HistorialConfigServicios_RIS> historialConfigServicioses) {
        this.historialConfigServicioses = historialConfigServicioses;
    }

}
