package cu.uci.cesim.hce_back.estadisticas.model.entity.auto.ris;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

// Generated May 21, 2012 5:42:06 PM by Hibernate Tools 3.4.0.CR1

import org.hibernate.validator.constraints.Length;

import javax.persistence.*;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * Entidad generated by hbm2java
 */
@Entity
@Table(name = "entidad", schema = "comun", uniqueConstraints = @UniqueConstraint(columnNames = "nombre"))
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "id")
public class Entidad_RIS implements java.io.Serializable {

    private long id;
    private Integer version;
    private String nombre;
    private String direccion;
    private String telefonos;
    private String fax;
    private String correo;
    private Date fechaApertura;
    private long idTipoHospital;
    private long idEstado;
    private long idMunicipio;
    private Long idLocalidad;
    private Integer camasArquitectonicas;
    private Integer camasPresupuestadas;
    private boolean esPublico;
    private Boolean eliminado;
    private Long cid;
    private String logo;
    private boolean perteneceARhio;
    private Long idCategoriaEntidad;
    private String idInstanciaHis;
    private Integer camasFuncionales;
    private Integer cantidadMedicos;
    private Integer cantidadEnfermeros;
    private Integer cantidadTrabajadores;
    private Long idRegionPdvsa;
    private Long idRis;
    private Set<ServicioInEntidad_RIS> servicioInEntidads = new HashSet<ServicioInEntidad_RIS>(
            0);
    private Set<ServicioInEntidad_RIS> servicioInEntidads_1 = new HashSet<ServicioInEntidad_RIS>(
            0);
    private Set<HojaConsulta_RIS> hojaConsultas = new HashSet<HojaConsulta_RIS>(
            0);

    public Entidad_RIS() {
    }

    public Entidad_RIS(long id, long idTipoHospital, long idEstado,
                       long idMunicipio, boolean esPublico, boolean perteneceARhio) {
        this.id = id;
        this.idTipoHospital = idTipoHospital;
        this.idEstado = idEstado;
        this.idMunicipio = idMunicipio;
        this.esPublico = esPublico;
        this.perteneceARhio = perteneceARhio;
    }

    public Entidad_RIS(long id, String nombre, String direccion,
                       String telefonos, String fax, String correo, Date fechaApertura,
                       long idTipoHospital, long idEstado, long idMunicipio,
                       Long idLocalidad, Integer camasArquitectonicas,
                       Integer camasPresupuestadas, boolean esPublico, Boolean eliminado,
                       Long cid, String logo, boolean perteneceARhio,
                       Long idCategoriaEntidad, String idInstanciaHis,
                       Integer camasFuncionales, Integer cantidadMedicos,
                       Integer cantidadEnfermeros, Integer cantidadTrabajadores,
                       Long idRegionPdvsa, Long idRis,
                       Set<ServicioInEntidad_RIS> servicioInEntidads,
                       Set<ServicioInEntidad_RIS> servicioInEntidads_1,
                       Set<HojaConsulta_RIS> hojaConsultas) {
        this.id = id;
        this.nombre = nombre;
        this.direccion = direccion;
        this.telefonos = telefonos;
        this.fax = fax;
        this.correo = correo;
        this.fechaApertura = fechaApertura;
        this.idTipoHospital = idTipoHospital;
        this.idEstado = idEstado;
        this.idMunicipio = idMunicipio;
        this.idLocalidad = idLocalidad;
        this.camasArquitectonicas = camasArquitectonicas;
        this.camasPresupuestadas = camasPresupuestadas;
        this.esPublico = esPublico;
        this.eliminado = eliminado;
        this.cid = cid;
        this.logo = logo;
        this.perteneceARhio = perteneceARhio;
        this.idCategoriaEntidad = idCategoriaEntidad;
        this.idInstanciaHis = idInstanciaHis;
        this.camasFuncionales = camasFuncionales;
        this.cantidadMedicos = cantidadMedicos;
        this.cantidadEnfermeros = cantidadEnfermeros;
        this.cantidadTrabajadores = cantidadTrabajadores;
        this.idRegionPdvsa = idRegionPdvsa;
        this.idRis = idRis;
        this.servicioInEntidads = servicioInEntidads;
        this.servicioInEntidads_1 = servicioInEntidads_1;
        this.hojaConsultas = hojaConsultas;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @Version
    @Column(name = "version")
    public Integer getVersion() {
        return this.version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    @Column(name = "nombre", unique = true)
    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        if (nombre != null)
            nombre = nombre.trim();
        this.nombre = nombre;
    }

    @Column(name = "direccion", length = 50)
    @Length(max = 50)
    public String getDireccion() {
        return this.direccion;
    }

    public void setDireccion(String direccion) {
        if (direccion != null)
            direccion = direccion.trim();
        this.direccion = direccion;
    }

    @Column(name = "telefonos", length = 15)
    @Length(max = 15)
    public String getTelefonos() {
        return this.telefonos;
    }

    public void setTelefonos(String telefonos) {
        if (telefonos != null)
            telefonos = telefonos.trim();
        this.telefonos = telefonos;
    }

    @Column(name = "fax", length = 15)
    @Length(max = 15)
    public String getFax() {
        return this.fax;
    }

    public void setFax(String fax) {
        if (fax != null)
            fax = fax.trim();
        this.fax = fax;
    }

    @Column(name = "correo", length = 20)
    @Length(max = 20)
    public String getCorreo() {
        return this.correo;
    }

    public void setCorreo(String correo) {
        if (correo != null)
            correo = correo.trim();
        this.correo = correo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "fecha_apertura", length = 13)
    public Date getFechaApertura() {
        return this.fechaApertura;
    }

    public void setFechaApertura(Date fechaApertura) {
        this.fechaApertura = fechaApertura;
    }

    @Column(name = "id_tipo_hospital", nullable = false)

    public long getIdTipoHospital() {
        return this.idTipoHospital;
    }

    public void setIdTipoHospital(long idTipoHospital) {
        this.idTipoHospital = idTipoHospital;
    }

    @Column(name = "id_estado", nullable = false)

    public long getIdEstado() {
        return this.idEstado;
    }

    public void setIdEstado(long idEstado) {
        this.idEstado = idEstado;
    }

    @Column(name = "id_municipio", nullable = false)

    public long getIdMunicipio() {
        return this.idMunicipio;
    }

    public void setIdMunicipio(long idMunicipio) {
        this.idMunicipio = idMunicipio;
    }

    @Column(name = "id_localidad")
    public Long getIdLocalidad() {
        return this.idLocalidad;
    }

    public void setIdLocalidad(Long idLocalidad) {
        this.idLocalidad = idLocalidad;
    }

    @Column(name = "camas_arquitectonicas")
    public Integer getCamasArquitectonicas() {
        return this.camasArquitectonicas;
    }

    public void setCamasArquitectonicas(Integer camasArquitectonicas) {
        this.camasArquitectonicas = camasArquitectonicas;
    }

    @Column(name = "camas_presupuestadas")
    public Integer getCamasPresupuestadas() {
        return this.camasPresupuestadas;
    }

    public void setCamasPresupuestadas(Integer camasPresupuestadas) {
        this.camasPresupuestadas = camasPresupuestadas;
    }

    @Column(name = "es_publico", nullable = false)

    public boolean isEsPublico() {
        return this.esPublico;
    }

    public void setEsPublico(boolean esPublico) {
        this.esPublico = esPublico;
    }

    @Column(name = "eliminado")
    public Boolean getEliminado() {
        return this.eliminado;
    }

    public void setEliminado(Boolean eliminado) {
        this.eliminado = eliminado;
    }

    @Column(name = "cid")
    public Long getCid() {
        return this.cid;
    }

    public void setCid(Long cid) {
        this.cid = cid;
    }

    @Column(name = "logo", length = 30)
    @Length(max = 30)
    public String getLogo() {
        return this.logo;
    }

    public void setLogo(String logo) {
        if (logo != null)
            logo = logo.trim();
        this.logo = logo;
    }

    @Column(name = "pertenece_a_rhio", nullable = false)

    public boolean isPerteneceARhio() {
        return this.perteneceARhio;
    }

    public void setPerteneceARhio(boolean perteneceARhio) {
        this.perteneceARhio = perteneceARhio;
    }

    @Column(name = "id_categoria_entidad")
    public Long getIdCategoriaEntidad() {
        return this.idCategoriaEntidad;
    }

    public void setIdCategoriaEntidad(Long idCategoriaEntidad) {
        this.idCategoriaEntidad = idCategoriaEntidad;
    }

    @Column(name = "id_instancia_his")
    public String getIdInstanciaHis() {
        return this.idInstanciaHis;
    }

    public void setIdInstanciaHis(String idInstanciaHis) {
        if (idInstanciaHis != null)
            idInstanciaHis = idInstanciaHis.trim();
        this.idInstanciaHis = idInstanciaHis;
    }

    @Column(name = "camas_funcionales")
    public Integer getCamasFuncionales() {
        return this.camasFuncionales;
    }

    public void setCamasFuncionales(Integer camasFuncionales) {
        this.camasFuncionales = camasFuncionales;
    }

    @Column(name = "cantidad_medicos")
    public Integer getCantidadMedicos() {
        return this.cantidadMedicos;
    }

    public void setCantidadMedicos(Integer cantidadMedicos) {
        this.cantidadMedicos = cantidadMedicos;
    }

    @Column(name = "cantidad_enfermeros")
    public Integer getCantidadEnfermeros() {
        return this.cantidadEnfermeros;
    }

    public void setCantidadEnfermeros(Integer cantidadEnfermeros) {
        this.cantidadEnfermeros = cantidadEnfermeros;
    }

    @Column(name = "cantidad_trabajadores")
    public Integer getCantidadTrabajadores() {
        return this.cantidadTrabajadores;
    }

    public void setCantidadTrabajadores(Integer cantidadTrabajadores) {
        this.cantidadTrabajadores = cantidadTrabajadores;
    }

    @Column(name = "id_region_pdvsa")
    public Long getIdRegionPdvsa() {
        return this.idRegionPdvsa;
    }

    public void setIdRegionPdvsa(Long idRegionPdvsa) {
        this.idRegionPdvsa = idRegionPdvsa;
    }

    @Column(name = "id_ris")
    public Long getIdRis() {
        return this.idRis;
    }

    public void setIdRis(Long idRis) {
        this.idRis = idRis;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "entidad")
    public Set<ServicioInEntidad_RIS> getServicioInEntidads() {
        return this.servicioInEntidads;
    }

    public void setServicioInEntidads(
            Set<ServicioInEntidad_RIS> servicioInEntidads) {
        this.servicioInEntidads = servicioInEntidads;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "entidad")
    public Set<ServicioInEntidad_RIS> getServicioInEntidads_1() {
        return this.servicioInEntidads_1;
    }

    public void setServicioInEntidads_1(
            Set<ServicioInEntidad_RIS> servicioInEntidads_1) {
        this.servicioInEntidads_1 = servicioInEntidads_1;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "entidad")
    public Set<HojaConsulta_RIS> getHojaConsultas() {
        return this.hojaConsultas;
    }

    public void setHojaConsultas(Set<HojaConsulta_RIS> hojaConsultas) {
        this.hojaConsultas = hojaConsultas;
    }

}
