package cu.uci.cesim.hce_back.estadisticas.model.entity.auto.ris;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

// Generated May 21, 2012 5:42:06 PM by Hibernate Tools 3.4.0.CR1

import org.hibernate.validator.constraints.Length;

import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;


/**
 * Equipo generated by hbm2java
 */
@Entity
@Table(name = "equipo", schema = "ris")
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "id")
public class Equipo_RIS implements java.io.Serializable {

    private long idHis;
    private EstadoOperacional_RIS estadoOperacional;
    private String ip;
    private String pacsAetitle;
    private String applicationEntity;
    private Boolean esDicomCompatible;
    private Long cid;
    private Integer id;
    private Long idApplication;
    private Set<Estudio_RIS> estudios = new HashSet<Estudio_RIS>(
            0);
    private Set<EquipoEstudioServicio_RIS> equipoEstudioServicios = new HashSet<EquipoEstudioServicio_RIS>(
            0);

    public Equipo_RIS() {
    }

    public Equipo_RIS(long idHis, String applicationEntity) {
        this.idHis = idHis;
        this.applicationEntity = applicationEntity;
    }

    public Equipo_RIS(long idHis,
                      EstadoOperacional_RIS estadoOperacional, String ip,
                      String pacsAetitle, String applicationEntity,
                      Boolean esDicomCompatible, Long cid, Integer id,
                      Long idApplication, Set<Estudio_RIS> estudios,
                      Set<EquipoEstudioServicio_RIS> equipoEstudioServicios) {
        this.idHis = idHis;
        this.estadoOperacional = estadoOperacional;
        this.ip = ip;
        this.pacsAetitle = pacsAetitle;
        this.applicationEntity = applicationEntity;
        this.esDicomCompatible = esDicomCompatible;
        this.cid = cid;
        this.id = id;
        this.idApplication = idApplication;
        this.estudios = estudios;
        this.equipoEstudioServicios = equipoEstudioServicios;
    }

    @Id
    @Column(name = "id_his", unique = true, nullable = false)

    public long getIdHis() {
        return this.idHis;
    }

    public void setIdHis(long idHis) {
        this.idHis = idHis;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_estado_operacional")
    public EstadoOperacional_RIS getEstadoOperacional() {
        return this.estadoOperacional;
    }

    public void setEstadoOperacional(
            EstadoOperacional_RIS estadoOperacional) {
        this.estadoOperacional = estadoOperacional;
    }

    @Column(name = "ip", length = 15)
    @Length(max = 15)
    public String getIp() {
        return this.ip;
    }

    public void setIp(String ip) {
        if (ip != null)
            ip = ip.trim();
        this.ip = ip;
    }

    @Column(name = "pacs_aetitle", length = 16)
    @Length(max = 16)
    public String getPacsAetitle() {
        return this.pacsAetitle;
    }

    public void setPacsAetitle(String pacsAetitle) {
        if (pacsAetitle != null)
            pacsAetitle = pacsAetitle.trim();
        this.pacsAetitle = pacsAetitle;
    }

    @Column(name = "application_entity", nullable = false, length = 25)

    @Length(max = 25)
    public String getApplicationEntity() {
        return this.applicationEntity;
    }

    public void setApplicationEntity(String applicationEntity) {
        if (applicationEntity != null)
            applicationEntity = applicationEntity.trim();
        this.applicationEntity = applicationEntity;
    }

    @Column(name = "es_dicom_compatible")
    public Boolean getEsDicomCompatible() {
        return this.esDicomCompatible;
    }

    public void setEsDicomCompatible(Boolean esDicomCompatible) {
        this.esDicomCompatible = esDicomCompatible;
    }

    @Column(name = "cid")
    public Long getCid() {
        return this.cid;
    }

    public void setCid(Long cid) {
        this.cid = cid;
    }

    @Column(name = "id")
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "id_application")
    public Long getIdApplication() {
        return this.idApplication;
    }

    public void setIdApplication(Long idApplication) {
        this.idApplication = idApplication;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "equipo")
    public Set<Estudio_RIS> getEstudios() {
        return this.estudios;
    }

    public void setEstudios(Set<Estudio_RIS> estudios) {
        this.estudios = estudios;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "equipo")
    public Set<EquipoEstudioServicio_RIS> getEquipoEstudioServicios() {
        return this.equipoEstudioServicios;
    }

    public void setEquipoEstudioServicios(
            Set<EquipoEstudioServicio_RIS> equipoEstudioServicios) {
        this.equipoEstudioServicios = equipoEstudioServicios;
    }

}
