package cu.uci.cesim.hce_back.estadisticas.model.entity.auto.ris;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

// Generated May 21, 2012 5:42:06 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.*;


/**
 * EquipoEstudioServicio generated by hbm2java
 */
@Entity
@Table(name = "equipo_estudio_servicio", schema = "ris")
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "id")
public class EquipoEstudioServicio_RIS implements java.io.Serializable {

    private long id;
    private TipoEstudio_RIS tipoEstudio;
    private ServicioInEntidad_RIS servicioInEntidad;
    private Equipo_RIS equipo;
    private Long cid;

    public EquipoEstudioServicio_RIS() {
    }

    public EquipoEstudioServicio_RIS(long id,
                                     TipoEstudio_RIS tipoEstudio,
                                     ServicioInEntidad_RIS servicioInEntidad,
                                     Equipo_RIS equipo) {
        this.id = id;
        this.tipoEstudio = tipoEstudio;
        this.servicioInEntidad = servicioInEntidad;
        this.equipo = equipo;
    }

    public EquipoEstudioServicio_RIS(long id,
                                     TipoEstudio_RIS tipoEstudio,
                                     ServicioInEntidad_RIS servicioInEntidad,
                                     Equipo_RIS equipo, Long cid) {
        this.id = id;
        this.tipoEstudio = tipoEstudio;
        this.servicioInEntidad = servicioInEntidad;
        this.equipo = equipo;
        this.cid = cid;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_estudio", nullable = false)

    public TipoEstudio_RIS getTipoEstudio() {
        return this.tipoEstudio;
    }

    public void setTipoEstudio(TipoEstudio_RIS tipoEstudio) {
        this.tipoEstudio = tipoEstudio;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_servicio", nullable = false)

    public ServicioInEntidad_RIS getServicioInEntidad() {
        return this.servicioInEntidad;
    }

    public void setServicioInEntidad(
            ServicioInEntidad_RIS servicioInEntidad) {
        this.servicioInEntidad = servicioInEntidad;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_equipo", nullable = false)

    public Equipo_RIS getEquipo() {
        return this.equipo;
    }

    public void setEquipo(Equipo_RIS equipo) {
        this.equipo = equipo;
    }

    @Column(name = "cid")
    public Long getCid() {
        return this.cid;
    }

    public void setCid(Long cid) {
        this.cid = cid;
    }

}
