package cu.uci.cesim.hce_back.estadisticas.model.entity.auto.ris;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

// Generated May 21, 2012 5:42:06 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;


/**
 * EstadoCita generated by hbm2java
 */
@Entity
@Table(name = "estado_cita", schema = "ris")
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "id")
public class EstadoCita_RIS implements java.io.Serializable {

    private long idHis;
    private String estado;
    private Long cid;
    private Long idApplication;
    private int id;
    private Set<CitaRis_RIS> citaRises = new HashSet<CitaRis_RIS>(
            0);

    public EstadoCita_RIS() {
    }

    public EstadoCita_RIS(long idHis, String estado, int id) {
        this.idHis = idHis;
        this.estado = estado;
        this.id = id;
    }

    public EstadoCita_RIS(long idHis, String estado, Long cid,
                          Long idApplication, int id, Set<CitaRis_RIS> citaRises) {
        this.idHis = idHis;
        this.estado = estado;
        this.cid = cid;
        this.idApplication = idApplication;
        this.id = id;
        this.citaRises = citaRises;
    }

    @Id
    @Column(name = "id_his", unique = true, nullable = false)

    public long getIdHis() {
        return this.idHis;
    }

    public void setIdHis(long idHis) {
        this.idHis = idHis;
    }

    @Column(name = "estado", nullable = false)

    public String getEstado() {
        return this.estado;
    }

    public void setEstado(String estado) {
        if (estado != null)
            estado = estado.trim();
        this.estado = estado;
    }

    @Column(name = "cid")
    public Long getCid() {
        return this.cid;
    }

    public void setCid(Long cid) {
        this.cid = cid;
    }

    @Column(name = "id_application")
    public Long getIdApplication() {
        return this.idApplication;
    }

    public void setIdApplication(Long idApplication) {
        this.idApplication = idApplication;
    }

    @Column(name = "id", nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "estadoCita")
    public Set<CitaRis_RIS> getCitaRises() {
        return this.citaRises;
    }

    public void setCitaRises(Set<CitaRis_RIS> citaRises) {
        this.citaRises = citaRises;
    }

}
