package cu.uci.cesim.hce_back.estadisticas.model.entity.auto.ris;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

// Generated May 21, 2012 5:42:06 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.*;
import java.util.Date;


/**
 * HistorialConfigServicios generated by hbm2java
 */
@Entity
@Table(name = "historial_config_servicios", schema = "ris")
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "id")
public class HistorialConfigServicios_RIS implements
        java.io.Serializable {

    private long id;
    private ServicioInEntidad_RIS servicioInEntidad;
    private ConfigServicios_RIS configServicios;
    private Date fecha;
    private Long cid;

    public HistorialConfigServicios_RIS() {
    }

    public HistorialConfigServicios_RIS(long id,
                                        ServicioInEntidad_RIS servicioInEntidad,
                                        ConfigServicios_RIS configServicios) {
        this.id = id;
        this.servicioInEntidad = servicioInEntidad;
        this.configServicios = configServicios;
    }

    public HistorialConfigServicios_RIS(long id,
                                        ServicioInEntidad_RIS servicioInEntidad,
                                        ConfigServicios_RIS configServicios, Date fecha, Long cid) {
        this.id = id;
        this.servicioInEntidad = servicioInEntidad;
        this.configServicios = configServicios;
        this.fecha = fecha;
        this.cid = cid;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_servicio", nullable = false)

    public ServicioInEntidad_RIS getServicioInEntidad() {
        return this.servicioInEntidad;
    }

    public void setServicioInEntidad(
            ServicioInEntidad_RIS servicioInEntidad) {
        this.servicioInEntidad = servicioInEntidad;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_configuracion", nullable = false)

    public ConfigServicios_RIS getConfigServicios() {
        return this.configServicios;
    }

    public void setConfigServicios(ConfigServicios_RIS configServicios) {
        this.configServicios = configServicios;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "fecha", length = 13)
    public Date getFecha() {
        return this.fecha;
    }

    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    @Column(name = "cid")
    public Long getCid() {
        return this.cid;
    }

    public void setCid(Long cid) {
        this.cid = cid;
    }

}
