package cu.uci.cesim.hce_back.estadisticas.model.entity.auto.ris;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

// Generated May 21, 2012 5:42:06 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.*;
import java.util.Date;


/**
 * HojaConsulta generated by hbm2java
 */
@Entity
@Table(name = "hoja_consulta", schema = "hc_local")
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "id")
public class HojaConsulta_RIS implements java.io.Serializable {

    private long id;
    private Integer version;
    private Entidad_RIS entidad;
    private Long idIndicacionesMedicas;
    private Long idConstancia;
    private Long idReferencia;
    private Long idContrarreferencia;
    private Long idOrdenAdmision;
    private Long idSolicitudAnalisisLab;
    private Long idSolicitudExamenTipiaje;
    private Long idSolicitudIntervencionQ;
    private Long idCitaConsulta;
    private Date fecha;
    private Long idDiagnostico;
    private String observaciones;
    private String conclusiones;
    private Long idDiagnosticoPrincFinal;
    private Long idHojaDermatologia;
    private Long idHojaGeneral;
    private Long idHojaHemOncPediatrica;
    private Long idHojaRadioterapia;
    private Long idHojaTriaje;
    private Long idHojaCirugiaColoRectal;
    private Long idHojaGinecologia;
    private Long idHojaNeurologia;
    private Long idHojaOftalmologia;
    private Long idHojaUroGenital;
    private Long idHojaGastroenterologia;
    private Long idHojaHemOncologica;
    private Long idHojaObstetricia;
    private Long idHojaOrl;
    private Long idHojaTraumatologia;
    private String motivo;
    private String enfermedadActual;
    private Date horaFin;
    private long idCitaOrigen;
    private Boolean eliminado;
    private Long cid;
    private Long idCitaTriajeGral;
    private Long idTipoHoja;
    private Long idEspecialidad;
    private Date horaInicio;
    private Long idHojaRefractiva;
    private Long idHojaNeuroftalmologia;
    private Long idHojaOculoplastia;
    private Long idHojaPterigium;
    private Long idHojaGlaucoma;
    private Long idHojaOftalmologiaEsp;
    private Long idHojaOftAprb;
    private Long idHojaOftCrist;
    private String identificadorDocumento;
    private Long idSignosVitales;
    private Long idHojaAps;
    private Long idHojaSldOcupacional;
    private Long idEcografiaGinecologica;
    private Long idSolPcre;
    private Long idEcoAbdominal;
    private Long idSolEndoDigestivaSup;
    private Long idSolEndoDigestivaInf;
    private Long idSolRectosigmoidoscopia;
    private Long idEvolucion;
    private Long idInformeReposo;
    private Long idLactanciaMaterna;
    private Long idSolCitGin;
    private Long idHojaPreanestesica;
    private Long idSolCitologia;
    private Long idSolBiopsia;
    private Integer edadPaciente;
    private Boolean activo;
    private Long idReaccionAdversa;

    public HojaConsulta_RIS() {
    }

    public HojaConsulta_RIS(long id, Date fecha, Date horaFin,
                            long idCitaOrigen, Date horaInicio) {
        this.id = id;
        this.fecha = fecha;
        this.horaFin = horaFin;
        this.idCitaOrigen = idCitaOrigen;
        this.horaInicio = horaInicio;
    }

    public HojaConsulta_RIS(long id, Entidad_RIS entidad,
                            Long idIndicacionesMedicas, Long idConstancia, Long idReferencia,
                            Long idContrarreferencia, Long idOrdenAdmision,
                            Long idSolicitudAnalisisLab, Long idSolicitudExamenTipiaje,
                            Long idSolicitudIntervencionQ, Long idCitaConsulta, Date fecha,
                            Long idDiagnostico, String observaciones, String conclusiones,
                            Long idDiagnosticoPrincFinal, Long idHojaDermatologia,
                            Long idHojaGeneral, Long idHojaHemOncPediatrica,
                            Long idHojaRadioterapia, Long idHojaTriaje,
                            Long idHojaCirugiaColoRectal, Long idHojaGinecologia,
                            Long idHojaNeurologia, Long idHojaOftalmologia,
                            Long idHojaUroGenital, Long idHojaGastroenterologia,
                            Long idHojaHemOncologica, Long idHojaObstetricia, Long idHojaOrl,
                            Long idHojaTraumatologia, String motivo, String enfermedadActual,
                            Date horaFin, long idCitaOrigen, Boolean eliminado, Long cid,
                            Long idCitaTriajeGral, Long idTipoHoja, Long idEspecialidad,
                            Date horaInicio, Long idHojaRefractiva,
                            Long idHojaNeuroftalmologia, Long idHojaOculoplastia,
                            Long idHojaPterigium, Long idHojaGlaucoma,
                            Long idHojaOftalmologiaEsp, Long idHojaOftAprb,
                            Long idHojaOftCrist, String identificadorDocumento,
                            Long idSignosVitales, Long idHojaAps, Long idHojaSldOcupacional,
                            Long idEcografiaGinecologica, Long idSolPcre, Long idEcoAbdominal,
                            Long idSolEndoDigestivaSup, Long idSolEndoDigestivaInf,
                            Long idSolRectosigmoidoscopia, Long idEvolucion,
                            Long idInformeReposo, Long idLactanciaMaterna, Long idSolCitGin,
                            Long idHojaPreanestesica, Long idSolCitologia, Long idSolBiopsia,
                            Integer edadPaciente, Boolean activo, Long idReaccionAdversa) {
        this.id = id;
        this.entidad = entidad;
        this.idIndicacionesMedicas = idIndicacionesMedicas;
        this.idConstancia = idConstancia;
        this.idReferencia = idReferencia;
        this.idContrarreferencia = idContrarreferencia;
        this.idOrdenAdmision = idOrdenAdmision;
        this.idSolicitudAnalisisLab = idSolicitudAnalisisLab;
        this.idSolicitudExamenTipiaje = idSolicitudExamenTipiaje;
        this.idSolicitudIntervencionQ = idSolicitudIntervencionQ;
        this.idCitaConsulta = idCitaConsulta;
        this.fecha = fecha;
        this.idDiagnostico = idDiagnostico;
        this.observaciones = observaciones;
        this.conclusiones = conclusiones;
        this.idDiagnosticoPrincFinal = idDiagnosticoPrincFinal;
        this.idHojaDermatologia = idHojaDermatologia;
        this.idHojaGeneral = idHojaGeneral;
        this.idHojaHemOncPediatrica = idHojaHemOncPediatrica;
        this.idHojaRadioterapia = idHojaRadioterapia;
        this.idHojaTriaje = idHojaTriaje;
        this.idHojaCirugiaColoRectal = idHojaCirugiaColoRectal;
        this.idHojaGinecologia = idHojaGinecologia;
        this.idHojaNeurologia = idHojaNeurologia;
        this.idHojaOftalmologia = idHojaOftalmologia;
        this.idHojaUroGenital = idHojaUroGenital;
        this.idHojaGastroenterologia = idHojaGastroenterologia;
        this.idHojaHemOncologica = idHojaHemOncologica;
        this.idHojaObstetricia = idHojaObstetricia;
        this.idHojaOrl = idHojaOrl;
        this.idHojaTraumatologia = idHojaTraumatologia;
        this.motivo = motivo;
        this.enfermedadActual = enfermedadActual;
        this.horaFin = horaFin;
        this.idCitaOrigen = idCitaOrigen;
        this.eliminado = eliminado;
        this.cid = cid;
        this.idCitaTriajeGral = idCitaTriajeGral;
        this.idTipoHoja = idTipoHoja;
        this.idEspecialidad = idEspecialidad;
        this.horaInicio = horaInicio;
        this.idHojaRefractiva = idHojaRefractiva;
        this.idHojaNeuroftalmologia = idHojaNeuroftalmologia;
        this.idHojaOculoplastia = idHojaOculoplastia;
        this.idHojaPterigium = idHojaPterigium;
        this.idHojaGlaucoma = idHojaGlaucoma;
        this.idHojaOftalmologiaEsp = idHojaOftalmologiaEsp;
        this.idHojaOftAprb = idHojaOftAprb;
        this.idHojaOftCrist = idHojaOftCrist;
        this.identificadorDocumento = identificadorDocumento;
        this.idSignosVitales = idSignosVitales;
        this.idHojaAps = idHojaAps;
        this.idHojaSldOcupacional = idHojaSldOcupacional;
        this.idEcografiaGinecologica = idEcografiaGinecologica;
        this.idSolPcre = idSolPcre;
        this.idEcoAbdominal = idEcoAbdominal;
        this.idSolEndoDigestivaSup = idSolEndoDigestivaSup;
        this.idSolEndoDigestivaInf = idSolEndoDigestivaInf;
        this.idSolRectosigmoidoscopia = idSolRectosigmoidoscopia;
        this.idEvolucion = idEvolucion;
        this.idInformeReposo = idInformeReposo;
        this.idLactanciaMaterna = idLactanciaMaterna;
        this.idSolCitGin = idSolCitGin;
        this.idHojaPreanestesica = idHojaPreanestesica;
        this.idSolCitologia = idSolCitologia;
        this.idSolBiopsia = idSolBiopsia;
        this.edadPaciente = edadPaciente;
        this.activo = activo;
        this.idReaccionAdversa = idReaccionAdversa;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @Version
    @Column(name = "version")
    public Integer getVersion() {
        return this.version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_entidad")
    public Entidad_RIS getEntidad() {
        return this.entidad;
    }

    public void setEntidad(Entidad_RIS entidad) {
        this.entidad = entidad;
    }

    @Column(name = "id_indicaciones_medicas")
    public Long getIdIndicacionesMedicas() {
        return this.idIndicacionesMedicas;
    }

    public void setIdIndicacionesMedicas(Long idIndicacionesMedicas) {
        this.idIndicacionesMedicas = idIndicacionesMedicas;
    }

    @Column(name = "id_constancia")
    public Long getIdConstancia() {
        return this.idConstancia;
    }

    public void setIdConstancia(Long idConstancia) {
        this.idConstancia = idConstancia;
    }

    @Column(name = "id_referencia")
    public Long getIdReferencia() {
        return this.idReferencia;
    }

    public void setIdReferencia(Long idReferencia) {
        this.idReferencia = idReferencia;
    }

    @Column(name = "id_contrarreferencia")
    public Long getIdContrarreferencia() {
        return this.idContrarreferencia;
    }

    public void setIdContrarreferencia(Long idContrarreferencia) {
        this.idContrarreferencia = idContrarreferencia;
    }

    @Column(name = "id_orden_admision")
    public Long getIdOrdenAdmision() {
        return this.idOrdenAdmision;
    }

    public void setIdOrdenAdmision(Long idOrdenAdmision) {
        this.idOrdenAdmision = idOrdenAdmision;
    }

    @Column(name = "id_solicitud_analisis_lab")
    public Long getIdSolicitudAnalisisLab() {
        return this.idSolicitudAnalisisLab;
    }

    public void setIdSolicitudAnalisisLab(Long idSolicitudAnalisisLab) {
        this.idSolicitudAnalisisLab = idSolicitudAnalisisLab;
    }

    @Column(name = "id_solicitud_examen_tipiaje")
    public Long getIdSolicitudExamenTipiaje() {
        return this.idSolicitudExamenTipiaje;
    }

    public void setIdSolicitudExamenTipiaje(Long idSolicitudExamenTipiaje) {
        this.idSolicitudExamenTipiaje = idSolicitudExamenTipiaje;
    }

    @Column(name = "id_solicitud_intervencion_q")
    public Long getIdSolicitudIntervencionQ() {
        return this.idSolicitudIntervencionQ;
    }

    public void setIdSolicitudIntervencionQ(Long idSolicitudIntervencionQ) {
        this.idSolicitudIntervencionQ = idSolicitudIntervencionQ;
    }

    @Column(name = "id_cita_consulta")
    public Long getIdCitaConsulta() {
        return this.idCitaConsulta;
    }

    public void setIdCitaConsulta(Long idCitaConsulta) {
        this.idCitaConsulta = idCitaConsulta;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "fecha", nullable = false, length = 13)

    public Date getFecha() {
        return this.fecha;
    }

    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    @Column(name = "id_diagnostico")
    public Long getIdDiagnostico() {
        return this.idDiagnostico;
    }

    public void setIdDiagnostico(Long idDiagnostico) {
        this.idDiagnostico = idDiagnostico;
    }

    @Column(name = "observaciones")
    public String getObservaciones() {
        return this.observaciones;
    }

    public void setObservaciones(String observaciones) {
        if (observaciones != null)
            observaciones = observaciones.trim();
        this.observaciones = observaciones;
    }

    @Column(name = "conclusiones")
    public String getConclusiones() {
        return this.conclusiones;
    }

    public void setConclusiones(String conclusiones) {
        if (conclusiones != null)
            conclusiones = conclusiones.trim();
        this.conclusiones = conclusiones;
    }

    @Column(name = "id_diagnostico_princ_final")
    public Long getIdDiagnosticoPrincFinal() {
        return this.idDiagnosticoPrincFinal;
    }

    public void setIdDiagnosticoPrincFinal(Long idDiagnosticoPrincFinal) {
        this.idDiagnosticoPrincFinal = idDiagnosticoPrincFinal;
    }

    @Column(name = "id_hoja_dermatologia")
    public Long getIdHojaDermatologia() {
        return this.idHojaDermatologia;
    }

    public void setIdHojaDermatologia(Long idHojaDermatologia) {
        this.idHojaDermatologia = idHojaDermatologia;
    }

    @Column(name = "id_hoja_general")
    public Long getIdHojaGeneral() {
        return this.idHojaGeneral;
    }

    public void setIdHojaGeneral(Long idHojaGeneral) {
        this.idHojaGeneral = idHojaGeneral;
    }

    @Column(name = "id_hoja_hem_onc_pediatrica")
    public Long getIdHojaHemOncPediatrica() {
        return this.idHojaHemOncPediatrica;
    }

    public void setIdHojaHemOncPediatrica(Long idHojaHemOncPediatrica) {
        this.idHojaHemOncPediatrica = idHojaHemOncPediatrica;
    }

    @Column(name = "id_hoja_radioterapia")
    public Long getIdHojaRadioterapia() {
        return this.idHojaRadioterapia;
    }

    public void setIdHojaRadioterapia(Long idHojaRadioterapia) {
        this.idHojaRadioterapia = idHojaRadioterapia;
    }

    @Column(name = "id_hoja_triaje")
    public Long getIdHojaTriaje() {
        return this.idHojaTriaje;
    }

    public void setIdHojaTriaje(Long idHojaTriaje) {
        this.idHojaTriaje = idHojaTriaje;
    }

    @Column(name = "id_hoja_cirugia_colo_rectal")
    public Long getIdHojaCirugiaColoRectal() {
        return this.idHojaCirugiaColoRectal;
    }

    public void setIdHojaCirugiaColoRectal(Long idHojaCirugiaColoRectal) {
        this.idHojaCirugiaColoRectal = idHojaCirugiaColoRectal;
    }

    @Column(name = "id_hoja_ginecologia")
    public Long getIdHojaGinecologia() {
        return this.idHojaGinecologia;
    }

    public void setIdHojaGinecologia(Long idHojaGinecologia) {
        this.idHojaGinecologia = idHojaGinecologia;
    }

    @Column(name = "id_hoja_neurologia")
    public Long getIdHojaNeurologia() {
        return this.idHojaNeurologia;
    }

    public void setIdHojaNeurologia(Long idHojaNeurologia) {
        this.idHojaNeurologia = idHojaNeurologia;
    }

    @Column(name = "id_hoja_oftalmologia")
    public Long getIdHojaOftalmologia() {
        return this.idHojaOftalmologia;
    }

    public void setIdHojaOftalmologia(Long idHojaOftalmologia) {
        this.idHojaOftalmologia = idHojaOftalmologia;
    }

    @Column(name = "id_hoja_uro_genital")
    public Long getIdHojaUroGenital() {
        return this.idHojaUroGenital;
    }

    public void setIdHojaUroGenital(Long idHojaUroGenital) {
        this.idHojaUroGenital = idHojaUroGenital;
    }

    @Column(name = "id_hoja_gastroenterologia")
    public Long getIdHojaGastroenterologia() {
        return this.idHojaGastroenterologia;
    }

    public void setIdHojaGastroenterologia(Long idHojaGastroenterologia) {
        this.idHojaGastroenterologia = idHojaGastroenterologia;
    }

    @Column(name = "id_hoja_hem_oncologica")
    public Long getIdHojaHemOncologica() {
        return this.idHojaHemOncologica;
    }

    public void setIdHojaHemOncologica(Long idHojaHemOncologica) {
        this.idHojaHemOncologica = idHojaHemOncologica;
    }

    @Column(name = "id_hoja_obstetricia")
    public Long getIdHojaObstetricia() {
        return this.idHojaObstetricia;
    }

    public void setIdHojaObstetricia(Long idHojaObstetricia) {
        this.idHojaObstetricia = idHojaObstetricia;
    }

    @Column(name = "id_hoja_orl")
    public Long getIdHojaOrl() {
        return this.idHojaOrl;
    }

    public void setIdHojaOrl(Long idHojaOrl) {
        this.idHojaOrl = idHojaOrl;
    }

    @Column(name = "id_hoja_traumatologia")
    public Long getIdHojaTraumatologia() {
        return this.idHojaTraumatologia;
    }

    public void setIdHojaTraumatologia(Long idHojaTraumatologia) {
        this.idHojaTraumatologia = idHojaTraumatologia;
    }

    @Column(name = "motivo")
    public String getMotivo() {
        return this.motivo;
    }

    public void setMotivo(String motivo) {
        if (motivo != null)
            motivo = motivo.trim();
        this.motivo = motivo;
    }

    @Column(name = "enfermedad_actual")
    public String getEnfermedadActual() {
        return this.enfermedadActual;
    }

    public void setEnfermedadActual(String enfermedadActual) {
        if (enfermedadActual != null)
            enfermedadActual = enfermedadActual.trim();
        this.enfermedadActual = enfermedadActual;
    }

    @Temporal(TemporalType.TIME)
    @Column(name = "hora_fin", nullable = false, length = 8)

    public Date getHoraFin() {
        return this.horaFin;
    }

    public void setHoraFin(Date horaFin) {
        this.horaFin = horaFin;
    }

    @Column(name = "id_cita_origen", nullable = false)

    public long getIdCitaOrigen() {
        return this.idCitaOrigen;
    }

    public void setIdCitaOrigen(long idCitaOrigen) {
        this.idCitaOrigen = idCitaOrigen;
    }

    @Column(name = "eliminado")
    public Boolean getEliminado() {
        return this.eliminado;
    }

    public void setEliminado(Boolean eliminado) {
        this.eliminado = eliminado;
    }

    @Column(name = "cid")
    public Long getCid() {
        return this.cid;
    }

    public void setCid(Long cid) {
        this.cid = cid;
    }

    @Column(name = "id_cita_triaje_gral")
    public Long getIdCitaTriajeGral() {
        return this.idCitaTriajeGral;
    }

    public void setIdCitaTriajeGral(Long idCitaTriajeGral) {
        this.idCitaTriajeGral = idCitaTriajeGral;
    }

    @Column(name = "id_tipo_hoja")
    public Long getIdTipoHoja() {
        return this.idTipoHoja;
    }

    public void setIdTipoHoja(Long idTipoHoja) {
        this.idTipoHoja = idTipoHoja;
    }

    @Column(name = "id_especialidad")
    public Long getIdEspecialidad() {
        return this.idEspecialidad;
    }

    public void setIdEspecialidad(Long idEspecialidad) {
        this.idEspecialidad = idEspecialidad;
    }

    @Temporal(TemporalType.TIME)
    @Column(name = "hora_inicio", nullable = false, length = 8)

    public Date getHoraInicio() {
        return this.horaInicio;
    }

    public void setHoraInicio(Date horaInicio) {
        this.horaInicio = horaInicio;
    }

    @Column(name = "id_hoja_refractiva")
    public Long getIdHojaRefractiva() {
        return this.idHojaRefractiva;
    }

    public void setIdHojaRefractiva(Long idHojaRefractiva) {
        this.idHojaRefractiva = idHojaRefractiva;
    }

    @Column(name = "id_hoja_neuroftalmologia")
    public Long getIdHojaNeuroftalmologia() {
        return this.idHojaNeuroftalmologia;
    }

    public void setIdHojaNeuroftalmologia(Long idHojaNeuroftalmologia) {
        this.idHojaNeuroftalmologia = idHojaNeuroftalmologia;
    }

    @Column(name = "id_hoja_oculoplastia")
    public Long getIdHojaOculoplastia() {
        return this.idHojaOculoplastia;
    }

    public void setIdHojaOculoplastia(Long idHojaOculoplastia) {
        this.idHojaOculoplastia = idHojaOculoplastia;
    }

    @Column(name = "id_hoja_pterigium")
    public Long getIdHojaPterigium() {
        return this.idHojaPterigium;
    }

    public void setIdHojaPterigium(Long idHojaPterigium) {
        this.idHojaPterigium = idHojaPterigium;
    }

    @Column(name = "id_hoja_glaucoma")
    public Long getIdHojaGlaucoma() {
        return this.idHojaGlaucoma;
    }

    public void setIdHojaGlaucoma(Long idHojaGlaucoma) {
        this.idHojaGlaucoma = idHojaGlaucoma;
    }

    @Column(name = "id_hoja_oftalmologia_esp")
    public Long getIdHojaOftalmologiaEsp() {
        return this.idHojaOftalmologiaEsp;
    }

    public void setIdHojaOftalmologiaEsp(Long idHojaOftalmologiaEsp) {
        this.idHojaOftalmologiaEsp = idHojaOftalmologiaEsp;
    }

    @Column(name = "id_hoja_oft_aprb")
    public Long getIdHojaOftAprb() {
        return this.idHojaOftAprb;
    }

    public void setIdHojaOftAprb(Long idHojaOftAprb) {
        this.idHojaOftAprb = idHojaOftAprb;
    }

    @Column(name = "id_hoja_oft_crist")
    public Long getIdHojaOftCrist() {
        return this.idHojaOftCrist;
    }

    public void setIdHojaOftCrist(Long idHojaOftCrist) {
        this.idHojaOftCrist = idHojaOftCrist;
    }

    @Column(name = "identificador_documento")
    public String getIdentificadorDocumento() {
        return this.identificadorDocumento;
    }

    public void setIdentificadorDocumento(String identificadorDocumento) {
        if (identificadorDocumento != null)
            identificadorDocumento = identificadorDocumento.trim();
        this.identificadorDocumento = identificadorDocumento;
    }

    @Column(name = "id_signos_vitales")
    public Long getIdSignosVitales() {
        return this.idSignosVitales;
    }

    public void setIdSignosVitales(Long idSignosVitales) {
        this.idSignosVitales = idSignosVitales;
    }

    @Column(name = "id_hoja_aps")
    public Long getIdHojaAps() {
        return this.idHojaAps;
    }

    public void setIdHojaAps(Long idHojaAps) {
        this.idHojaAps = idHojaAps;
    }

    @Column(name = "id_hoja_sld_ocupacional")
    public Long getIdHojaSldOcupacional() {
        return this.idHojaSldOcupacional;
    }

    public void setIdHojaSldOcupacional(Long idHojaSldOcupacional) {
        this.idHojaSldOcupacional = idHojaSldOcupacional;
    }

    @Column(name = "id_ecografia_ginecologica")
    public Long getIdEcografiaGinecologica() {
        return this.idEcografiaGinecologica;
    }

    public void setIdEcografiaGinecologica(Long idEcografiaGinecologica) {
        this.idEcografiaGinecologica = idEcografiaGinecologica;
    }

    @Column(name = "id_sol_pcre")
    public Long getIdSolPcre() {
        return this.idSolPcre;
    }

    public void setIdSolPcre(Long idSolPcre) {
        this.idSolPcre = idSolPcre;
    }

    @Column(name = "id_eco_abdominal")
    public Long getIdEcoAbdominal() {
        return this.idEcoAbdominal;
    }

    public void setIdEcoAbdominal(Long idEcoAbdominal) {
        this.idEcoAbdominal = idEcoAbdominal;
    }

    @Column(name = "id_sol_endo_digestiva_sup")
    public Long getIdSolEndoDigestivaSup() {
        return this.idSolEndoDigestivaSup;
    }

    public void setIdSolEndoDigestivaSup(Long idSolEndoDigestivaSup) {
        this.idSolEndoDigestivaSup = idSolEndoDigestivaSup;
    }

    @Column(name = "id_sol_endo_digestiva_inf")
    public Long getIdSolEndoDigestivaInf() {
        return this.idSolEndoDigestivaInf;
    }

    public void setIdSolEndoDigestivaInf(Long idSolEndoDigestivaInf) {
        this.idSolEndoDigestivaInf = idSolEndoDigestivaInf;
    }

    @Column(name = "id_sol_rectosigmoidoscopia")
    public Long getIdSolRectosigmoidoscopia() {
        return this.idSolRectosigmoidoscopia;
    }

    public void setIdSolRectosigmoidoscopia(Long idSolRectosigmoidoscopia) {
        this.idSolRectosigmoidoscopia = idSolRectosigmoidoscopia;
    }

    @Column(name = "id_evolucion")
    public Long getIdEvolucion() {
        return this.idEvolucion;
    }

    public void setIdEvolucion(Long idEvolucion) {
        this.idEvolucion = idEvolucion;
    }

    @Column(name = "id_informe_reposo")
    public Long getIdInformeReposo() {
        return this.idInformeReposo;
    }

    public void setIdInformeReposo(Long idInformeReposo) {
        this.idInformeReposo = idInformeReposo;
    }

    @Column(name = "id_lactancia_materna")
    public Long getIdLactanciaMaterna() {
        return this.idLactanciaMaterna;
    }

    public void setIdLactanciaMaterna(Long idLactanciaMaterna) {
        this.idLactanciaMaterna = idLactanciaMaterna;
    }

    @Column(name = "id_sol_cit_gin")
    public Long getIdSolCitGin() {
        return this.idSolCitGin;
    }

    public void setIdSolCitGin(Long idSolCitGin) {
        this.idSolCitGin = idSolCitGin;
    }

    @Column(name = "id_hoja_preanestesica")
    public Long getIdHojaPreanestesica() {
        return this.idHojaPreanestesica;
    }

    public void setIdHojaPreanestesica(Long idHojaPreanestesica) {
        this.idHojaPreanestesica = idHojaPreanestesica;
    }

    @Column(name = "id_sol_citologia")
    public Long getIdSolCitologia() {
        return this.idSolCitologia;
    }

    public void setIdSolCitologia(Long idSolCitologia) {
        this.idSolCitologia = idSolCitologia;
    }

    @Column(name = "id_sol_biopsia")
    public Long getIdSolBiopsia() {
        return this.idSolBiopsia;
    }

    public void setIdSolBiopsia(Long idSolBiopsia) {
        this.idSolBiopsia = idSolBiopsia;
    }

    @Column(name = "edad_paciente")
    public Integer getEdadPaciente() {
        return this.edadPaciente;
    }

    public void setEdadPaciente(Integer edadPaciente) {
        this.edadPaciente = edadPaciente;
    }

    @Column(name = "activo")
    public Boolean getActivo() {
        return this.activo;
    }

    public void setActivo(Boolean activo) {
        this.activo = activo;
    }

    @Column(name = "id_reaccion_adversa")
    public Long getIdReaccionAdversa() {
        return this.idReaccionAdversa;
    }

    public void setIdReaccionAdversa(Long idReaccionAdversa) {
        this.idReaccionAdversa = idReaccionAdversa;
    }

}
