package cu.uci.cesim.hce_back.estadisticas.model.entity.auto.ris;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

// Generated May 21, 2012 5:42:06 PM by Hibernate Tools 3.4.0.CR1

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;
import org.hibernate.validator.constraints.Length;

import javax.persistence.*;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * HojaFrontal generated by hbm2java
 */
@Entity
@Table(name = "hoja_frontal", schema = "hc_local")
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "id")
public class HojaFrontal_RIS implements java.io.Serializable {

    private long id;
    private Integer version;
    private Persona_RIS personaById;
    private Status_RIS status;
    private Persona_RIS personaByIdAvisarEmergencia;
    private Long idGrupoSanguineo;
    private String puntoReferencia;
    private Integer tiempoResidencia;
    private Long idAntPrenatObst;
    private Long idPeriodoNeonatal;
    private Long idAlimentacion;
    private Long idDesarrollo;
    private Long idAntSexReprod;
    private Long idFactorSanguineo;
    private Long cid;
    private Boolean eliminado;
    private Long idAntGinecoObstetrico;
    private long idTipoHojaFrontal;
    private Long idAntHematoOnc;
    private Boolean estaEmbarazada;
    private String descripcionDesconocido;
    private Date fechaCreada;
    private boolean desconocido;
    private Integer idRis;
    private Long idProblemasDetectados;
    private String numeroHc;
    private Boolean tieneCda;
    private Set<Solicitud_RIS> solicituds = new HashSet<Solicitud_RIS>(
            0);

    public HojaFrontal_RIS() {
    }

    public HojaFrontal_RIS(Persona_RIS personaById,
                           long idTipoHojaFrontal, Date fechaCreada, boolean desconocido,
                           String numeroHc) {
        this.personaById = personaById;
        this.idTipoHojaFrontal = idTipoHojaFrontal;
        this.fechaCreada = fechaCreada;
        this.desconocido = desconocido;
        this.numeroHc = numeroHc;
    }

    public HojaFrontal_RIS(Persona_RIS personaById,
                           Status_RIS status,
                           Persona_RIS personaByIdAvisarEmergencia,
                           Long idGrupoSanguineo, String puntoReferencia,
                           Integer tiempoResidencia, Long idAntPrenatObst,
                           Long idPeriodoNeonatal, Long idAlimentacion, Long idDesarrollo,
                           Long idAntSexReprod, Long idFactorSanguineo, Long cid,
                           Boolean eliminado, Long idAntGinecoObstetrico,
                           long idTipoHojaFrontal, Long idAntHematoOnc,
                           Boolean estaEmbarazada, String descripcionDesconocido,
                           Date fechaCreada, boolean desconocido, Integer idRis,
                           Long idProblemasDetectados, String numeroHc, Boolean tieneCda,
                           Set<Solicitud_RIS> solicituds) {
        this.personaById = personaById;
        this.status = status;
        this.personaByIdAvisarEmergencia = personaByIdAvisarEmergencia;
        this.idGrupoSanguineo = idGrupoSanguineo;
        this.puntoReferencia = puntoReferencia;
        this.tiempoResidencia = tiempoResidencia;
        this.idAntPrenatObst = idAntPrenatObst;
        this.idPeriodoNeonatal = idPeriodoNeonatal;
        this.idAlimentacion = idAlimentacion;
        this.idDesarrollo = idDesarrollo;
        this.idAntSexReprod = idAntSexReprod;
        this.idFactorSanguineo = idFactorSanguineo;
        this.cid = cid;
        this.eliminado = eliminado;
        this.idAntGinecoObstetrico = idAntGinecoObstetrico;
        this.idTipoHojaFrontal = idTipoHojaFrontal;
        this.idAntHematoOnc = idAntHematoOnc;
        this.estaEmbarazada = estaEmbarazada;
        this.descripcionDesconocido = descripcionDesconocido;
        this.fechaCreada = fechaCreada;
        this.desconocido = desconocido;
        this.idRis = idRis;
        this.idProblemasDetectados = idProblemasDetectados;
        this.numeroHc = numeroHc;
        this.tieneCda = tieneCda;
        this.solicituds = solicituds;
    }

    @GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "personaById"))
    @Id
    @GeneratedValue(generator = "generator")
    @Column(name = "id", unique = true, nullable = false)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @Version
    @Column(name = "version")
    public Integer getVersion() {
        return this.version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    @OneToOne(fetch = FetchType.LAZY)
    @PrimaryKeyJoinColumn

    public Persona_RIS getPersonaById() {
        return this.personaById;
    }

    public void setPersonaById(Persona_RIS personaById) {
        this.personaById = personaById;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_status")
    public Status_RIS getStatus() {
        return this.status;
    }

    public void setStatus(Status_RIS status) {
        this.status = status;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_avisar_emergencia")
    public Persona_RIS getPersonaByIdAvisarEmergencia() {
        return this.personaByIdAvisarEmergencia;
    }

    public void setPersonaByIdAvisarEmergencia(
            Persona_RIS personaByIdAvisarEmergencia) {
        this.personaByIdAvisarEmergencia = personaByIdAvisarEmergencia;
    }

    @Column(name = "id_grupo_sanguineo")
    public Long getIdGrupoSanguineo() {
        return this.idGrupoSanguineo;
    }

    public void setIdGrupoSanguineo(Long idGrupoSanguineo) {
        this.idGrupoSanguineo = idGrupoSanguineo;
    }

    @Column(name = "punto_referencia", length = 100)
    @Length(max = 100)
    public String getPuntoReferencia() {
        return this.puntoReferencia;
    }

    public void setPuntoReferencia(String puntoReferencia) {
        if (puntoReferencia != null)
            puntoReferencia = puntoReferencia.trim();
        this.puntoReferencia = puntoReferencia;
    }

    @Column(name = "tiempo_residencia")
    public Integer getTiempoResidencia() {
        return this.tiempoResidencia;
    }

    public void setTiempoResidencia(Integer tiempoResidencia) {
        this.tiempoResidencia = tiempoResidencia;
    }

    @Column(name = "id_ant_prenat_obst")
    public Long getIdAntPrenatObst() {
        return this.idAntPrenatObst;
    }

    public void setIdAntPrenatObst(Long idAntPrenatObst) {
        this.idAntPrenatObst = idAntPrenatObst;
    }

    @Column(name = "id_periodo_neonatal")
    public Long getIdPeriodoNeonatal() {
        return this.idPeriodoNeonatal;
    }

    public void setIdPeriodoNeonatal(Long idPeriodoNeonatal) {
        this.idPeriodoNeonatal = idPeriodoNeonatal;
    }

    @Column(name = "id_alimentacion")
    public Long getIdAlimentacion() {
        return this.idAlimentacion;
    }

    public void setIdAlimentacion(Long idAlimentacion) {
        this.idAlimentacion = idAlimentacion;
    }

    @Column(name = "id_desarrollo")
    public Long getIdDesarrollo() {
        return this.idDesarrollo;
    }

    public void setIdDesarrollo(Long idDesarrollo) {
        this.idDesarrollo = idDesarrollo;
    }

    @Column(name = "id_ant_sex_reprod")
    public Long getIdAntSexReprod() {
        return this.idAntSexReprod;
    }

    public void setIdAntSexReprod(Long idAntSexReprod) {
        this.idAntSexReprod = idAntSexReprod;
    }

    @Column(name = "id_factor_sanguineo")
    public Long getIdFactorSanguineo() {
        return this.idFactorSanguineo;
    }

    public void setIdFactorSanguineo(Long idFactorSanguineo) {
        this.idFactorSanguineo = idFactorSanguineo;
    }

    @Column(name = "cid")
    public Long getCid() {
        return this.cid;
    }

    public void setCid(Long cid) {
        this.cid = cid;
    }

    @Column(name = "eliminado")
    public Boolean getEliminado() {
        return this.eliminado;
    }

    public void setEliminado(Boolean eliminado) {
        this.eliminado = eliminado;
    }

    @Column(name = "id_ant_gineco_obstetrico")
    public Long getIdAntGinecoObstetrico() {
        return this.idAntGinecoObstetrico;
    }

    public void setIdAntGinecoObstetrico(Long idAntGinecoObstetrico) {
        this.idAntGinecoObstetrico = idAntGinecoObstetrico;
    }

    @Column(name = "id_tipo_hoja_frontal", nullable = false)

    public long getIdTipoHojaFrontal() {
        return this.idTipoHojaFrontal;
    }

    public void setIdTipoHojaFrontal(long idTipoHojaFrontal) {
        this.idTipoHojaFrontal = idTipoHojaFrontal;
    }

    @Column(name = "id_ant_hemato_onc")
    public Long getIdAntHematoOnc() {
        return this.idAntHematoOnc;
    }

    public void setIdAntHematoOnc(Long idAntHematoOnc) {
        this.idAntHematoOnc = idAntHematoOnc;
    }

    @Column(name = "esta_embarazada")
    public Boolean getEstaEmbarazada() {
        return this.estaEmbarazada;
    }

    public void setEstaEmbarazada(Boolean estaEmbarazada) {
        this.estaEmbarazada = estaEmbarazada;
    }

    @Column(name = "descripcion_desconocido")
    public String getDescripcionDesconocido() {
        return this.descripcionDesconocido;
    }

    public void setDescripcionDesconocido(String descripcionDesconocido) {
        if (descripcionDesconocido != null)
            descripcionDesconocido = descripcionDesconocido.trim();
        this.descripcionDesconocido = descripcionDesconocido;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "fecha_creada", nullable = false, length = 13)

    public Date getFechaCreada() {
        return this.fechaCreada;
    }

    public void setFechaCreada(Date fechaCreada) {
        this.fechaCreada = fechaCreada;
    }

    @Column(name = "desconocido", nullable = false)

    public boolean isDesconocido() {
        return this.desconocido;
    }

    public void setDesconocido(boolean desconocido) {
        this.desconocido = desconocido;
    }

    @Column(name = "id_ris")
    public Integer getIdRis() {
        return this.idRis;
    }

    public void setIdRis(Integer idRis) {
        this.idRis = idRis;
    }

    @Column(name = "id_problemas_detectados")
    public Long getIdProblemasDetectados() {
        return this.idProblemasDetectados;
    }

    public void setIdProblemasDetectados(Long idProblemasDetectados) {
        this.idProblemasDetectados = idProblemasDetectados;
    }

    @Column(name = "numero_hc", nullable = false)

    public String getNumeroHc() {
        return this.numeroHc;
    }

    public void setNumeroHc(String numeroHc) {
        if (numeroHc != null)
            numeroHc = numeroHc.trim();
        this.numeroHc = numeroHc;
    }

    @Column(name = "tiene_cda")
    public Boolean getTieneCda() {
        return this.tieneCda;
    }

    public void setTieneCda(Boolean tieneCda) {
        this.tieneCda = tieneCda;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "hojaFrontal")
    public Set<Solicitud_RIS> getSolicituds() {
        return this.solicituds;
    }

    public void setSolicituds(Set<Solicitud_RIS> solicituds) {
        this.solicituds = solicituds;
    }

}
