package cu.uci.cesim.hce_back.estadisticas.model.entity.auto.ris;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

// Generated May 21, 2012 5:42:06 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;


/**
 * Modalidad generated by hbm2java
 */
@Entity
@Table(name = "modalidad", schema = "ris")
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "id")
public class Modalidad_RIS implements java.io.Serializable {

    private long idHis;
    private String modalidad;
    private Long cid;
    private Long idApplication;
    private Integer id;
    private Set<TipoEstudio_RIS> tipoEstudios = new HashSet<TipoEstudio_RIS>(
            0);

    public Modalidad_RIS() {
    }

    public Modalidad_RIS(long idHis) {
        this.idHis = idHis;
    }

    public Modalidad_RIS(long idHis, String modalidad, Long cid,
                         Long idApplication, Integer id,
                         Set<TipoEstudio_RIS> tipoEstudios) {
        this.idHis = idHis;
        this.modalidad = modalidad;
        this.cid = cid;
        this.idApplication = idApplication;
        this.id = id;
        this.tipoEstudios = tipoEstudios;
    }

    @Id
    @Column(name = "id_his", unique = true, nullable = false)

    public long getIdHis() {
        return this.idHis;
    }

    public void setIdHis(long idHis) {
        this.idHis = idHis;
    }

    @Column(name = "modalidad")
    public String getModalidad() {
        return this.modalidad;
    }

    public void setModalidad(String modalidad) {
        if (modalidad != null)
            modalidad = modalidad.trim();
        this.modalidad = modalidad;
    }

    @Column(name = "cid")
    public Long getCid() {
        return this.cid;
    }

    public void setCid(Long cid) {
        this.cid = cid;
    }

    @Column(name = "id_application")
    public Long getIdApplication() {
        return this.idApplication;
    }

    public void setIdApplication(Long idApplication) {
        this.idApplication = idApplication;
    }

    @Column(name = "id")
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "modalidad")
    public Set<TipoEstudio_RIS> getTipoEstudios() {
        return this.tipoEstudios;
    }

    public void setTipoEstudios(Set<TipoEstudio_RIS> tipoEstudios) {
        this.tipoEstudios = tipoEstudios;
    }

}
