package cu.uci.cesim.hce_back.estadisticas.model.entity.auto.ris;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

// Generated May 21, 2012 5:42:06 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;


/**
 * Nacion generated by hbm2java
 */
@Entity
@Table(name = "nacion", schema = "nomencladores", uniqueConstraints = {
        @UniqueConstraint(columnNames = "valor"),
        @UniqueConstraint(columnNames = "nacionalidad")})
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "id")
public class Nacion_RIS implements java.io.Serializable {

    private long id;
    private Integer version;
    private String valor;
    private String nacionalidad;
    private Boolean eliminado;
    private Long cid;
    private String codigo;
    private Set<PersonaHist_RIS> personaHists = new HashSet<PersonaHist_RIS>(
            0);
    private Set<Persona_RIS> personas = new HashSet<Persona_RIS>(
            0);

    public Nacion_RIS() {
    }

    public Nacion_RIS(long id, String valor, String nacionalidad) {
        this.id = id;
        this.valor = valor;
        this.nacionalidad = nacionalidad;
    }

    public Nacion_RIS(long id, String valor, String nacionalidad,
                      Boolean eliminado, Long cid, String codigo,
                      Set<PersonaHist_RIS> personaHists,
                      Set<Persona_RIS> personas) {
        this.id = id;
        this.valor = valor;
        this.nacionalidad = nacionalidad;
        this.eliminado = eliminado;
        this.cid = cid;
        this.codigo = codigo;
        this.personaHists = personaHists;
        this.personas = personas;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @Version
    @Column(name = "version")
    public Integer getVersion() {
        return this.version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    @Column(name = "valor", unique = true, nullable = false)

    public String getValor() {
        return this.valor;
    }

    public void setValor(String valor) {
        if (valor != null)
            valor = valor.trim();
        this.valor = valor;
    }

    @Column(name = "nacionalidad", unique = true, nullable = false)

    public String getNacionalidad() {
        return this.nacionalidad;
    }

    public void setNacionalidad(String nacionalidad) {
        if (nacionalidad != null)
            nacionalidad = nacionalidad.trim();
        this.nacionalidad = nacionalidad;
    }

    @Column(name = "eliminado")
    public Boolean getEliminado() {
        return this.eliminado;
    }

    public void setEliminado(Boolean eliminado) {
        this.eliminado = eliminado;
    }

    @Column(name = "cid")
    public Long getCid() {
        return this.cid;
    }

    public void setCid(Long cid) {
        this.cid = cid;
    }

    @Column(name = "codigo")
    public String getCodigo() {
        return this.codigo;
    }

    public void setCodigo(String codigo) {
        if (codigo != null)
            codigo = codigo.trim();
        this.codigo = codigo;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "nacion")
    public Set<PersonaHist_RIS> getPersonaHists() {
        return this.personaHists;
    }

    public void setPersonaHists(Set<PersonaHist_RIS> personaHists) {
        this.personaHists = personaHists;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "nacion")
    public Set<Persona_RIS> getPersonas() {
        return this.personas;
    }

    public void setPersonas(Set<Persona_RIS> personas) {
        this.personas = personas;
    }

}
