package cu.uci.cesim.hce_back.estadisticas.model.entity.auto.ris;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

// Generated May 21, 2012 5:42:06 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.*;
import java.util.Date;


/**
 * PersonaHist generated by hbm2java
 */
@Entity
@Table(name = "persona_hist", schema = "estadisticas")
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "id")
public class PersonaHist_RIS implements java.io.Serializable {

    private long id;
    private Integer version;
    private Sexo_RIS sexo;
    private Nacion_RIS nacion;
    private Persona_RIS persona;
    private Status_RIS status;
    private Date fechaRegistro;
    private Long cid;
    private Boolean eliminado;
    private Long idGrupoSanguineo;
    private Long idFactorSanguineo;
    private Long idTipoHojaFrontal;
    private String descripcionDesconocido;
    private Date fechaHojaFrontalCreada;
    private Boolean desconocido;
    private String noHc;
    private String cedula;
    private Long idEstadoCivil;
    private Long idLugarNacimiento;
    private Long idDireccionParticular;
    private Long idLugarResidencia;
    private Long idFormacion;
    private Long idGrupoPersonal;
    private Long idEstadoLaboral;
    private Long idAreaPersonal;
    private Long idDivisionPersonal;
    private Long idDivision;
    private Long idSubdivisionPersonal;
    private Long idSociedad;
    private Long idUnidadOrganizativa;
    private String telefonoOficina;
    private Long idPosicion;
    private Long idManoDominante;
    private String numeroPersonal;
    private Boolean aseguradoIvss;
    private Long idTipoZonaLaboral;
    private Integer numHijos;
    private Date tiempoServicio;
    private Date fechaNacimiento;
    private Long idRaza;
    private Long idEtnia;

    public PersonaHist_RIS() {
    }

    public PersonaHist_RIS(long id) {
        this.id = id;
    }

    public PersonaHist_RIS(long id, Sexo_RIS sexo,
                           Nacion_RIS nacion, Persona_RIS persona,
                           Status_RIS status, Date fechaRegistro, Long cid,
                           Boolean eliminado, Long idGrupoSanguineo, Long idFactorSanguineo,
                           Long idTipoHojaFrontal, String descripcionDesconocido,
                           Date fechaHojaFrontalCreada, Boolean desconocido, String noHc,
                           String cedula, Long idEstadoCivil, Long idLugarNacimiento,
                           Long idDireccionParticular, Long idLugarResidencia,
                           Long idFormacion, Long idGrupoPersonal, Long idEstadoLaboral,
                           Long idAreaPersonal, Long idDivisionPersonal, Long idDivision,
                           Long idSubdivisionPersonal, Long idSociedad,
                           Long idUnidadOrganizativa, String telefonoOficina, Long idPosicion,
                           Long idManoDominante, String numeroPersonal, Boolean aseguradoIvss,
                           Long idTipoZonaLaboral, Integer numHijos, Date tiempoServicio,
                           Date fechaNacimiento, Long idRaza, Long idEtnia) {
        this.id = id;
        this.sexo = sexo;
        this.nacion = nacion;
        this.persona = persona;
        this.status = status;
        this.fechaRegistro = fechaRegistro;
        this.cid = cid;
        this.eliminado = eliminado;
        this.idGrupoSanguineo = idGrupoSanguineo;
        this.idFactorSanguineo = idFactorSanguineo;
        this.idTipoHojaFrontal = idTipoHojaFrontal;
        this.descripcionDesconocido = descripcionDesconocido;
        this.fechaHojaFrontalCreada = fechaHojaFrontalCreada;
        this.desconocido = desconocido;
        this.noHc = noHc;
        this.cedula = cedula;
        this.idEstadoCivil = idEstadoCivil;
        this.idLugarNacimiento = idLugarNacimiento;
        this.idDireccionParticular = idDireccionParticular;
        this.idLugarResidencia = idLugarResidencia;
        this.idFormacion = idFormacion;
        this.idGrupoPersonal = idGrupoPersonal;
        this.idEstadoLaboral = idEstadoLaboral;
        this.idAreaPersonal = idAreaPersonal;
        this.idDivisionPersonal = idDivisionPersonal;
        this.idDivision = idDivision;
        this.idSubdivisionPersonal = idSubdivisionPersonal;
        this.idSociedad = idSociedad;
        this.idUnidadOrganizativa = idUnidadOrganizativa;
        this.telefonoOficina = telefonoOficina;
        this.idPosicion = idPosicion;
        this.idManoDominante = idManoDominante;
        this.numeroPersonal = numeroPersonal;
        this.aseguradoIvss = aseguradoIvss;
        this.idTipoZonaLaboral = idTipoZonaLaboral;
        this.numHijos = numHijos;
        this.tiempoServicio = tiempoServicio;
        this.fechaNacimiento = fechaNacimiento;
        this.idRaza = idRaza;
        this.idEtnia = idEtnia;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @Version
    @Column(name = "version")
    public Integer getVersion() {
        return this.version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_sexo")
    public Sexo_RIS getSexo() {
        return this.sexo;
    }

    public void setSexo(Sexo_RIS sexo) {
        this.sexo = sexo;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_nacion")
    public Nacion_RIS getNacion() {
        return this.nacion;
    }

    public void setNacion(Nacion_RIS nacion) {
        this.nacion = nacion;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_persona")
    public Persona_RIS getPersona() {
        return this.persona;
    }

    public void setPersona(Persona_RIS persona) {
        this.persona = persona;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_status")
    public Status_RIS getStatus() {
        return this.status;
    }

    public void setStatus(Status_RIS status) {
        this.status = status;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "fecha_registro", length = 29, nullable = false)

    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }

    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }

    @Column(name = "cid")
    public Long getCid() {
        return this.cid;
    }

    public void setCid(Long cid) {
        this.cid = cid;
    }

    @Column(name = "eliminado")
    public Boolean getEliminado() {
        return this.eliminado;
    }

    public void setEliminado(Boolean eliminado) {
        this.eliminado = eliminado;
    }

    @Column(name = "id_grupo_sanguineo")
    public Long getIdGrupoSanguineo() {
        return this.idGrupoSanguineo;
    }

    public void setIdGrupoSanguineo(Long idGrupoSanguineo) {
        this.idGrupoSanguineo = idGrupoSanguineo;
    }

    @Column(name = "id_factor_sanguineo")
    public Long getIdFactorSanguineo() {
        return this.idFactorSanguineo;
    }

    public void setIdFactorSanguineo(Long idFactorSanguineo) {
        this.idFactorSanguineo = idFactorSanguineo;
    }

    @Column(name = "id_tipo_hoja_frontal")
    public Long getIdTipoHojaFrontal() {
        return this.idTipoHojaFrontal;
    }

    public void setIdTipoHojaFrontal(Long idTipoHojaFrontal) {
        this.idTipoHojaFrontal = idTipoHojaFrontal;
    }

    @Column(name = "descripcion_desconocido")
    public String getDescripcionDesconocido() {
        return this.descripcionDesconocido;
    }

    public void setDescripcionDesconocido(String descripcionDesconocido) {
        if (descripcionDesconocido != null)
            descripcionDesconocido = descripcionDesconocido.trim();
        this.descripcionDesconocido = descripcionDesconocido;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "fecha_hoja_frontal_creada", length = 13)
    public Date getFechaHojaFrontalCreada() {
        return this.fechaHojaFrontalCreada;
    }

    public void setFechaHojaFrontalCreada(Date fechaHojaFrontalCreada) {
        this.fechaHojaFrontalCreada = fechaHojaFrontalCreada;
    }

    @Column(name = "desconocido")
    public Boolean getDesconocido() {
        return this.desconocido;
    }

    public void setDesconocido(Boolean desconocido) {
        this.desconocido = desconocido;
    }

    @Column(name = "no_hc")
    public String getNoHc() {
        return this.noHc;
    }

    public void setNoHc(String noHc) {
        if (noHc != null)
            noHc = noHc.trim();
        this.noHc = noHc;
    }

    @Column(name = "cedula")
    public String getCedula() {
        return this.cedula;
    }

    public void setCedula(String cedula) {
        if (cedula != null)
            cedula = cedula.trim();
        this.cedula = cedula;
    }

    @Column(name = "id_estado_civil")
    public Long getIdEstadoCivil() {
        return this.idEstadoCivil;
    }

    public void setIdEstadoCivil(Long idEstadoCivil) {
        this.idEstadoCivil = idEstadoCivil;
    }

    @Column(name = "id_lugar_nacimiento")
    public Long getIdLugarNacimiento() {
        return this.idLugarNacimiento;
    }

    public void setIdLugarNacimiento(Long idLugarNacimiento) {
        this.idLugarNacimiento = idLugarNacimiento;
    }

    @Column(name = "id_direccion_particular")
    public Long getIdDireccionParticular() {
        return this.idDireccionParticular;
    }

    public void setIdDireccionParticular(Long idDireccionParticular) {
        this.idDireccionParticular = idDireccionParticular;
    }

    @Column(name = "id_lugar_residencia")
    public Long getIdLugarResidencia() {
        return this.idLugarResidencia;
    }

    public void setIdLugarResidencia(Long idLugarResidencia) {
        this.idLugarResidencia = idLugarResidencia;
    }

    @Column(name = "id_formacion")
    public Long getIdFormacion() {
        return this.idFormacion;
    }

    public void setIdFormacion(Long idFormacion) {
        this.idFormacion = idFormacion;
    }

    @Column(name = "id_grupo_personal")
    public Long getIdGrupoPersonal() {
        return this.idGrupoPersonal;
    }

    public void setIdGrupoPersonal(Long idGrupoPersonal) {
        this.idGrupoPersonal = idGrupoPersonal;
    }

    @Column(name = "id_estado_laboral")
    public Long getIdEstadoLaboral() {
        return this.idEstadoLaboral;
    }

    public void setIdEstadoLaboral(Long idEstadoLaboral) {
        this.idEstadoLaboral = idEstadoLaboral;
    }

    @Column(name = "id_area_personal")
    public Long getIdAreaPersonal() {
        return this.idAreaPersonal;
    }

    public void setIdAreaPersonal(Long idAreaPersonal) {
        this.idAreaPersonal = idAreaPersonal;
    }

    @Column(name = "id_division_personal")
    public Long getIdDivisionPersonal() {
        return this.idDivisionPersonal;
    }

    public void setIdDivisionPersonal(Long idDivisionPersonal) {
        this.idDivisionPersonal = idDivisionPersonal;
    }

    @Column(name = "id_division")
    public Long getIdDivision() {
        return this.idDivision;
    }

    public void setIdDivision(Long idDivision) {
        this.idDivision = idDivision;
    }

    @Column(name = "id_subdivision_personal")
    public Long getIdSubdivisionPersonal() {
        return this.idSubdivisionPersonal;
    }

    public void setIdSubdivisionPersonal(Long idSubdivisionPersonal) {
        this.idSubdivisionPersonal = idSubdivisionPersonal;
    }

    @Column(name = "id_sociedad")
    public Long getIdSociedad() {
        return this.idSociedad;
    }

    public void setIdSociedad(Long idSociedad) {
        this.idSociedad = idSociedad;
    }

    @Column(name = "id_unidad_organizativa")
    public Long getIdUnidadOrganizativa() {
        return this.idUnidadOrganizativa;
    }

    public void setIdUnidadOrganizativa(Long idUnidadOrganizativa) {
        this.idUnidadOrganizativa = idUnidadOrganizativa;
    }

    @Column(name = "telefono_oficina")
    public String getTelefonoOficina() {
        return this.telefonoOficina;
    }

    public void setTelefonoOficina(String telefonoOficina) {
        if (telefonoOficina != null)
            telefonoOficina = telefonoOficina.trim();
        this.telefonoOficina = telefonoOficina;
    }

    @Column(name = "id_posicion")
    public Long getIdPosicion() {
        return this.idPosicion;
    }

    public void setIdPosicion(Long idPosicion) {
        this.idPosicion = idPosicion;
    }

    @Column(name = "id_mano_dominante")
    public Long getIdManoDominante() {
        return this.idManoDominante;
    }

    public void setIdManoDominante(Long idManoDominante) {
        this.idManoDominante = idManoDominante;
    }

    @Column(name = "numero_personal")
    public String getNumeroPersonal() {
        return this.numeroPersonal;
    }

    public void setNumeroPersonal(String numeroPersonal) {
        if (numeroPersonal != null)
            numeroPersonal = numeroPersonal.trim();
        this.numeroPersonal = numeroPersonal;
    }

    @Column(name = "asegurado_ivss")
    public Boolean getAseguradoIvss() {
        return this.aseguradoIvss;
    }

    public void setAseguradoIvss(Boolean aseguradoIvss) {
        this.aseguradoIvss = aseguradoIvss;
    }

    @Column(name = "id_tipo_zona_laboral")
    public Long getIdTipoZonaLaboral() {
        return this.idTipoZonaLaboral;
    }

    public void setIdTipoZonaLaboral(Long idTipoZonaLaboral) {
        this.idTipoZonaLaboral = idTipoZonaLaboral;
    }

    @Column(name = "num_hijos")
    public Integer getNumHijos() {
        return this.numHijos;
    }

    public void setNumHijos(Integer numHijos) {
        this.numHijos = numHijos;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "tiempo_servicio", length = 13)
    public Date getTiempoServicio() {
        return this.tiempoServicio;
    }

    public void setTiempoServicio(Date tiempoServicio) {
        this.tiempoServicio = tiempoServicio;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "fecha_nacimiento", length = 13)
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }

    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }

    @Column(name = "id_raza")
    public Long getIdRaza() {
        return this.idRaza;
    }

    public void setIdRaza(Long idRaza) {
        this.idRaza = idRaza;
    }

    @Column(name = "id_etnia")
    public Long getIdEtnia() {
        return this.idEtnia;
    }

    public void setIdEtnia(Long idEtnia) {
        this.idEtnia = idEtnia;
    }

}
