package cu.uci.cesim.hce_back.estadisticas.model.entity.auto.ris;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

// Generated May 21, 2012 5:42:06 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;


/**
 * Procedencia generated by hbm2java
 */
@Entity
@Table(name = "procedencia", schema = "ris")
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "id")
public class Procedencia_RIS implements java.io.Serializable {

    private long idHis;
    private String procedencia;
    private Long cid;
    private Long idApplication;
    private Integer id;
    private Set<Solicitud_RIS> solicituds = new HashSet<Solicitud_RIS>(
            0);

    public Procedencia_RIS() {
    }

    public Procedencia_RIS(long idHis, String procedencia) {
        this.idHis = idHis;
        this.procedencia = procedencia;
    }

    public Procedencia_RIS(long idHis, String procedencia, Long cid,
                           Long idApplication, Integer id,
                           Set<Solicitud_RIS> solicituds) {
        this.idHis = idHis;
        this.procedencia = procedencia;
        this.cid = cid;
        this.idApplication = idApplication;
        this.id = id;
        this.solicituds = solicituds;
    }

    @Id
    @Column(name = "id_his", unique = true, nullable = false)

    public long getIdHis() {
        return this.idHis;
    }

    public void setIdHis(long idHis) {
        this.idHis = idHis;
    }

    @Column(name = "procedencia", nullable = false)

    public String getProcedencia() {
        return this.procedencia;
    }

    public void setProcedencia(String procedencia) {
        if (procedencia != null)
            procedencia = procedencia.trim();
        this.procedencia = procedencia;
    }

    @Column(name = "cid")
    public Long getCid() {
        return this.cid;
    }

    public void setCid(Long cid) {
        this.cid = cid;
    }

    @Column(name = "id_application")
    public Long getIdApplication() {
        return this.idApplication;
    }

    public void setIdApplication(Long idApplication) {
        this.idApplication = idApplication;
    }

    @Column(name = "id")
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "procedencia")
    public Set<Solicitud_RIS> getSolicituds() {
        return this.solicituds;
    }

    public void setSolicituds(Set<Solicitud_RIS> solicituds) {
        this.solicituds = solicituds;
    }

}
