package cu.uci.cesim.hce_back.estadisticas.model.entity.auto.ris;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

// Generated May 21, 2012 5:42:06 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;


/**
 * ServicioInEntidad generated by hbm2java
 */
@Entity
@Table(name = "servicio_in_entidad", schema = "comun", uniqueConstraints = @UniqueConstraint(columnNames = {
        "id_entidad", "id_servicio"}))
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "id")
public class ServicioInEntidad_RIS implements java.io.Serializable {

    private long id;
    private int version;
    private Entidad_RIS entidad;
    private Servicio_RIS servicio;
    private Long cid;
    private Boolean eliminado;
    private Boolean tieneConsultaExterna;
    private Boolean tieneHospitalizacion;
    private Integer idRis;
    private Boolean tieneEmergencia;
    private Set<CitaRis_RIS> citaRises = new HashSet<CitaRis_RIS>(
            0);
    private Set<EquipoEstudioServicio_RIS> equipoEstudioServicios = new HashSet<EquipoEstudioServicio_RIS>(
            0);
    private Set<HistorialConfigServicios_RIS> historialConfigServicioses = new HashSet<HistorialConfigServicios_RIS>(
            0);

    public ServicioInEntidad_RIS() {
    }

    public ServicioInEntidad_RIS(long id,
                                 Entidad_RIS entidad, Servicio_RIS servicio) {
        this.id = id;
        this.entidad = entidad;
        this.servicio = servicio;
    }

    public ServicioInEntidad_RIS(
            long id,
            Entidad_RIS entidad,
            Servicio_RIS servicio,
            Long cid,
            Boolean eliminado,
            Boolean tieneConsultaExterna,
            Boolean tieneHospitalizacion,
            Integer idRis,
            Boolean tieneEmergencia,
            Set<CitaRis_RIS> citaRises,
            Set<EquipoEstudioServicio_RIS> equipoEstudioServicios,
            Set<HistorialConfigServicios_RIS> historialConfigServicioses) {
        this.id = id;
        this.entidad = entidad;
        this.servicio = servicio;
        this.cid = cid;
        this.eliminado = eliminado;
        this.tieneConsultaExterna = tieneConsultaExterna;
        this.tieneHospitalizacion = tieneHospitalizacion;
        this.idRis = idRis;
        this.tieneEmergencia = tieneEmergencia;
        this.citaRises = citaRises;
        this.equipoEstudioServicios = equipoEstudioServicios;
        this.historialConfigServicioses = historialConfigServicioses;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @Version
    @Column(name = "version", nullable = false)

    public int getVersion() {
        return this.version;
    }

    public void setVersion(int version) {
        this.version = version;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_entidad", nullable = false)

    public Entidad_RIS getEntidad() {
        return this.entidad;
    }

    public void setEntidad(Entidad_RIS entidad) {
        this.entidad = entidad;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_servicio", nullable = false)

    public Servicio_RIS getServicio() {
        return this.servicio;
    }

    public void setServicio(Servicio_RIS servicio) {
        this.servicio = servicio;
    }

    @Column(name = "cid")
    public Long getCid() {
        return this.cid;
    }

    public void setCid(Long cid) {
        this.cid = cid;
    }

    @Column(name = "eliminado")
    public Boolean getEliminado() {
        return this.eliminado;
    }

    public void setEliminado(Boolean eliminado) {
        this.eliminado = eliminado;
    }

    @Column(name = "tiene_consulta_externa")
    public Boolean getTieneConsultaExterna() {
        return this.tieneConsultaExterna;
    }

    public void setTieneConsultaExterna(Boolean tieneConsultaExterna) {
        this.tieneConsultaExterna = tieneConsultaExterna;
    }

    @Column(name = "tiene_hospitalizacion")
    public Boolean getTieneHospitalizacion() {
        return this.tieneHospitalizacion;
    }

    public void setTieneHospitalizacion(Boolean tieneHospitalizacion) {
        this.tieneHospitalizacion = tieneHospitalizacion;
    }

    @Column(name = "id_ris")
    public Integer getIdRis() {
        return this.idRis;
    }

    public void setIdRis(Integer idRis) {
        this.idRis = idRis;
    }

    @Column(name = "tiene_emergencia")
    public Boolean getTieneEmergencia() {
        return this.tieneEmergencia;
    }

    public void setTieneEmergencia(Boolean tieneEmergencia) {
        this.tieneEmergencia = tieneEmergencia;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "servicioInEntidad")
    public Set<CitaRis_RIS> getCitaRises() {
        return this.citaRises;
    }

    public void setCitaRises(Set<CitaRis_RIS> citaRises) {
        this.citaRises = citaRises;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "servicioInEntidad")
    public Set<EquipoEstudioServicio_RIS> getEquipoEstudioServicios() {
        return this.equipoEstudioServicios;
    }

    public void setEquipoEstudioServicios(
            Set<EquipoEstudioServicio_RIS> equipoEstudioServicios) {
        this.equipoEstudioServicios = equipoEstudioServicios;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "servicioInEntidad")
    public Set<HistorialConfigServicios_RIS> getHistorialConfigServicioses() {
        return this.historialConfigServicioses;
    }

    public void setHistorialConfigServicioses(
            Set<HistorialConfigServicios_RIS> historialConfigServicioses) {
        this.historialConfigServicioses = historialConfigServicioses;
    }

}
