package cu.uci.cesim.hce_back.estadisticas.model.entity.auto.ris;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

// Generated May 21, 2012 5:42:06 PM by Hibernate Tools 3.4.0.CR1

import org.hibernate.validator.constraints.Length;

import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;


/**
 * Sexo generated by hbm2java
 */
@Entity
@Table(name = "sexo", schema = "nomencladores", uniqueConstraints = {
        @UniqueConstraint(columnNames = "codigo_sap"),
        @UniqueConstraint(columnNames = "abreviatura")})
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "id")
public class Sexo_RIS implements java.io.Serializable {

    private long id;
    private Integer version;
    private String valor;
    private String abreviatura;
    private Boolean eliminado;
    private Long cid;
    private String codigo;
    private String codigoSap;
    private Set<Persona_RIS> personas = new HashSet<Persona_RIS>(
            0);
    private Set<PersonaHist_RIS> personaHists = new HashSet<PersonaHist_RIS>(
            0);

    public Sexo_RIS() {
    }

    public Sexo_RIS(long id, String valor, String abreviatura) {
        this.id = id;
        this.valor = valor;
        this.abreviatura = abreviatura;
    }

    public Sexo_RIS(long id, String valor, String abreviatura,
                    Boolean eliminado, Long cid, String codigo, String codigoSap,
                    Set<Persona_RIS> personas,
                    Set<PersonaHist_RIS> personaHists) {
        this.id = id;
        this.valor = valor;
        this.abreviatura = abreviatura;
        this.eliminado = eliminado;
        this.cid = cid;
        this.codigo = codigo;
        this.codigoSap = codigoSap;
        this.personas = personas;
        this.personaHists = personaHists;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @Version
    @Column(name = "version")
    public Integer getVersion() {
        return this.version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    @Column(name = "valor", nullable = false)

    public String getValor() {
        return this.valor;
    }

    public void setValor(String valor) {
        if (valor != null)
            valor = valor.trim();
        this.valor = valor;
    }

    @Column(name = "abreviatura", unique = true, nullable = false, length = 3)

    @Length(max = 3)
    public String getAbreviatura() {
        return this.abreviatura;
    }

    public void setAbreviatura(String abreviatura) {
        if (abreviatura != null)
            abreviatura = abreviatura.trim();
        this.abreviatura = abreviatura;
    }

    @Column(name = "eliminado")
    public Boolean getEliminado() {
        return this.eliminado;
    }

    public void setEliminado(Boolean eliminado) {
        this.eliminado = eliminado;
    }

    @Column(name = "cid")
    public Long getCid() {
        return this.cid;
    }

    public void setCid(Long cid) {
        this.cid = cid;
    }

    @Column(name = "codigo")
    public String getCodigo() {
        return this.codigo;
    }

    public void setCodigo(String codigo) {
        if (codigo != null)
            codigo = codigo.trim();
        this.codigo = codigo;
    }

    @Column(name = "codigo_sap", unique = true)
    public String getCodigoSap() {
        return this.codigoSap;
    }

    public void setCodigoSap(String codigoSap) {
        if (codigoSap != null)
            codigoSap = codigoSap.trim();
        this.codigoSap = codigoSap;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "sexo")
    public Set<Persona_RIS> getPersonas() {
        return this.personas;
    }

    public void setPersonas(Set<Persona_RIS> personas) {
        this.personas = personas;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "sexo")
    public Set<PersonaHist_RIS> getPersonaHists() {
        return this.personaHists;
    }

    public void setPersonaHists(Set<PersonaHist_RIS> personaHists) {
        this.personaHists = personaHists;
    }

}
