package cu.uci.cesim.hce_back.estadisticas.model.entity.auto.ris;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

// Generated May 21, 2012 5:42:06 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;


/**
 * Status generated by hbm2java
 */
@Entity
@Table(name = "status", schema = "nomencladores", uniqueConstraints = {
        @UniqueConstraint(columnNames = "valor"),
        @UniqueConstraint(columnNames = "codigo")})
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "id")
public class Status_RIS implements java.io.Serializable {

    private long id;
    private Integer version;
    private String codigo;
    private String valor;
    private Boolean eliminado;
    private Long cid;
    private Set<HojaFrontal_RIS> hojaFrontals = new HashSet<HojaFrontal_RIS>(
            0);
    private Set<PersonaHist_RIS> personaHists = new HashSet<PersonaHist_RIS>(
            0);

    public Status_RIS() {
    }

    public Status_RIS(long id, String codigo, String valor) {
        this.id = id;
        this.codigo = codigo;
        this.valor = valor;
    }

    public Status_RIS(long id, String codigo, String valor,
                      Boolean eliminado, Long cid,
                      Set<HojaFrontal_RIS> hojaFrontals,
                      Set<PersonaHist_RIS> personaHists) {
        this.id = id;
        this.codigo = codigo;
        this.valor = valor;
        this.eliminado = eliminado;
        this.cid = cid;
        this.hojaFrontals = hojaFrontals;
        this.personaHists = personaHists;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @Version
    @Column(name = "version")
    public Integer getVersion() {
        return this.version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    @Column(name = "codigo", unique = true, nullable = false)

    public String getCodigo() {
        return this.codigo;
    }

    public void setCodigo(String codigo) {
        if (codigo != null)
            codigo = codigo.trim();
        this.codigo = codigo;
    }

    @Column(name = "valor", unique = true, nullable = false)

    public String getValor() {
        return this.valor;
    }

    public void setValor(String valor) {
        if (valor != null)
            valor = valor.trim();
        this.valor = valor;
    }

    @Column(name = "eliminado")
    public Boolean getEliminado() {
        return this.eliminado;
    }

    public void setEliminado(Boolean eliminado) {
        this.eliminado = eliminado;
    }

    @Column(name = "cid")
    public Long getCid() {
        return this.cid;
    }

    public void setCid(Long cid) {
        this.cid = cid;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "status")
    public Set<HojaFrontal_RIS> getHojaFrontals() {
        return this.hojaFrontals;
    }

    public void setHojaFrontals(Set<HojaFrontal_RIS> hojaFrontals) {
        this.hojaFrontals = hojaFrontals;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "status")
    public Set<PersonaHist_RIS> getPersonaHists() {
        return this.personaHists;
    }

    public void setPersonaHists(Set<PersonaHist_RIS> personaHists) {
        this.personaHists = personaHists;
    }

}
