package cu.uci.cesim.hce_back.estadisticas.model.entity.reportes.auto;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

// Generated 21/09/2012 09:38:30 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.*;

/**
 * ReporteDiagnostico generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "reporte_diagnostico", schema = "epidemiologia")
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "id")
public class ReporteDiagnostico_reportes implements java.io.Serializable {

    private long id;
    private ReporteCategoria_reportes reporteCategoria;
    private String codigo;
    private Boolean eliminado;
    private Long cid;

    public ReporteDiagnostico_reportes() {
    }

    public ReporteDiagnostico_reportes(long id) {
        this.id = id;
    }

    public ReporteDiagnostico_reportes(long id,
                                       ReporteCategoria_reportes reporteCategoria, String codigo,
                                       Boolean eliminado, Long cid) {
        this.id = id;
        this.reporteCategoria = reporteCategoria;
        this.codigo = codigo;
        this.eliminado = eliminado;
        this.cid = cid;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_categoria")
    public ReporteCategoria_reportes getReporteCategoria() {
        return this.reporteCategoria;
    }

    public void setReporteCategoria(ReporteCategoria_reportes reporteCategoria) {
        this.reporteCategoria = reporteCategoria;
    }

    @Column(name = "codigo")
    public String getCodigo() {
        return this.codigo;
    }

    public void setCodigo(String codigo) {
        if (codigo != null)
            codigo = codigo.trim();
        this.codigo = codigo;
    }

    @Column(name = "eliminado")
    public Boolean getEliminado() {
        return this.eliminado;
    }

    public void setEliminado(Boolean eliminado) {
        this.eliminado = eliminado;
    }

    @Column(name = "cid")
    public Long getCid() {
        return this.cid;
    }

    public void setCid(Long cid) {
        this.cid = cid;
    }

}
