package cu.uci.cesim.hce_back.estadisticas.model.entity.reportes.auto;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

// Generated 21/09/2012 09:38:30 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

/**
 * ReporteTipoReporte generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "reporte_tipo_reporte", schema = "epidemiologia")
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "id")
public class ReporteTipoReporte_reportes implements java.io.Serializable {

    private long id;
    private Integer version;
    private String valor;
    private String codigo;
    private Long cid;
    private Boolean eliminado;
    private Set<ReporteCategoriaEnfermedad_reportes> reporteCategoriaEnfermedads = new HashSet<ReporteCategoriaEnfermedad_reportes>(
            0);

    public ReporteTipoReporte_reportes() {
    }

    public ReporteTipoReporte_reportes(long id) {
        this.id = id;
    }

    public ReporteTipoReporte_reportes(long id, String valor, String codigo,
                                       Long cid, Boolean eliminado,
                                       Set<ReporteCategoriaEnfermedad_reportes> reporteCategoriaEnfermedads) {
        this.id = id;
        this.valor = valor;
        this.codigo = codigo;
        this.cid = cid;
        this.eliminado = eliminado;
        this.reporteCategoriaEnfermedads = reporteCategoriaEnfermedads;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @Version
    @Column(name = "version")
    public Integer getVersion() {
        return this.version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    @Column(name = "valor")
    public String getValor() {
        return this.valor;
    }

    public void setValor(String valor) {
        if (valor != null)
            valor = valor.trim();
        this.valor = valor;
    }

    @Column(name = "codigo")
    public String getCodigo() {
        return this.codigo;
    }

    public void setCodigo(String codigo) {
        if (codigo != null)
            codigo = codigo.trim();
        this.codigo = codigo;
    }

    @Column(name = "cid")
    public Long getCid() {
        return this.cid;
    }

    public void setCid(Long cid) {
        this.cid = cid;
    }

    @Column(name = "eliminado")
    public Boolean getEliminado() {
        return this.eliminado;
    }

    public void setEliminado(Boolean eliminado) {
        this.eliminado = eliminado;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "reporteTipoReporte")
    public Set<ReporteCategoriaEnfermedad_reportes> getReporteCategoriaEnfermedads() {
        return this.reporteCategoriaEnfermedads;
    }

    public void setReporteCategoriaEnfermedads(
            Set<ReporteCategoriaEnfermedad_reportes> reporteCategoriaEnfermedads) {
        this.reporteCategoriaEnfermedads = reporteCategoriaEnfermedads;
    }

}
