package cu.uci.cesim.hce_back.estadisticas.model.entity.configuracion;

// Generated 03/03/2012 11:28:05 AM by Hibernate Tools 3.2.4.GA

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;
import org.hibernate.validator.constraints.Length;

import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;


/**
 * TipoCie generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "tipo_cie", schema = "nomencladores", uniqueConstraints = {
        @UniqueConstraint(columnNames = "codigo"),
        @UniqueConstraint(columnNames = "valor")})
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "id")
public class TipoCie_configuracionep implements java.io.Serializable {

    private long id;
    private Integer version;
    private String valor;
    private String codigo;
    private Boolean eliminado;
    private Long cid;
    private Set<Cie_configuracionep> cies = new HashSet<Cie_configuracionep>(0);

    public TipoCie_configuracionep() {
    }

    public TipoCie_configuracionep(long id, String valor, String codigo) {
        this.id = id;
        this.valor = valor;
        this.codigo = codigo;
    }

    public TipoCie_configuracionep(long id, String valor, String codigo,
                                   Boolean eliminado, Long cid, Set<Cie_configuracionep> cies) {
        this.id = id;
        this.valor = valor;
        this.codigo = codigo;
        this.eliminado = eliminado;
        this.cid = cid;
        this.cies = cies;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @Version
    @Column(name = "version")
    public Integer getVersion() {
        return this.version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    @Column(name = "valor", unique = true, nullable = false, length = 25)

    @Length(max = 25)
    public String getValor() {
        return this.valor;
    }

    public void setValor(String valor) {
        if (valor != null)
            valor = valor.trim();
        this.valor = valor;
    }

    @Column(name = "codigo", unique = true, nullable = false)

    public String getCodigo() {
        return this.codigo;
    }

    public void setCodigo(String codigo) {
        if (codigo != null)
            codigo = codigo.trim();
        this.codigo = codigo;
    }

    @Column(name = "eliminado")
    public Boolean getEliminado() {
        return this.eliminado;
    }

    public void setEliminado(Boolean eliminado) {
        this.eliminado = eliminado;
    }

    @Column(name = "cid")
    public Long getCid() {
        return this.cid;
    }

    public void setCid(Long cid) {
        this.cid = cid;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoCie")
    public Set<Cie_configuracionep> getCies() {
        return this.cies;
    }

    public void setCies(Set<Cie_configuracionep> cies) {
        this.cies = cies;
    }

}
