package cu.uci.cesim.hce_back.estadisticas.model.entity.auto;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

import javax.persistence.*;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

// Generated Apr 18, 2012 10:46:48 AM by Hibernate Tools 3.4.0.CR1

/**
 * CertificadoDefuncion generated by hbm2java
 */
@Entity
@Table(name = "certificado_defuncion", schema = "hc_local")
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "id")
public class CertificadoDefuncion_estadisticas implements java.io.Serializable {

    private long id;
    private Integer version;
    private SolicitudAutopsia_estadisticas solicitudAutopsia;
    private Direccion_estadisticas direccionByIdDireccion;
    private Funcionalidad_estadisticas funcionalidad;
    private TipoEstablecimientoSalud_estadisticas tipoEstablecimientoSalud;
    private HojaFrontal_estadisticas hojaFrontal;
    private Direccion_estadisticas direccionByIdLugarMuerte;
    private String valor;
    private Boolean eliminado;
    private Long cid;
    private Long idMuerteViolenta;
    private Long idRegistroCivil;
    private Long idOtrosDatosMadre;
    private Long idOtrosDatosFallecido;
    private Date fechaDefuncion;
    private Date horaDefuncion;
    private Boolean tuvoAistenciaMedica;
    private Long idSitioMuerte;
    private String nombreEstablecimiento;
    private Integer numeroTomoPartidaNacimiento;
    private Integer numeroFolioPartidaNacimiento;
    private Integer numeroLibroPartidaNacimiento;
    private Integer numeroActaPartidaNacimiento;
    private Long idUbicacionPartida;
    private String causaDirectaMuerte;
    private String causaAntecedenteMuerte;
    private String causaMaternaDirecta;
    private String causaMaternaInderecta;
    private String otrosEstadosPatologicos;
    private Integer codigoEnfermedad;
    private Long idFormaConfirmacionDiagnostico;
    private Boolean autopsiaEnProceso;
    private String especificacionDeOtro;
    private Long idMedicoFirmante;
    private String otroMedicoFirmante;
    private Integer tiempoEnfermo;
    private Integer numeroCertificado;
    private Date fechaAnulacion;
    private String motivoAnulacion;
    private Long idModelo;
    private Boolean confirmacionMuerteClinica;
    private Boolean confirmacionMuerteInvestigacion;
    private Boolean confirmacionMuerteOperacion;
    private Boolean confirmacionMuerteBiopsia;
    private Boolean confirmacionNecropsia;
    private String causaMuerteA;
    private String causaMuerteB;
    private String causaMuerteC;
    private String causaMuerteD;
    private String causaMuerteOtras;
    private String motivoSolAutopsia;
    private Boolean causasReordenadas;
    private Set<Egreso_estadisticas> egresos = new HashSet<Egreso_estadisticas>(
            0);
    private Set<EgresoEmergencia_estadisticas> egresoEmergencias = new HashSet<EgresoEmergencia_estadisticas>(
            0);
    private Set<CausasMuerte_estadisticas> causasMuertes = new HashSet<CausasMuerte_estadisticas>(
            0);
    private Set<Fallecimiento_estadisticas> fallecimientos = new HashSet<Fallecimiento_estadisticas>(
            0);

    public CertificadoDefuncion_estadisticas() {
    }

    public CertificadoDefuncion_estadisticas(long id) {
        this.id = id;
    }

    public CertificadoDefuncion_estadisticas(long id,
                                             SolicitudAutopsia_estadisticas solicitudAutopsia,
                                             Direccion_estadisticas direccionByIdDireccion,
                                             Funcionalidad_estadisticas funcionalidad,
                                             TipoEstablecimientoSalud_estadisticas tipoEstablecimientoSalud,
                                             HojaFrontal_estadisticas hojaFrontal,
                                             Direccion_estadisticas direccionByIdLugarMuerte, String valor,
                                             Boolean eliminado, Long cid, Long idMuerteViolenta,
                                             Long idRegistroCivil, Long idOtrosDatosMadre,
                                             Long idOtrosDatosFallecido, Date fechaDefuncion,
                                             Date horaDefuncion, Boolean tuvoAistenciaMedica,
                                             Long idSitioMuerte, String nombreEstablecimiento,
                                             Integer numeroTomoPartidaNacimiento,
                                             Integer numeroFolioPartidaNacimiento,
                                             Integer numeroLibroPartidaNacimiento,
                                             Integer numeroActaPartidaNacimiento, Long idUbicacionPartida,
                                             String causaDirectaMuerte, String causaAntecedenteMuerte,
                                             String causaMaternaDirecta, String causaMaternaInderecta,
                                             String otrosEstadosPatologicos, Integer codigoEnfermedad,
                                             Long idFormaConfirmacionDiagnostico, Boolean autopsiaEnProceso,
                                             String especificacionDeOtro, Long idMedicoFirmante,
                                             String otroMedicoFirmante, Integer tiempoEnfermo,
                                             Integer numeroCertificado, Date fechaAnulacion,
                                             String motivoAnulacion, Long idModelo,
                                             Boolean confirmacionMuerteClinica,
                                             Boolean confirmacionMuerteInvestigacion,
                                             Boolean confirmacionMuerteOperacion,
                                             Boolean confirmacionMuerteBiopsia, Boolean confirmacionNecropsia,
                                             String causaMuerteA, String causaMuerteB, String causaMuerteC,
                                             String causaMuerteD, String causaMuerteOtras,
                                             String motivoSolAutopsia, Boolean causasReordenadas,
                                             Set<Egreso_estadisticas> egresos,
                                             Set<EgresoEmergencia_estadisticas> egresoEmergencias,
                                             Set<CausasMuerte_estadisticas> causasMuertes,
                                             Set<Fallecimiento_estadisticas> fallecimientos) {
        this.id = id;
        this.solicitudAutopsia = solicitudAutopsia;
        this.direccionByIdDireccion = direccionByIdDireccion;
        this.funcionalidad = funcionalidad;
        this.tipoEstablecimientoSalud = tipoEstablecimientoSalud;
        this.hojaFrontal = hojaFrontal;
        this.direccionByIdLugarMuerte = direccionByIdLugarMuerte;
        this.valor = valor;
        this.eliminado = eliminado;
        this.cid = cid;
        this.idMuerteViolenta = idMuerteViolenta;
        this.idRegistroCivil = idRegistroCivil;
        this.idOtrosDatosMadre = idOtrosDatosMadre;
        this.idOtrosDatosFallecido = idOtrosDatosFallecido;
        this.fechaDefuncion = fechaDefuncion;
        this.horaDefuncion = horaDefuncion;
        this.tuvoAistenciaMedica = tuvoAistenciaMedica;
        this.idSitioMuerte = idSitioMuerte;
        this.nombreEstablecimiento = nombreEstablecimiento;
        this.numeroTomoPartidaNacimiento = numeroTomoPartidaNacimiento;
        this.numeroFolioPartidaNacimiento = numeroFolioPartidaNacimiento;
        this.numeroLibroPartidaNacimiento = numeroLibroPartidaNacimiento;
        this.numeroActaPartidaNacimiento = numeroActaPartidaNacimiento;
        this.idUbicacionPartida = idUbicacionPartida;
        this.causaDirectaMuerte = causaDirectaMuerte;
        this.causaAntecedenteMuerte = causaAntecedenteMuerte;
        this.causaMaternaDirecta = causaMaternaDirecta;
        this.causaMaternaInderecta = causaMaternaInderecta;
        this.otrosEstadosPatologicos = otrosEstadosPatologicos;
        this.codigoEnfermedad = codigoEnfermedad;
        this.idFormaConfirmacionDiagnostico = idFormaConfirmacionDiagnostico;
        this.autopsiaEnProceso = autopsiaEnProceso;
        this.especificacionDeOtro = especificacionDeOtro;
        this.idMedicoFirmante = idMedicoFirmante;
        this.otroMedicoFirmante = otroMedicoFirmante;
        this.tiempoEnfermo = tiempoEnfermo;
        this.numeroCertificado = numeroCertificado;
        this.fechaAnulacion = fechaAnulacion;
        this.motivoAnulacion = motivoAnulacion;
        this.idModelo = idModelo;
        this.confirmacionMuerteClinica = confirmacionMuerteClinica;
        this.confirmacionMuerteInvestigacion = confirmacionMuerteInvestigacion;
        this.confirmacionMuerteOperacion = confirmacionMuerteOperacion;
        this.confirmacionMuerteBiopsia = confirmacionMuerteBiopsia;
        this.confirmacionNecropsia = confirmacionNecropsia;
        this.causaMuerteA = causaMuerteA;
        this.causaMuerteB = causaMuerteB;
        this.causaMuerteC = causaMuerteC;
        this.causaMuerteD = causaMuerteD;
        this.causaMuerteOtras = causaMuerteOtras;
        this.motivoSolAutopsia = motivoSolAutopsia;
        this.causasReordenadas = causasReordenadas;
        this.egresos = egresos;
        this.egresoEmergencias = egresoEmergencias;
        this.causasMuertes = causasMuertes;
        this.fallecimientos = fallecimientos;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @Version
    @Column(name = "version")
    public Integer getVersion() {
        return this.version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_solicitud_autopsia")
    public SolicitudAutopsia_estadisticas getSolicitudAutopsia() {
        return this.solicitudAutopsia;
    }

    public void setSolicitudAutopsia(
            SolicitudAutopsia_estadisticas solicitudAutopsia) {
        this.solicitudAutopsia = solicitudAutopsia;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_direccion")
    public Direccion_estadisticas getDireccionByIdDireccion() {
        return this.direccionByIdDireccion;
    }

    public void setDireccionByIdDireccion(
            Direccion_estadisticas direccionByIdDireccion) {
        this.direccionByIdDireccion = direccionByIdDireccion;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_funcionalidad")
    public Funcionalidad_estadisticas getFuncionalidad() {
        return this.funcionalidad;
    }

    public void setFuncionalidad(Funcionalidad_estadisticas funcionalidad) {
        this.funcionalidad = funcionalidad;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "tipo_establecimiento_salud")
    public TipoEstablecimientoSalud_estadisticas getTipoEstablecimientoSalud() {
        return this.tipoEstablecimientoSalud;
    }

    public void setTipoEstablecimientoSalud(
            TipoEstablecimientoSalud_estadisticas tipoEstablecimientoSalud) {
        this.tipoEstablecimientoSalud = tipoEstablecimientoSalud;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_hoja_frontal")
    public HojaFrontal_estadisticas getHojaFrontal() {
        return this.hojaFrontal;
    }

    public void setHojaFrontal(HojaFrontal_estadisticas hojaFrontal) {
        this.hojaFrontal = hojaFrontal;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_lugar_muerte")
    public Direccion_estadisticas getDireccionByIdLugarMuerte() {
        return this.direccionByIdLugarMuerte;
    }

    public void setDireccionByIdLugarMuerte(
            Direccion_estadisticas direccionByIdLugarMuerte) {
        this.direccionByIdLugarMuerte = direccionByIdLugarMuerte;
    }

    @Column(name = "valor")
    public String getValor() {
        return this.valor;
    }

    public void setValor(String valor) {
        if (valor != null)
            valor = valor.trim();
        this.valor = valor;
    }

    @Column(name = "eliminado")
    public Boolean getEliminado() {
        return this.eliminado;
    }

    public void setEliminado(Boolean eliminado) {
        this.eliminado = eliminado;
    }

    @Column(name = "cid")
    public Long getCid() {
        return this.cid;
    }

    public void setCid(Long cid) {
        this.cid = cid;
    }

    @Column(name = "id_muerte_violenta")
    public Long getIdMuerteViolenta() {
        return this.idMuerteViolenta;
    }

    public void setIdMuerteViolenta(Long idMuerteViolenta) {
        this.idMuerteViolenta = idMuerteViolenta;
    }

    @Column(name = "id_registro_civil")
    public Long getIdRegistroCivil() {
        return this.idRegistroCivil;
    }

    public void setIdRegistroCivil(Long idRegistroCivil) {
        this.idRegistroCivil = idRegistroCivil;
    }

    @Column(name = "id_otros_datos_madre")
    public Long getIdOtrosDatosMadre() {
        return this.idOtrosDatosMadre;
    }

    public void setIdOtrosDatosMadre(Long idOtrosDatosMadre) {
        this.idOtrosDatosMadre = idOtrosDatosMadre;
    }

    @Column(name = "id_otros_datos_fallecido")
    public Long getIdOtrosDatosFallecido() {
        return this.idOtrosDatosFallecido;
    }

    public void setIdOtrosDatosFallecido(Long idOtrosDatosFallecido) {
        this.idOtrosDatosFallecido = idOtrosDatosFallecido;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "fecha_defuncion", length = 13)
    public Date getFechaDefuncion() {
        return this.fechaDefuncion;
    }

    public void setFechaDefuncion(Date fechaDefuncion) {
        this.fechaDefuncion = fechaDefuncion;
    }

    @Temporal(TemporalType.TIME)
    @Column(name = "hora_defuncion", length = 8)
    public Date getHoraDefuncion() {
        return this.horaDefuncion;
    }

    public void setHoraDefuncion(Date horaDefuncion) {
        this.horaDefuncion = horaDefuncion;
    }

    @Column(name = "tuvo_aistencia_medica")
    public Boolean getTuvoAistenciaMedica() {
        return this.tuvoAistenciaMedica;
    }

    public void setTuvoAistenciaMedica(Boolean tuvoAistenciaMedica) {
        this.tuvoAistenciaMedica = tuvoAistenciaMedica;
    }

    @Column(name = "id_sitio_muerte")
    public Long getIdSitioMuerte() {
        return this.idSitioMuerte;
    }

    public void setIdSitioMuerte(Long idSitioMuerte) {
        this.idSitioMuerte = idSitioMuerte;
    }

    @Column(name = "nombre_establecimiento")
    public String getNombreEstablecimiento() {
        return this.nombreEstablecimiento;
    }

    public void setNombreEstablecimiento(String nombreEstablecimiento) {
        if (nombreEstablecimiento != null)
            nombreEstablecimiento = nombreEstablecimiento.trim();
        this.nombreEstablecimiento = nombreEstablecimiento;
    }

    @Column(name = "numero_tomo_partida_nacimiento")
    public Integer getNumeroTomoPartidaNacimiento() {
        return this.numeroTomoPartidaNacimiento;
    }

    public void setNumeroTomoPartidaNacimiento(
            Integer numeroTomoPartidaNacimiento) {
        this.numeroTomoPartidaNacimiento = numeroTomoPartidaNacimiento;
    }

    @Column(name = "numero_folio_partida_nacimiento")
    public Integer getNumeroFolioPartidaNacimiento() {
        return this.numeroFolioPartidaNacimiento;
    }

    public void setNumeroFolioPartidaNacimiento(
            Integer numeroFolioPartidaNacimiento) {
        this.numeroFolioPartidaNacimiento = numeroFolioPartidaNacimiento;
    }

    @Column(name = "numero_libro_partida_nacimiento")
    public Integer getNumeroLibroPartidaNacimiento() {
        return this.numeroLibroPartidaNacimiento;
    }

    public void setNumeroLibroPartidaNacimiento(
            Integer numeroLibroPartidaNacimiento) {
        this.numeroLibroPartidaNacimiento = numeroLibroPartidaNacimiento;
    }

    @Column(name = "numero_acta_partida_nacimiento")
    public Integer getNumeroActaPartidaNacimiento() {
        return this.numeroActaPartidaNacimiento;
    }

    public void setNumeroActaPartidaNacimiento(
            Integer numeroActaPartidaNacimiento) {
        this.numeroActaPartidaNacimiento = numeroActaPartidaNacimiento;
    }

    @Column(name = "id_ubicacion_partida")
    public Long getIdUbicacionPartida() {
        return this.idUbicacionPartida;
    }

    public void setIdUbicacionPartida(Long idUbicacionPartida) {
        this.idUbicacionPartida = idUbicacionPartida;
    }

    @Column(name = "causa_directa_muerte")
    public String getCausaDirectaMuerte() {
        return this.causaDirectaMuerte;
    }

    public void setCausaDirectaMuerte(String causaDirectaMuerte) {
        if (causaDirectaMuerte != null)
            causaDirectaMuerte = causaDirectaMuerte.trim();
        this.causaDirectaMuerte = causaDirectaMuerte;
    }

    @Column(name = "causa_antecedente_muerte")
    public String getCausaAntecedenteMuerte() {
        return this.causaAntecedenteMuerte;
    }

    public void setCausaAntecedenteMuerte(String causaAntecedenteMuerte) {
        if (causaAntecedenteMuerte != null)
            causaAntecedenteMuerte = causaAntecedenteMuerte.trim();
        this.causaAntecedenteMuerte = causaAntecedenteMuerte;
    }

    @Column(name = "causa_materna_directa")
    public String getCausaMaternaDirecta() {
        return this.causaMaternaDirecta;
    }

    public void setCausaMaternaDirecta(String causaMaternaDirecta) {
        if (causaMaternaDirecta != null)
            causaMaternaDirecta = causaMaternaDirecta.trim();
        this.causaMaternaDirecta = causaMaternaDirecta;
    }

    @Column(name = "causa_materna_inderecta")
    public String getCausaMaternaInderecta() {
        return this.causaMaternaInderecta;
    }

    public void setCausaMaternaInderecta(String causaMaternaInderecta) {
        if (causaMaternaInderecta != null)
            causaMaternaInderecta = causaMaternaInderecta.trim();
        this.causaMaternaInderecta = causaMaternaInderecta;
    }

    @Column(name = "otros_estados_patologicos")
    public String getOtrosEstadosPatologicos() {
        return this.otrosEstadosPatologicos;
    }

    public void setOtrosEstadosPatologicos(String otrosEstadosPatologicos) {
        if (otrosEstadosPatologicos != null)
            otrosEstadosPatologicos = otrosEstadosPatologicos.trim();
        this.otrosEstadosPatologicos = otrosEstadosPatologicos;
    }

    @Column(name = "codigo_enfermedad")
    public Integer getCodigoEnfermedad() {
        return this.codigoEnfermedad;
    }

    public void setCodigoEnfermedad(Integer codigoEnfermedad) {
        this.codigoEnfermedad = codigoEnfermedad;
    }

    @Column(name = "id_forma_confirmacion_diagnostico")
    public Long getIdFormaConfirmacionDiagnostico() {
        return this.idFormaConfirmacionDiagnostico;
    }

    public void setIdFormaConfirmacionDiagnostico(
            Long idFormaConfirmacionDiagnostico) {
        this.idFormaConfirmacionDiagnostico = idFormaConfirmacionDiagnostico;
    }

    @Column(name = "autopsia_en_proceso")
    public Boolean getAutopsiaEnProceso() {
        return this.autopsiaEnProceso;
    }

    public void setAutopsiaEnProceso(Boolean autopsiaEnProceso) {
        this.autopsiaEnProceso = autopsiaEnProceso;
    }

    @Column(name = "especificacion_de_otro")
    public String getEspecificacionDeOtro() {
        return this.especificacionDeOtro;
    }

    public void setEspecificacionDeOtro(String especificacionDeOtro) {
        if (especificacionDeOtro != null)
            especificacionDeOtro = especificacionDeOtro.trim();
        this.especificacionDeOtro = especificacionDeOtro;
    }

    @Column(name = "id_medico_firmante")
    public Long getIdMedicoFirmante() {
        return this.idMedicoFirmante;
    }

    public void setIdMedicoFirmante(Long idMedicoFirmante) {
        this.idMedicoFirmante = idMedicoFirmante;
    }

    @Column(name = "otro_medico_firmante")
    public String getOtroMedicoFirmante() {
        return this.otroMedicoFirmante;
    }

    public void setOtroMedicoFirmante(String otroMedicoFirmante) {
        if (otroMedicoFirmante != null)
            otroMedicoFirmante = otroMedicoFirmante.trim();
        this.otroMedicoFirmante = otroMedicoFirmante;
    }

    @Column(name = "tiempo_enfermo")
    public Integer getTiempoEnfermo() {
        return this.tiempoEnfermo;
    }

    public void setTiempoEnfermo(Integer tiempoEnfermo) {
        this.tiempoEnfermo = tiempoEnfermo;
    }

    @Column(name = "numero_certificado")
    public Integer getNumeroCertificado() {
        return this.numeroCertificado;
    }

    public void setNumeroCertificado(Integer numeroCertificado) {
        this.numeroCertificado = numeroCertificado;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "fecha_anulacion", length = 13)
    public Date getFechaAnulacion() {
        return this.fechaAnulacion;
    }

    public void setFechaAnulacion(Date fechaAnulacion) {
        this.fechaAnulacion = fechaAnulacion;
    }

    @Column(name = "motivo_anulacion")
    public String getMotivoAnulacion() {
        return this.motivoAnulacion;
    }

    public void setMotivoAnulacion(String motivoAnulacion) {
        if (motivoAnulacion != null)
            motivoAnulacion = motivoAnulacion.trim();
        this.motivoAnulacion = motivoAnulacion;
    }

    @Column(name = "id_modelo")
    public Long getIdModelo() {
        return this.idModelo;
    }

    public void setIdModelo(Long idModelo) {
        this.idModelo = idModelo;
    }

    @Column(name = "confirmacion_muerte_clinica")
    public Boolean getConfirmacionMuerteClinica() {
        return this.confirmacionMuerteClinica;
    }

    public void setConfirmacionMuerteClinica(Boolean confirmacionMuerteClinica) {
        this.confirmacionMuerteClinica = confirmacionMuerteClinica;
    }

    @Column(name = "confirmacion_muerte_investigacion")
    public Boolean getConfirmacionMuerteInvestigacion() {
        return this.confirmacionMuerteInvestigacion;
    }

    public void setConfirmacionMuerteInvestigacion(
            Boolean confirmacionMuerteInvestigacion) {
        this.confirmacionMuerteInvestigacion = confirmacionMuerteInvestigacion;
    }

    @Column(name = "confirmacion_muerte_operacion")
    public Boolean getConfirmacionMuerteOperacion() {
        return this.confirmacionMuerteOperacion;
    }

    public void setConfirmacionMuerteOperacion(
            Boolean confirmacionMuerteOperacion) {
        this.confirmacionMuerteOperacion = confirmacionMuerteOperacion;
    }

    @Column(name = "confirmacion_muerte_biopsia")
    public Boolean getConfirmacionMuerteBiopsia() {
        return this.confirmacionMuerteBiopsia;
    }

    public void setConfirmacionMuerteBiopsia(Boolean confirmacionMuerteBiopsia) {
        this.confirmacionMuerteBiopsia = confirmacionMuerteBiopsia;
    }

    @Column(name = "confirmacion_necropsia")
    public Boolean getConfirmacionNecropsia() {
        return this.confirmacionNecropsia;
    }

    public void setConfirmacionNecropsia(Boolean confirmacionNecropsia) {
        this.confirmacionNecropsia = confirmacionNecropsia;
    }

    @Column(name = "causa_muerte_a")
    public String getCausaMuerteA() {
        return this.causaMuerteA;
    }

    public void setCausaMuerteA(String causaMuerteA) {
        if (causaMuerteA != null)
            causaMuerteA = causaMuerteA.trim();
        this.causaMuerteA = causaMuerteA;
    }

    @Column(name = "causa_muerte_b")
    public String getCausaMuerteB() {
        return this.causaMuerteB;
    }

    public void setCausaMuerteB(String causaMuerteB) {
        if (causaMuerteB != null)
            causaMuerteB = causaMuerteB.trim();
        this.causaMuerteB = causaMuerteB;
    }

    @Column(name = "causa_muerte_c")
    public String getCausaMuerteC() {
        return this.causaMuerteC;
    }

    public void setCausaMuerteC(String causaMuerteC) {
        if (causaMuerteC != null)
            causaMuerteC = causaMuerteC.trim();
        this.causaMuerteC = causaMuerteC;
    }

    @Column(name = "causa_muerte_d")
    public String getCausaMuerteD() {
        return this.causaMuerteD;
    }

    public void setCausaMuerteD(String causaMuerteD) {
        if (causaMuerteD != null)
            causaMuerteD = causaMuerteD.trim();
        this.causaMuerteD = causaMuerteD;
    }

    @Column(name = "causa_muerte_otras")
    public String getCausaMuerteOtras() {
        return this.causaMuerteOtras;
    }

    public void setCausaMuerteOtras(String causaMuerteOtras) {
        if (causaMuerteOtras != null)
            causaMuerteOtras = causaMuerteOtras.trim();
        this.causaMuerteOtras = causaMuerteOtras;
    }

    @Column(name = "motivo_sol_autopsia")
    public String getMotivoSolAutopsia() {
        return this.motivoSolAutopsia;
    }

    public void setMotivoSolAutopsia(String motivoSolAutopsia) {
        if (motivoSolAutopsia != null)
            motivoSolAutopsia = motivoSolAutopsia.trim();
        this.motivoSolAutopsia = motivoSolAutopsia;
    }

    @Column(name = "causas_reordenadas")
    public Boolean getCausasReordenadas() {
        return this.causasReordenadas;
    }

    public void setCausasReordenadas(Boolean causasReordenadas) {
        this.causasReordenadas = causasReordenadas;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "certificadoDefuncion")
    public Set<Egreso_estadisticas> getEgresos() {
        return this.egresos;
    }

    public void setEgresos(Set<Egreso_estadisticas> egresos) {
        this.egresos = egresos;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "certificadoDefuncion")
    public Set<EgresoEmergencia_estadisticas> getEgresoEmergencias() {
        return this.egresoEmergencias;
    }

    public void setEgresoEmergencias(
            Set<EgresoEmergencia_estadisticas> egresoEmergencias) {
        this.egresoEmergencias = egresoEmergencias;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "certificadoDefuncion")
    public Set<CausasMuerte_estadisticas> getCausasMuertes() {
        return this.causasMuertes;
    }

    public void setCausasMuertes(Set<CausasMuerte_estadisticas> causasMuertes) {
        this.causasMuertes = causasMuertes;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "certificadoDefuncion")
    public Set<Fallecimiento_estadisticas> getFallecimientos() {
        return this.fallecimientos;
    }

    public void setFallecimientos(Set<Fallecimiento_estadisticas> fallecimientos) {
        this.fallecimientos = fallecimientos;
    }

}
