package cu.uci.cesim.hce_back.estadisticas.model.entity.auto;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;
import org.hibernate.validator.constraints.Length;

import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

// Generated Apr 18, 2012 10:46:48 AM by Hibernate Tools 3.4.0.CR1


/**
 * Cie generated by hbm2java
 */
@Entity
@Table(name = "cie", schema = "estandares")
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "id")
public class Cie_estadisticas implements java.io.Serializable {

    private long id;
    private Integer version;
    private Cie_estadisticas cie;
    private String codigo;
    private String descripcion;
    private String incluye;
    private String excluye;
    private String observaciones;
    private Long idTipoCie;
    private Boolean eliminado;
    private Long cid;
    private Set<CausasMuerte_estadisticas> causasMuertes = new HashSet<CausasMuerte_estadisticas>(
            0);
    private Set<Cie_estadisticas> cies = new HashSet<Cie_estadisticas>(0);

    public Cie_estadisticas() {
    }

    public Cie_estadisticas(long id, String codigo, String descripcion) {
        this.id = id;
        this.codigo = codigo;
        this.descripcion = descripcion;
    }

    public Cie_estadisticas(long id, Cie_estadisticas cie, String codigo,
                            String descripcion, String incluye, String excluye,
                            String observaciones, Long idTipoCie, Boolean eliminado, Long cid,
                            Set<CausasMuerte_estadisticas> causasMuertes,
                            Set<Cie_estadisticas> cies) {
        this.id = id;
        this.cie = cie;
        this.codigo = codigo;
        this.descripcion = descripcion;
        this.incluye = incluye;
        this.excluye = excluye;
        this.observaciones = observaciones;
        this.idTipoCie = idTipoCie;
        this.eliminado = eliminado;
        this.cid = cid;
        this.causasMuertes = causasMuertes;
        this.cies = cies;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @Version
    @Column(name = "version")
    public Integer getVersion() {
        return this.version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_cie_padre")
    public Cie_estadisticas getCie() {
        return this.cie;
    }

    public void setCie(Cie_estadisticas cie) {
        this.cie = cie;
    }

    @Column(name = "codigo", nullable = false, length = 10)

    @Length(max = 10)
    public String getCodigo() {
        return this.codigo;
    }

    public void setCodigo(String codigo) {
        if (codigo != null)
            codigo = codigo.trim();
        this.codigo = codigo;
    }

    @Column(name = "descripcion", nullable = false)

    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        if (descripcion != null)
            descripcion = descripcion.trim();
        this.descripcion = descripcion;
    }

    @Column(name = "incluye")
    public String getIncluye() {
        return this.incluye;
    }

    public void setIncluye(String incluye) {
        if (incluye != null)
            incluye = incluye.trim();
        this.incluye = incluye;
    }

    @Column(name = "excluye")
    public String getExcluye() {
        return this.excluye;
    }

    public void setExcluye(String excluye) {
        if (excluye != null)
            excluye = excluye.trim();
        this.excluye = excluye;
    }

    @Column(name = "observaciones")
    public String getObservaciones() {
        return this.observaciones;
    }

    public void setObservaciones(String observaciones) {
        if (observaciones != null)
            observaciones = observaciones.trim();
        this.observaciones = observaciones;
    }

    @Column(name = "id_tipo_cie")
    public Long getIdTipoCie() {
        return this.idTipoCie;
    }

    public void setIdTipoCie(Long idTipoCie) {
        this.idTipoCie = idTipoCie;
    }

    @Column(name = "eliminado")
    public Boolean getEliminado() {
        return this.eliminado;
    }

    public void setEliminado(Boolean eliminado) {
        this.eliminado = eliminado;
    }

    @Column(name = "cid")
    public Long getCid() {
        return this.cid;
    }

    public void setCid(Long cid) {
        this.cid = cid;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "cie")
    public Set<CausasMuerte_estadisticas> getCausasMuertes() {
        return this.causasMuertes;
    }

    public void setCausasMuertes(Set<CausasMuerte_estadisticas> causasMuertes) {
        this.causasMuertes = causasMuertes;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "cie")
    public Set<Cie_estadisticas> getCies() {
        return this.cies;
    }

    public void setCies(Set<Cie_estadisticas> cies) {
        this.cies = cies;
    }

}
