package cu.uci.cesim.hce_back.estadisticas.model.entity.auto;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

// Generated Apr 18, 2012 10:46:48 AM by Hibernate Tools 3.4.0.CR1


/**
 * CipGrupo generated by hbm2java
 */
@Entity
@Table(name = "cip_grupo", schema = "estandares")
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "id")
public class CipGrupo_estadisticas implements java.io.Serializable {

    private long id;
    private Integer version;
    private CipCapitulo_estadisticas cipCapitulo;
    private String codigo;
    private String valor;
    private Boolean eliminado;
    private Long cid;
    private Set<CipCategoria_estadisticas> cipCategorias = new HashSet<CipCategoria_estadisticas>(
            0);

    public CipGrupo_estadisticas() {
    }

    public CipGrupo_estadisticas(long id, CipCapitulo_estadisticas cipCapitulo,
                                 String codigo, String valor) {
        this.id = id;
        this.cipCapitulo = cipCapitulo;
        this.codigo = codigo;
        this.valor = valor;
    }

    public CipGrupo_estadisticas(long id, CipCapitulo_estadisticas cipCapitulo,
                                 String codigo, String valor, Boolean eliminado, Long cid,
                                 Set<CipCategoria_estadisticas> cipCategorias) {
        this.id = id;
        this.cipCapitulo = cipCapitulo;
        this.codigo = codigo;
        this.valor = valor;
        this.eliminado = eliminado;
        this.cid = cid;
        this.cipCategorias = cipCategorias;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @Version
    @Column(name = "version")
    public Integer getVersion() {
        return this.version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_capitulo", nullable = false)

    public CipCapitulo_estadisticas getCipCapitulo() {
        return this.cipCapitulo;
    }

    public void setCipCapitulo(CipCapitulo_estadisticas cipCapitulo) {
        this.cipCapitulo = cipCapitulo;
    }

    @Column(name = "codigo", nullable = false)

    public String getCodigo() {
        return this.codigo;
    }

    public void setCodigo(String codigo) {
        if (codigo != null)
            codigo = codigo.trim();
        this.codigo = codigo;
    }

    @Column(name = "valor", nullable = false)

    public String getValor() {
        return this.valor;
    }

    public void setValor(String valor) {
        if (valor != null)
            valor = valor.trim();
        this.valor = valor;
    }

    @Column(name = "eliminado")
    public Boolean getEliminado() {
        return this.eliminado;
    }

    public void setEliminado(Boolean eliminado) {
        this.eliminado = eliminado;
    }

    @Column(name = "cid")
    public Long getCid() {
        return this.cid;
    }

    public void setCid(Long cid) {
        this.cid = cid;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "cipGrupo")
    public Set<CipCategoria_estadisticas> getCipCategorias() {
        return this.cipCategorias;
    }

    public void setCipCategorias(Set<CipCategoria_estadisticas> cipCategorias) {
        this.cipCategorias = cipCategorias;
    }

}
