package cu.uci.cesim.hce_back.estadisticas.model.entity.auto;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

import javax.persistence.*;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

// Generated 21/09/2012 09:38:30 AM by Hibernate Tools 3.4.0.CR1

/**
 * DatosLaborales generated by hbm2java
 */
@Entity
@Table(name = "datos_laborales", schema = "hc_local")
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "id")
public class DatosLaborales_estadisticas implements java.io.Serializable {

    private long id;
    private Integer version;
    private Division_estadisticas division;
    private Long idFormacion;
    private GrupoPersonal_estadisticas grupoPersonal;
    private Long idEstadoLaboral;
    private Long idAreaPersonal;
    private Long idDivisionPersonal;
    private SubdivisionPersonal_estadisticas subdivisionPersonal;
    private Long idSociedad;
    private Long idUnidadOrganizativa;
    private String telefonoOficina;
    private Long idPosicion;
    private Long idManoDominante;
    private String numeroPersonal;
    private Boolean aseguradoIvss;
    private Long idTipoZonaLaboral;
    private Integer numHijos;
    private Long cid;
    private Date tiempoServicio;
    private Boolean eliminado;
    private Set<Persona_estadisticas> personas = new HashSet<Persona_estadisticas>(0);

    public DatosLaborales_estadisticas() {
    }

    public DatosLaborales_estadisticas(long id) {
        this.id = id;
    }

    public DatosLaborales_estadisticas(long id, Division_estadisticas division,
                                       Long idFormacion, GrupoPersonal_estadisticas grupoPersonal, Long idEstadoLaboral,
                                       Long idAreaPersonal, Long idDivisionPersonal,
                                       SubdivisionPersonal_estadisticas subdivisionPersonal, Long idSociedad,
                                       Long idUnidadOrganizativa, String telefonoOficina, Long idPosicion,
                                       Long idManoDominante, String numeroPersonal, Boolean aseguradoIvss,
                                       Long idTipoZonaLaboral, Integer numHijos, Long cid,
                                       Date tiempoServicio, Boolean eliminado,
                                       Set<Persona_estadisticas> personas) {
        this.id = id;
        this.division = division;
        this.idFormacion = idFormacion;
        this.grupoPersonal = grupoPersonal;
        this.idEstadoLaboral = idEstadoLaboral;
        this.idAreaPersonal = idAreaPersonal;
        this.idDivisionPersonal = idDivisionPersonal;
        this.subdivisionPersonal = subdivisionPersonal;
        this.idSociedad = idSociedad;
        this.idUnidadOrganizativa = idUnidadOrganizativa;
        this.telefonoOficina = telefonoOficina;
        this.idPosicion = idPosicion;
        this.idManoDominante = idManoDominante;
        this.numeroPersonal = numeroPersonal;
        this.aseguradoIvss = aseguradoIvss;
        this.idTipoZonaLaboral = idTipoZonaLaboral;
        this.numHijos = numHijos;
        this.cid = cid;
        this.tiempoServicio = tiempoServicio;
        this.eliminado = eliminado;
        this.personas = personas;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @Version
    @Column(name = "version")
    public Integer getVersion() {
        return this.version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_division")
    public Division_estadisticas getDivision() {
        return this.division;
    }

    public void setDivision(Division_estadisticas division) {
        this.division = division;
    }

    @Column(name = "id_formacion")
    public Long getIdFormacion() {
        return this.idFormacion;
    }

    public void setIdFormacion(Long idFormacion) {
        this.idFormacion = idFormacion;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_grupo_personal")
    public GrupoPersonal_estadisticas getGrupoPersonal() {
        return this.grupoPersonal;
    }

    public void setGrupoPersonal(GrupoPersonal_estadisticas grupoPersonal) {
        this.grupoPersonal = grupoPersonal;
    }

    @Column(name = "id_estado_laboral")
    public Long getIdEstadoLaboral() {
        return this.idEstadoLaboral;
    }

    public void setIdEstadoLaboral(Long idEstadoLaboral) {
        this.idEstadoLaboral = idEstadoLaboral;
    }

    @Column(name = "id_area_personal")
    public Long getIdAreaPersonal() {
        return this.idAreaPersonal;
    }

    public void setIdAreaPersonal(Long idAreaPersonal) {
        this.idAreaPersonal = idAreaPersonal;
    }

    @Column(name = "id_division_personal")
    public Long getIdDivisionPersonal() {
        return this.idDivisionPersonal;
    }

    public void setIdDivisionPersonal(Long idDivisionPersonal) {
        this.idDivisionPersonal = idDivisionPersonal;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_subdivision_personal")
    public SubdivisionPersonal_estadisticas getSubdivisionPersonal() {
        return this.subdivisionPersonal;
    }

    public void setSubdivisionPersonal(
            SubdivisionPersonal_estadisticas subdivisionPersonal) {
        this.subdivisionPersonal = subdivisionPersonal;
    }

    @Column(name = "id_sociedad")
    public Long getIdSociedad() {
        return this.idSociedad;
    }

    public void setIdSociedad(Long idSociedad) {
        this.idSociedad = idSociedad;
    }

    @Column(name = "id_unidad_organizativa")
    public Long getIdUnidadOrganizativa() {
        return this.idUnidadOrganizativa;
    }

    public void setIdUnidadOrganizativa(Long idUnidadOrganizativa) {
        this.idUnidadOrganizativa = idUnidadOrganizativa;
    }

    @Column(name = "telefono_oficina")
    public String getTelefonoOficina() {
        return this.telefonoOficina;
    }

    public void setTelefonoOficina(String telefonoOficina) {
        if (telefonoOficina != null)
            telefonoOficina = telefonoOficina.trim();
        this.telefonoOficina = telefonoOficina;
    }

    @Column(name = "id_posicion")
    public Long getIdPosicion() {
        return this.idPosicion;
    }

    public void setIdPosicion(Long idPosicion) {
        this.idPosicion = idPosicion;
    }

    @Column(name = "id_mano_dominante")
    public Long getIdManoDominante() {
        return this.idManoDominante;
    }

    public void setIdManoDominante(Long idManoDominante) {
        this.idManoDominante = idManoDominante;
    }

    @Column(name = "numero_personal")
    public String getNumeroPersonal() {
        return this.numeroPersonal;
    }

    public void setNumeroPersonal(String numeroPersonal) {
        if (numeroPersonal != null)
            numeroPersonal = numeroPersonal.trim();
        this.numeroPersonal = numeroPersonal;
    }

    @Column(name = "asegurado_ivss")
    public Boolean getAseguradoIvss() {
        return this.aseguradoIvss;
    }

    public void setAseguradoIvss(Boolean aseguradoIvss) {
        this.aseguradoIvss = aseguradoIvss;
    }

    @Column(name = "id_tipo_zona_laboral")
    public Long getIdTipoZonaLaboral() {
        return this.idTipoZonaLaboral;
    }

    public void setIdTipoZonaLaboral(Long idTipoZonaLaboral) {
        this.idTipoZonaLaboral = idTipoZonaLaboral;
    }

    @Column(name = "num_hijos")
    public Integer getNumHijos() {
        return this.numHijos;
    }

    public void setNumHijos(Integer numHijos) {
        this.numHijos = numHijos;
    }

    @Column(name = "cid")
    public Long getCid() {
        return this.cid;
    }

    public void setCid(Long cid) {
        this.cid = cid;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "tiempo_servicio", length = 13)
    public Date getTiempoServicio() {
        return this.tiempoServicio;
    }

    public void setTiempoServicio(Date tiempoServicio) {
        this.tiempoServicio = tiempoServicio;
    }

    @Column(name = "eliminado")
    public Boolean getEliminado() {
        return this.eliminado;
    }

    public void setEliminado(Boolean eliminado) {
        this.eliminado = eliminado;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "datosLaborales")
    public Set<Persona_estadisticas> getPersonas() {
        return this.personas;
    }

    public void setPersonas(Set<Persona_estadisticas> personas) {
        this.personas = personas;
    }

}
