package cu.uci.cesim.hce_back.estadisticas.model.entity.auto;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

import javax.persistence.*;

// Generated Apr 18, 2012 10:46:48 AM by Hibernate Tools 3.4.0.CR1


/**
 * DepartamentoInEntidad generated by hbm2java
 */
@Entity
@Table(name = "departamento_in_entidad", schema = "comun", uniqueConstraints = @UniqueConstraint(columnNames = {
        "id_entidad", "id_departamento"}))
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "id")
public class DepartamentoInEntidad_estadisticas implements java.io.Serializable {

    private long id;
    private int version;
    private Entidad_estadisticas entidad;
    private Departamento_estadisticas departamento;
    private Long cid;
    private Boolean eliminado;

    public DepartamentoInEntidad_estadisticas() {
    }

    public DepartamentoInEntidad_estadisticas(long id,
                                              Entidad_estadisticas entidad, Departamento_estadisticas departamento) {
        this.id = id;
        this.entidad = entidad;
        this.departamento = departamento;
    }

    public DepartamentoInEntidad_estadisticas(long id,
                                              Entidad_estadisticas entidad,
                                              Departamento_estadisticas departamento, Long cid, Boolean eliminado) {
        this.id = id;
        this.entidad = entidad;
        this.departamento = departamento;
        this.cid = cid;
        this.eliminado = eliminado;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @Version
    @Column(name = "version", nullable = false)

    public int getVersion() {
        return this.version;
    }

    public void setVersion(int version) {
        this.version = version;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_entidad", nullable = false)

    public Entidad_estadisticas getEntidad() {
        return this.entidad;
    }

    public void setEntidad(Entidad_estadisticas entidad) {
        this.entidad = entidad;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_departamento", nullable = false)

    public Departamento_estadisticas getDepartamento() {
        return this.departamento;
    }

    public void setDepartamento(Departamento_estadisticas departamento) {
        this.departamento = departamento;
    }

    @Column(name = "cid")
    public Long getCid() {
        return this.cid;
    }

    public void setCid(Long cid) {
        this.cid = cid;
    }

    @Column(name = "eliminado")
    public Boolean getEliminado() {
        return this.eliminado;
    }

    public void setEliminado(Boolean eliminado) {
        this.eliminado = eliminado;
    }

}
