package cu.uci.cesim.hce_back.estadisticas.model.entity.auto;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

// Generated Apr 18, 2012 10:46:48 AM by Hibernate Tools 3.4.0.CR1


/**
 * DesechoSangre generated by hbm2java
 */
@Entity
@Table(name = "desecho_sangre", schema = "bancosangre")
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "id")
public class DesechoSangre_estadisticas implements java.io.Serializable {

    private long id;
    private Integer version;
    private MotivoDesechoSangre_estadisticas motivoDesechoSangre;
    private Enfermera_estadisticas enfermera;
    private String observaciones;
    private Boolean eliminado;
    private Long cid;
    private Set<MovimientoSanguineo_estadisticas> movimientoSanguineos = new HashSet<MovimientoSanguineo_estadisticas>(
            0);

    public DesechoSangre_estadisticas() {
    }

    public DesechoSangre_estadisticas(long id,
                                      MotivoDesechoSangre_estadisticas motivoDesechoSangre,
                                      Enfermera_estadisticas enfermera, String observaciones) {
        this.id = id;
        this.motivoDesechoSangre = motivoDesechoSangre;
        this.enfermera = enfermera;
        this.observaciones = observaciones;
    }

    public DesechoSangre_estadisticas(long id,
                                      MotivoDesechoSangre_estadisticas motivoDesechoSangre,
                                      Enfermera_estadisticas enfermera, String observaciones,
                                      Boolean eliminado, Long cid,
                                      Set<MovimientoSanguineo_estadisticas> movimientoSanguineos) {
        this.id = id;
        this.motivoDesechoSangre = motivoDesechoSangre;
        this.enfermera = enfermera;
        this.observaciones = observaciones;
        this.eliminado = eliminado;
        this.cid = cid;
        this.movimientoSanguineos = movimientoSanguineos;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @Version
    @Column(name = "version")
    public Integer getVersion() {
        return this.version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_motivo", nullable = false)

    public MotivoDesechoSangre_estadisticas getMotivoDesechoSangre() {
        return this.motivoDesechoSangre;
    }

    public void setMotivoDesechoSangre(
            MotivoDesechoSangre_estadisticas motivoDesechoSangre) {
        this.motivoDesechoSangre = motivoDesechoSangre;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_enfermera", nullable = false)

    public Enfermera_estadisticas getEnfermera() {
        return this.enfermera;
    }

    public void setEnfermera(Enfermera_estadisticas enfermera) {
        this.enfermera = enfermera;
    }

    @Column(name = "observaciones", nullable = false)

    public String getObservaciones() {
        return this.observaciones;
    }

    public void setObservaciones(String observaciones) {
        if (observaciones != null)
            observaciones = observaciones.trim();
        this.observaciones = observaciones;
    }

    @Column(name = "eliminado")
    public Boolean getEliminado() {
        return this.eliminado;
    }

    public void setEliminado(Boolean eliminado) {
        this.eliminado = eliminado;
    }

    @Column(name = "cid")
    public Long getCid() {
        return this.cid;
    }

    public void setCid(Long cid) {
        this.cid = cid;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "desechoSangre")
    public Set<MovimientoSanguineo_estadisticas> getMovimientoSanguineos() {
        return this.movimientoSanguineos;
    }

    public void setMovimientoSanguineos(
            Set<MovimientoSanguineo_estadisticas> movimientoSanguineos) {
        this.movimientoSanguineos = movimientoSanguineos;
    }

}
