package cu.uci.cesim.hce_back.estadisticas.model.entity.auto;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

import javax.persistence.*;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

// Generated Apr 18, 2012 10:46:48 AM by Hibernate Tools 3.4.0.CR1


/**
 * DiagnosticoMedico generated by hbm2java
 */
@Entity
@Table(name = "diagnostico_medico", schema = "hc_local")
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "id")
public class DiagnosticoMedico_estadisticas implements java.io.Serializable {

    private long id;
    private Integer version;
    private TipoDiagnostico_estadisticas tipoDiagnostico;
    private Date fechaEmision;
    private Date horaEmision;
    private Boolean eliminado;
    private Long cid;
    private Set<SolicitudIntervencion_estadisticas> solicitudIntervencions = new HashSet<SolicitudIntervencion_estadisticas>(
            0);
    private Set<Egreso_estadisticas> egresosForIdDiagnostico = new HashSet<Egreso_estadisticas>(
            0);
    private Set<SolicitudTransfusion_estadisticas> solicitudTransfusions = new HashSet<SolicitudTransfusion_estadisticas>(
            0);
    private Set<HojaConsulta_estadisticas> hojaConsultasForIdDiagnosticoPrincFinal = new HashSet<HojaConsulta_estadisticas>(
            0);
    private Set<Referencias_estadisticas> referenciases = new HashSet<Referencias_estadisticas>(
            0);
    private Set<OrdenAdmision_estadisticas> ordenAdmisions = new HashSet<OrdenAdmision_estadisticas>(
            0);
    private Set<HojaEmergencia_estadisticas> hojaEmergenciasForIdDiagnosticoFinal = new HashSet<HojaEmergencia_estadisticas>(
            0);
    private Set<SolicitudCitologia_estadisticas> solicitudCitologias = new HashSet<SolicitudCitologia_estadisticas>(
            0);
    private Set<SolicitudCitologiaGinecologica_estadisticas> solicitudCitologiaGinecologicas = new HashSet<SolicitudCitologiaGinecologica_estadisticas>(
            0);
    private Set<SolicitudInterconsulta_estadisticas> solicitudInterconsultas = new HashSet<SolicitudInterconsulta_estadisticas>(
            0);
    private Set<Egreso_estadisticas> egresosForIdDiagnosticoPrincFinal = new HashSet<Egreso_estadisticas>(
            0);
    private Set<SolicitudAutopsia_estadisticas> solicitudAutopsias = new HashSet<SolicitudAutopsia_estadisticas>(
            0);
    private Set<DiagnosticoMedicoEnfermedad_estadisticas> diagnosticoMedicoEnfermedads = new HashSet<DiagnosticoMedicoEnfermedad_estadisticas>(
            0);
    private Set<HojaEmergencia_estadisticas> hojaEmergenciasForIdDiagnosticoFinalRecodificado = new HashSet<HojaEmergencia_estadisticas>(
            0);
    private Set<HojaConsulta_estadisticas> hojaConsultasForIdDiagnostico = new HashSet<HojaConsulta_estadisticas>(
            0);
    private Set<SolicitudBiopsia_estadisticas> solicitudBiopsias = new HashSet<SolicitudBiopsia_estadisticas>(
            0);

    public DiagnosticoMedico_estadisticas() {
    }

    public DiagnosticoMedico_estadisticas(long id, Date fechaEmision,
                                          Date horaEmision) {
        this.id = id;
        this.fechaEmision = fechaEmision;
        this.horaEmision = horaEmision;
    }

    public DiagnosticoMedico_estadisticas(
            long id,
            TipoDiagnostico_estadisticas tipoDiagnostico,
            Date fechaEmision,
            Date horaEmision,
            Boolean eliminado,
            Long cid,
            Set<SolicitudIntervencion_estadisticas> solicitudIntervencions,
            Set<Egreso_estadisticas> egresosForIdDiagnostico,
            Set<SolicitudTransfusion_estadisticas> solicitudTransfusions,
            Set<HojaConsulta_estadisticas> hojaConsultasForIdDiagnosticoPrincFinal,
            Set<Referencias_estadisticas> referenciases,
            Set<OrdenAdmision_estadisticas> ordenAdmisions,
            Set<HojaEmergencia_estadisticas> hojaEmergenciasForIdDiagnosticoFinal,
            Set<SolicitudCitologia_estadisticas> solicitudCitologias,
            Set<SolicitudCitologiaGinecologica_estadisticas> solicitudCitologiaGinecologicas,
            Set<SolicitudInterconsulta_estadisticas> solicitudInterconsultas,
            Set<Egreso_estadisticas> egresosForIdDiagnosticoPrincFinal,
            Set<SolicitudAutopsia_estadisticas> solicitudAutopsias,
            Set<DiagnosticoMedicoEnfermedad_estadisticas> diagnosticoMedicoEnfermedads,
            Set<HojaEmergencia_estadisticas> hojaEmergenciasForIdDiagnosticoFinalRecodificado,
            Set<HojaConsulta_estadisticas> hojaConsultasForIdDiagnostico,
            Set<SolicitudBiopsia_estadisticas> solicitudBiopsias) {
        this.id = id;
        this.tipoDiagnostico = tipoDiagnostico;
        this.fechaEmision = fechaEmision;
        this.horaEmision = horaEmision;
        this.eliminado = eliminado;
        this.cid = cid;
        this.solicitudIntervencions = solicitudIntervencions;
        this.egresosForIdDiagnostico = egresosForIdDiagnostico;
        this.solicitudTransfusions = solicitudTransfusions;
        this.hojaConsultasForIdDiagnosticoPrincFinal = hojaConsultasForIdDiagnosticoPrincFinal;
        this.referenciases = referenciases;
        this.ordenAdmisions = ordenAdmisions;
        this.hojaEmergenciasForIdDiagnosticoFinal = hojaEmergenciasForIdDiagnosticoFinal;
        this.solicitudCitologias = solicitudCitologias;
        this.solicitudCitologiaGinecologicas = solicitudCitologiaGinecologicas;
        this.solicitudInterconsultas = solicitudInterconsultas;
        this.egresosForIdDiagnosticoPrincFinal = egresosForIdDiagnosticoPrincFinal;
        this.solicitudAutopsias = solicitudAutopsias;
        this.diagnosticoMedicoEnfermedads = diagnosticoMedicoEnfermedads;
        this.hojaEmergenciasForIdDiagnosticoFinalRecodificado = hojaEmergenciasForIdDiagnosticoFinalRecodificado;
        this.hojaConsultasForIdDiagnostico = hojaConsultasForIdDiagnostico;
        this.solicitudBiopsias = solicitudBiopsias;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @Version
    @Column(name = "version")
    public Integer getVersion() {
        return this.version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_tipo_diagnostico")
    public TipoDiagnostico_estadisticas getTipoDiagnostico() {
        return this.tipoDiagnostico;
    }

    public void setTipoDiagnostico(TipoDiagnostico_estadisticas tipoDiagnostico) {
        this.tipoDiagnostico = tipoDiagnostico;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "fecha_emision", nullable = false, length = 13)

    public Date getFechaEmision() {
        return this.fechaEmision;
    }

    public void setFechaEmision(Date fechaEmision) {
        this.fechaEmision = fechaEmision;
    }

    @Temporal(TemporalType.TIME)
    @Column(name = "hora_emision", nullable = false, length = 15)

    public Date getHoraEmision() {
        return this.horaEmision;
    }

    public void setHoraEmision(Date horaEmision) {
        this.horaEmision = horaEmision;
    }

    @Column(name = "eliminado")
    public Boolean getEliminado() {
        return this.eliminado;
    }

    public void setEliminado(Boolean eliminado) {
        this.eliminado = eliminado;
    }

    @Column(name = "cid")
    public Long getCid() {
        return this.cid;
    }

    public void setCid(Long cid) {
        this.cid = cid;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "diagnosticoMedico")
    public Set<SolicitudIntervencion_estadisticas> getSolicitudIntervencions() {
        return this.solicitudIntervencions;
    }

    public void setSolicitudIntervencions(
            Set<SolicitudIntervencion_estadisticas> solicitudIntervencions) {
        this.solicitudIntervencions = solicitudIntervencions;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "diagnosticoMedicoByIdDiagnostico")
    public Set<Egreso_estadisticas> getEgresosForIdDiagnostico() {
        return this.egresosForIdDiagnostico;
    }

    public void setEgresosForIdDiagnostico(
            Set<Egreso_estadisticas> egresosForIdDiagnostico) {
        this.egresosForIdDiagnostico = egresosForIdDiagnostico;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "diagnosticoMedico")
    public Set<SolicitudTransfusion_estadisticas> getSolicitudTransfusions() {
        return this.solicitudTransfusions;
    }

    public void setSolicitudTransfusions(
            Set<SolicitudTransfusion_estadisticas> solicitudTransfusions) {
        this.solicitudTransfusions = solicitudTransfusions;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "diagnosticoMedicoByIdDiagnosticoPrincFinal")
    public Set<HojaConsulta_estadisticas> getHojaConsultasForIdDiagnosticoPrincFinal() {
        return this.hojaConsultasForIdDiagnosticoPrincFinal;
    }

    public void setHojaConsultasForIdDiagnosticoPrincFinal(
            Set<HojaConsulta_estadisticas> hojaConsultasForIdDiagnosticoPrincFinal) {
        this.hojaConsultasForIdDiagnosticoPrincFinal = hojaConsultasForIdDiagnosticoPrincFinal;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "diagnosticoMedico")
    public Set<Referencias_estadisticas> getReferenciases() {
        return this.referenciases;
    }

    public void setReferenciases(Set<Referencias_estadisticas> referenciases) {
        this.referenciases = referenciases;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "diagnosticoMedico")
    public Set<OrdenAdmision_estadisticas> getOrdenAdmisions() {
        return this.ordenAdmisions;
    }

    public void setOrdenAdmisions(Set<OrdenAdmision_estadisticas> ordenAdmisions) {
        this.ordenAdmisions = ordenAdmisions;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "diagnosticoMedicoByIdDiagnosticoFinal")
    public Set<HojaEmergencia_estadisticas> getHojaEmergenciasForIdDiagnosticoFinal() {
        return this.hojaEmergenciasForIdDiagnosticoFinal;
    }

    public void setHojaEmergenciasForIdDiagnosticoFinal(
            Set<HojaEmergencia_estadisticas> hojaEmergenciasForIdDiagnosticoFinal) {
        this.hojaEmergenciasForIdDiagnosticoFinal = hojaEmergenciasForIdDiagnosticoFinal;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "diagnosticoMedico")
    public Set<SolicitudCitologia_estadisticas> getSolicitudCitologias() {
        return this.solicitudCitologias;
    }

    public void setSolicitudCitologias(
            Set<SolicitudCitologia_estadisticas> solicitudCitologias) {
        this.solicitudCitologias = solicitudCitologias;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "diagnosticoMedico")
    public Set<SolicitudCitologiaGinecologica_estadisticas> getSolicitudCitologiaGinecologicas() {
        return this.solicitudCitologiaGinecologicas;
    }

    public void setSolicitudCitologiaGinecologicas(
            Set<SolicitudCitologiaGinecologica_estadisticas> solicitudCitologiaGinecologicas) {
        this.solicitudCitologiaGinecologicas = solicitudCitologiaGinecologicas;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "diagnosticoMedico")
    public Set<SolicitudInterconsulta_estadisticas> getSolicitudInterconsultas() {
        return this.solicitudInterconsultas;
    }

    public void setSolicitudInterconsultas(
            Set<SolicitudInterconsulta_estadisticas> solicitudInterconsultas) {
        this.solicitudInterconsultas = solicitudInterconsultas;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "diagnosticoMedicoByIdDiagnosticoPrincFinal")
    public Set<Egreso_estadisticas> getEgresosForIdDiagnosticoPrincFinal() {
        return this.egresosForIdDiagnosticoPrincFinal;
    }

    public void setEgresosForIdDiagnosticoPrincFinal(
            Set<Egreso_estadisticas> egresosForIdDiagnosticoPrincFinal) {
        this.egresosForIdDiagnosticoPrincFinal = egresosForIdDiagnosticoPrincFinal;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "diagnosticoMedico")
    public Set<SolicitudAutopsia_estadisticas> getSolicitudAutopsias() {
        return this.solicitudAutopsias;
    }

    public void setSolicitudAutopsias(
            Set<SolicitudAutopsia_estadisticas> solicitudAutopsias) {
        this.solicitudAutopsias = solicitudAutopsias;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "diagnosticoMedico")
    public Set<DiagnosticoMedicoEnfermedad_estadisticas> getDiagnosticoMedicoEnfermedads() {
        return this.diagnosticoMedicoEnfermedads;
    }

    public void setDiagnosticoMedicoEnfermedads(
            Set<DiagnosticoMedicoEnfermedad_estadisticas> diagnosticoMedicoEnfermedads) {
        this.diagnosticoMedicoEnfermedads = diagnosticoMedicoEnfermedads;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "diagnosticoMedicoByIdDiagnosticoFinalRecodificado")
    public Set<HojaEmergencia_estadisticas> getHojaEmergenciasForIdDiagnosticoFinalRecodificado() {
        return this.hojaEmergenciasForIdDiagnosticoFinalRecodificado;
    }

    public void setHojaEmergenciasForIdDiagnosticoFinalRecodificado(
            Set<HojaEmergencia_estadisticas> hojaEmergenciasForIdDiagnosticoFinalRecodificado) {
        this.hojaEmergenciasForIdDiagnosticoFinalRecodificado = hojaEmergenciasForIdDiagnosticoFinalRecodificado;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "diagnosticoMedicoByIdDiagnostico")
    public Set<HojaConsulta_estadisticas> getHojaConsultasForIdDiagnostico() {
        return this.hojaConsultasForIdDiagnostico;
    }

    public void setHojaConsultasForIdDiagnostico(
            Set<HojaConsulta_estadisticas> hojaConsultasForIdDiagnostico) {
        this.hojaConsultasForIdDiagnostico = hojaConsultasForIdDiagnostico;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "diagnosticoMedico")
    public Set<SolicitudBiopsia_estadisticas> getSolicitudBiopsias() {
        return this.solicitudBiopsias;
    }

    public void setSolicitudBiopsias(
            Set<SolicitudBiopsia_estadisticas> solicitudBiopsias) {
        this.solicitudBiopsias = solicitudBiopsias;
    }

}
