package cu.uci.cesim.hce_back.estadisticas.model.entity.auto;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

import javax.persistence.*;

// Generated Apr 18, 2012 10:46:48 AM by Hibernate Tools 3.4.0.CR1

/**
 * EdadDesglosada generated by hbm2java
 */
@Entity
@Table(name = "edad_desglosada", schema = "estadisticas")
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "id")
public class EdadDesglosada_estadisticas implements java.io.Serializable {

    private long id;
    private Integer version;
    private PoblacionEdad_estadisticas poblacionEdad;
    private Integer mesInicial;
    private Integer mesFinal;
    private Long valor;
    private Boolean eliminado;
    private Long cid;

    public EdadDesglosada_estadisticas() {
    }

    public EdadDesglosada_estadisticas(long id) {
        this.id = id;
    }

    public EdadDesglosada_estadisticas(long id,
                                       PoblacionEdad_estadisticas poblacionEdad, Integer mesInicial,
                                       Integer mesFinal, Long valor, Boolean eliminado, Long cid) {
        this.id = id;
        this.poblacionEdad = poblacionEdad;
        this.mesInicial = mesInicial;
        this.mesFinal = mesFinal;
        this.valor = valor;
        this.eliminado = eliminado;
        this.cid = cid;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @Version
    @Column(name = "version")
    public Integer getVersion() {
        return this.version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_edad")
    public PoblacionEdad_estadisticas getPoblacionEdad() {
        return this.poblacionEdad;
    }

    public void setPoblacionEdad(PoblacionEdad_estadisticas poblacionEdad) {
        this.poblacionEdad = poblacionEdad;
    }

    @Column(name = "mes_inicial")
    public Integer getMesInicial() {
        return this.mesInicial;
    }

    public void setMesInicial(Integer mesInicial) {
        this.mesInicial = mesInicial;
    }

    @Column(name = "mes_final")
    public Integer getMesFinal() {
        return this.mesFinal;
    }

    public void setMesFinal(Integer mesFinal) {
        this.mesFinal = mesFinal;
    }

    @Column(name = "valor")
    public Long getValor() {
        return this.valor;
    }

    public void setValor(Long valor) {
        this.valor = valor;
    }

    @Column(name = "eliminado")
    public Boolean getEliminado() {
        return this.eliminado;
    }

    public void setEliminado(Boolean eliminado) {
        this.eliminado = eliminado;
    }

    @Column(name = "cid")
    public Long getCid() {
        return this.cid;
    }

    public void setCid(Long cid) {
        this.cid = cid;
    }

}
