package cu.uci.cesim.hce_back.estadisticas.model.entity.auto;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

import javax.persistence.*;

// Generated Apr 18, 2012 10:46:48 AM by Hibernate Tools 3.4.0.CR1


/**
 * EnfermeraInEntidad generated by hbm2java
 */
@Entity
@Table(name = "enfermera_in_entidad", schema = "comun")
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "id")
public class EnfermeraInEntidad_estadisticas implements java.io.Serializable {

    private long id;
    private Integer version;
    private Entidad_estadisticas entidad;
    private Enfermera_estadisticas enfermera;
    private Boolean eliminado;
    private Long cid;

    public EnfermeraInEntidad_estadisticas() {
    }

    public EnfermeraInEntidad_estadisticas(long id,
                                           Entidad_estadisticas entidad, Enfermera_estadisticas enfermera) {
        this.id = id;
        this.entidad = entidad;
        this.enfermera = enfermera;
    }

    public EnfermeraInEntidad_estadisticas(long id,
                                           Entidad_estadisticas entidad, Enfermera_estadisticas enfermera,
                                           Boolean eliminado, Long cid) {
        this.id = id;
        this.entidad = entidad;
        this.enfermera = enfermera;
        this.eliminado = eliminado;
        this.cid = cid;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @Version
    @Column(name = "version")
    public Integer getVersion() {
        return this.version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_entidad", nullable = false)

    public Entidad_estadisticas getEntidad() {
        return this.entidad;
    }

    public void setEntidad(Entidad_estadisticas entidad) {
        this.entidad = entidad;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_enfermero", nullable = false)

    public Enfermera_estadisticas getEnfermera() {
        return this.enfermera;
    }

    public void setEnfermera(Enfermera_estadisticas enfermera) {
        this.enfermera = enfermera;
    }

    @Column(name = "eliminado")
    public Boolean getEliminado() {
        return this.eliminado;
    }

    public void setEliminado(Boolean eliminado) {
        this.eliminado = eliminado;
    }

    @Column(name = "cid")
    public Long getCid() {
        return this.cid;
    }

    public void setCid(Long cid) {
        this.cid = cid;
    }

}
