package cu.uci.cesim.hce_back.estadisticas.model.entity.auto;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

// Generated Apr 18, 2012 10:46:48 AM by Hibernate Tools 3.4.0.CR1


/**
 * EntregaSangre generated by hbm2java
 */
@Entity
@Table(name = "entrega_sangre", schema = "publico")
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "id")
public class EntregaSangre_estadisticas implements java.io.Serializable {

    private long id;
    private Integer version;
    private Enfermera_estadisticas enfermeraByIdEnfermeraEntrega;
    private SolicitudTransfusion_estadisticas solicitudTransfusion;
    private Enfermera_estadisticas enfermeraByIdEnfermeraRecibe;
    private Boolean eliminado;
    private Long cid;
    private Set<RegistroTransfusion_estadisticas> registroTransfusions = new HashSet<RegistroTransfusion_estadisticas>(
            0);
    private Set<BolsaSangreInEntrega_estadisticas> bolsaSangreInEntregas = new HashSet<BolsaSangreInEntrega_estadisticas>(
            0);
    private Set<MovimientoSanguineo_estadisticas> movimientoSanguineos = new HashSet<MovimientoSanguineo_estadisticas>(
            0);

    public EntregaSangre_estadisticas() {
    }

    public EntregaSangre_estadisticas(long id,
                                      Enfermera_estadisticas enfermeraByIdEnfermeraEntrega,
                                      SolicitudTransfusion_estadisticas solicitudTransfusion,
                                      Enfermera_estadisticas enfermeraByIdEnfermeraRecibe) {
        this.id = id;
        this.enfermeraByIdEnfermeraEntrega = enfermeraByIdEnfermeraEntrega;
        this.solicitudTransfusion = solicitudTransfusion;
        this.enfermeraByIdEnfermeraRecibe = enfermeraByIdEnfermeraRecibe;
    }

    public EntregaSangre_estadisticas(long id,
                                      Enfermera_estadisticas enfermeraByIdEnfermeraEntrega,
                                      SolicitudTransfusion_estadisticas solicitudTransfusion,
                                      Enfermera_estadisticas enfermeraByIdEnfermeraRecibe,
                                      Boolean eliminado, Long cid,
                                      Set<RegistroTransfusion_estadisticas> registroTransfusions,
                                      Set<BolsaSangreInEntrega_estadisticas> bolsaSangreInEntregas,
                                      Set<MovimientoSanguineo_estadisticas> movimientoSanguineos) {
        this.id = id;
        this.enfermeraByIdEnfermeraEntrega = enfermeraByIdEnfermeraEntrega;
        this.solicitudTransfusion = solicitudTransfusion;
        this.enfermeraByIdEnfermeraRecibe = enfermeraByIdEnfermeraRecibe;
        this.eliminado = eliminado;
        this.cid = cid;
        this.registroTransfusions = registroTransfusions;
        this.bolsaSangreInEntregas = bolsaSangreInEntregas;
        this.movimientoSanguineos = movimientoSanguineos;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @Version
    @Column(name = "version")
    public Integer getVersion() {
        return this.version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_enfermera_entrega", nullable = false)

    public Enfermera_estadisticas getEnfermeraByIdEnfermeraEntrega() {
        return this.enfermeraByIdEnfermeraEntrega;
    }

    public void setEnfermeraByIdEnfermeraEntrega(
            Enfermera_estadisticas enfermeraByIdEnfermeraEntrega) {
        this.enfermeraByIdEnfermeraEntrega = enfermeraByIdEnfermeraEntrega;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_solicitud", nullable = false)

    public SolicitudTransfusion_estadisticas getSolicitudTransfusion() {
        return this.solicitudTransfusion;
    }

    public void setSolicitudTransfusion(
            SolicitudTransfusion_estadisticas solicitudTransfusion) {
        this.solicitudTransfusion = solicitudTransfusion;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_enfermera_recibe", nullable = false)

    public Enfermera_estadisticas getEnfermeraByIdEnfermeraRecibe() {
        return this.enfermeraByIdEnfermeraRecibe;
    }

    public void setEnfermeraByIdEnfermeraRecibe(
            Enfermera_estadisticas enfermeraByIdEnfermeraRecibe) {
        this.enfermeraByIdEnfermeraRecibe = enfermeraByIdEnfermeraRecibe;
    }

    @Column(name = "eliminado")
    public Boolean getEliminado() {
        return this.eliminado;
    }

    public void setEliminado(Boolean eliminado) {
        this.eliminado = eliminado;
    }

    @Column(name = "cid")
    public Long getCid() {
        return this.cid;
    }

    public void setCid(Long cid) {
        this.cid = cid;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "entregaSangre")
    public Set<RegistroTransfusion_estadisticas> getRegistroTransfusions() {
        return this.registroTransfusions;
    }

    public void setRegistroTransfusions(
            Set<RegistroTransfusion_estadisticas> registroTransfusions) {
        this.registroTransfusions = registroTransfusions;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "entregaSangre")
    public Set<BolsaSangreInEntrega_estadisticas> getBolsaSangreInEntregas() {
        return this.bolsaSangreInEntregas;
    }

    public void setBolsaSangreInEntregas(
            Set<BolsaSangreInEntrega_estadisticas> bolsaSangreInEntregas) {
        this.bolsaSangreInEntregas = bolsaSangreInEntregas;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "entregaSangre")
    public Set<MovimientoSanguineo_estadisticas> getMovimientoSanguineos() {
        return this.movimientoSanguineos;
    }

    public void setMovimientoSanguineos(
            Set<MovimientoSanguineo_estadisticas> movimientoSanguineos) {
        this.movimientoSanguineos = movimientoSanguineos;
    }

}
