package cu.uci.cesim.hce_back.estadisticas.model.entity.auto;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

// Generated Apr 18, 2012 10:46:48 AM by Hibernate Tools 3.4.0.CR1


/**
 * Estado generated by hbm2java
 */
@Entity
@Table(name = "estado", schema = "nomencladores", uniqueConstraints = @UniqueConstraint(columnNames = "codigo"))
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "id")
public class Estado_estadisticas implements java.io.Serializable {

    private long id;
    private Integer version;
    private Nacion_estadisticas nacion;
    private String valor;
    private Boolean eliminado;
    private Long cid;
    private String codigo;
    private Set<Direccion_estadisticas> direccions = new HashSet<Direccion_estadisticas>(
            0);
    private Set<Municipio_estadisticas> municipios = new HashSet<Municipio_estadisticas>(
            0);
    private Set<Entidad_estadisticas> entidads = new HashSet<Entidad_estadisticas>(
            0);

    public Estado_estadisticas() {
    }

    public Estado_estadisticas(long id, Nacion_estadisticas nacion, String valor) {
        this.id = id;
        this.nacion = nacion;
        this.valor = valor;
    }

    public Estado_estadisticas(long id, Nacion_estadisticas nacion,
                               String valor, Boolean eliminado, Long cid, String codigo,
                               Set<Direccion_estadisticas> direccions,
                               Set<Municipio_estadisticas> municipios,
                               Set<Entidad_estadisticas> entidads) {
        this.id = id;
        this.nacion = nacion;
        this.valor = valor;
        this.eliminado = eliminado;
        this.cid = cid;
        this.codigo = codigo;
        this.direccions = direccions;
        this.municipios = municipios;
        this.entidads = entidads;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @Version
    @Column(name = "version")
    public Integer getVersion() {
        return this.version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_nacion", nullable = false)

    public Nacion_estadisticas getNacion() {
        return this.nacion;
    }

    public void setNacion(Nacion_estadisticas nacion) {
        this.nacion = nacion;
    }

    @Column(name = "valor", nullable = false)

    public String getValor() {
        return this.valor;
    }

    public void setValor(String valor) {
        if (valor != null)
            valor = valor.trim();
        this.valor = valor;
    }

    @Column(name = "eliminado")
    public Boolean getEliminado() {
        return this.eliminado;
    }

    public void setEliminado(Boolean eliminado) {
        this.eliminado = eliminado;
    }

    @Column(name = "cid")
    public Long getCid() {
        return this.cid;
    }

    public void setCid(Long cid) {
        this.cid = cid;
    }

    @Column(name = "codigo", unique = true)
    public String getCodigo() {
        return this.codigo;
    }

    public void setCodigo(String codigo) {
        if (codigo != null)
            codigo = codigo.trim();
        this.codigo = codigo;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "estado")
    public Set<Direccion_estadisticas> getDireccions() {
        return this.direccions;
    }

    public void setDireccions(Set<Direccion_estadisticas> direccions) {
        this.direccions = direccions;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "estado")
    public Set<Municipio_estadisticas> getMunicipios() {
        return this.municipios;
    }

    public void setMunicipios(Set<Municipio_estadisticas> municipios) {
        this.municipios = municipios;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "estado")
    public Set<Entidad_estadisticas> getEntidads() {
        return this.entidads;
    }

    public void setEntidads(Set<Entidad_estadisticas> entidads) {
        this.entidads = entidads;
    }

}
