package cu.uci.cesim.hce_back.estadisticas.model.entity.auto;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;
import org.hibernate.validator.constraints.Length;

import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

// Generated Apr 18, 2012 10:46:48 AM by Hibernate Tools 3.4.0.CR1


/**
 * EstadoCama generated by hbm2java
 */
@Entity
@Table(name = "estado_cama", schema = "comun", uniqueConstraints = {
        @UniqueConstraint(columnNames = "valor"),
        @UniqueConstraint(columnNames = "codigo")})
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "id")
public class EstadoCama_estadisticas implements java.io.Serializable {

    private long id;
    private Integer version;
    private String valor;
    private Boolean eliminado;
    private Long cid;
    private String codigo;
    private Set<Cama_estadisticas> camas = new HashSet<Cama_estadisticas>(0);
    private Set<CamasHistorico_estadisticas> camasHistoricos = new HashSet<CamasHistorico_estadisticas>(
            0);

    public EstadoCama_estadisticas() {
    }

    public EstadoCama_estadisticas(long id, String valor, String codigo) {
        this.id = id;
        this.valor = valor;
        this.codigo = codigo;
    }

    public EstadoCama_estadisticas(long id, String valor, Boolean eliminado,
                                   Long cid, String codigo, Set<Cama_estadisticas> camas,
                                   Set<CamasHistorico_estadisticas> camasHistoricos) {
        this.id = id;
        this.valor = valor;
        this.eliminado = eliminado;
        this.cid = cid;
        this.codigo = codigo;
        this.camas = camas;
        this.camasHistoricos = camasHistoricos;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @Version
    @Column(name = "version")
    public Integer getVersion() {
        return this.version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    @Column(name = "valor", unique = true, nullable = false)

    public String getValor() {
        return this.valor;
    }

    public void setValor(String valor) {
        if (valor != null)
            valor = valor.trim();
        this.valor = valor;
    }

    @Column(name = "eliminado")
    public Boolean getEliminado() {
        return this.eliminado;
    }

    public void setEliminado(Boolean eliminado) {
        this.eliminado = eliminado;
    }

    @Column(name = "cid")
    public Long getCid() {
        return this.cid;
    }

    public void setCid(Long cid) {
        this.cid = cid;
    }

    @Column(name = "codigo", unique = true, nullable = false, length = 50)

    @Length(max = 50)
    public String getCodigo() {
        return this.codigo;
    }

    public void setCodigo(String codigo) {
        if (codigo != null)
            codigo = codigo.trim();
        this.codigo = codigo;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "estadoCama")
    public Set<Cama_estadisticas> getCamas() {
        return this.camas;
    }

    public void setCamas(Set<Cama_estadisticas> camas) {
        this.camas = camas;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "estadoCama")
    public Set<CamasHistorico_estadisticas> getCamasHistoricos() {
        return this.camasHistoricos;
    }

    public void setCamasHistoricos(
            Set<CamasHistorico_estadisticas> camasHistoricos) {
        this.camasHistoricos = camasHistoricos;
    }

}
