package cu.uci.cesim.hce_back.estadisticas.model.entity.auto;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

import javax.persistence.*;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

// Generated Apr 18, 2012 10:46:48 AM by Hibernate Tools 3.4.0.CR1


/**
 * Fallecimiento generated by hbm2java
 */
@Entity
@Table(name = "fallecimiento", schema = "hc_local")
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "id")
public class Fallecimiento_estadisticas implements java.io.Serializable {

    private long id;
    private Integer version;
    private CertificadoDefuncion_estadisticas certificadoDefuncion;
    private Date fecha;
    private Date hora;
    private Boolean eliminado;
    private Long cid;
    private Integer idSolicitudAutopsia;
    private String motivoAutopsia;
    private String causaMuerteA;
    private String causaMuerteB;
    private String causaMuerteC;
    private String causaMuerteD;
    private String causaMuerteOtras;
    private Boolean confirmacionClinica;
    private Boolean confirmacionInvestigacion;
    private Boolean confirmacionOperacion;
    private Boolean confirmacionBiopsia;
    private Boolean confirmacionNecropsia;
    private Set<Egreso_estadisticas> egresos = new HashSet<Egreso_estadisticas>(
            0);

    public Fallecimiento_estadisticas() {
    }

    public Fallecimiento_estadisticas(long id, Date fecha, Date hora) {
        this.id = id;
        this.fecha = fecha;
        this.hora = hora;
    }

    public Fallecimiento_estadisticas(long id,
                                      CertificadoDefuncion_estadisticas certificadoDefuncion, Date fecha,
                                      Date hora, Boolean eliminado, Long cid,
                                      Integer idSolicitudAutopsia, String motivoAutopsia,
                                      String causaMuerteA, String causaMuerteB, String causaMuerteC,
                                      String causaMuerteD, String causaMuerteOtras,
                                      Boolean confirmacionClinica, Boolean confirmacionInvestigacion,
                                      Boolean confirmacionOperacion, Boolean confirmacionBiopsia,
                                      Boolean confirmacionNecropsia, Set<Egreso_estadisticas> egresos) {
        this.id = id;
        this.certificadoDefuncion = certificadoDefuncion;
        this.fecha = fecha;
        this.hora = hora;
        this.eliminado = eliminado;
        this.cid = cid;
        this.idSolicitudAutopsia = idSolicitudAutopsia;
        this.motivoAutopsia = motivoAutopsia;
        this.causaMuerteA = causaMuerteA;
        this.causaMuerteB = causaMuerteB;
        this.causaMuerteC = causaMuerteC;
        this.causaMuerteD = causaMuerteD;
        this.causaMuerteOtras = causaMuerteOtras;
        this.confirmacionClinica = confirmacionClinica;
        this.confirmacionInvestigacion = confirmacionInvestigacion;
        this.confirmacionOperacion = confirmacionOperacion;
        this.confirmacionBiopsia = confirmacionBiopsia;
        this.confirmacionNecropsia = confirmacionNecropsia;
        this.egresos = egresos;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @Version
    @Column(name = "version")
    public Integer getVersion() {
        return this.version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_certificado_defuncion")
    public CertificadoDefuncion_estadisticas getCertificadoDefuncion() {
        return this.certificadoDefuncion;
    }

    public void setCertificadoDefuncion(
            CertificadoDefuncion_estadisticas certificadoDefuncion) {
        this.certificadoDefuncion = certificadoDefuncion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "fecha", nullable = false, length = 13)

    public Date getFecha() {
        return this.fecha;
    }

    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    @Temporal(TemporalType.TIME)
    @Column(name = "hora", nullable = false, length = 15)

    public Date getHora() {
        return this.hora;
    }

    public void setHora(Date hora) {
        this.hora = hora;
    }

    @Column(name = "eliminado")
    public Boolean getEliminado() {
        return this.eliminado;
    }

    public void setEliminado(Boolean eliminado) {
        this.eliminado = eliminado;
    }

    @Column(name = "cid")
    public Long getCid() {
        return this.cid;
    }

    public void setCid(Long cid) {
        this.cid = cid;
    }

    @Column(name = "id_solicitud_autopsia")
    public Integer getIdSolicitudAutopsia() {
        return this.idSolicitudAutopsia;
    }

    public void setIdSolicitudAutopsia(Integer idSolicitudAutopsia) {
        this.idSolicitudAutopsia = idSolicitudAutopsia;
    }

    @Column(name = "motivo_autopsia")
    public String getMotivoAutopsia() {
        return this.motivoAutopsia;
    }

    public void setMotivoAutopsia(String motivoAutopsia) {
        if (motivoAutopsia != null)
            motivoAutopsia = motivoAutopsia.trim();
        this.motivoAutopsia = motivoAutopsia;
    }

    @Column(name = "causa_muerte_a")
    public String getCausaMuerteA() {
        return this.causaMuerteA;
    }

    public void setCausaMuerteA(String causaMuerteA) {
        if (causaMuerteA != null)
            causaMuerteA = causaMuerteA.trim();
        this.causaMuerteA = causaMuerteA;
    }

    @Column(name = "causa_muerte_b")
    public String getCausaMuerteB() {
        return this.causaMuerteB;
    }

    public void setCausaMuerteB(String causaMuerteB) {
        if (causaMuerteB != null)
            causaMuerteB = causaMuerteB.trim();
        this.causaMuerteB = causaMuerteB;
    }

    @Column(name = "causa_muerte_c")
    public String getCausaMuerteC() {
        return this.causaMuerteC;
    }

    public void setCausaMuerteC(String causaMuerteC) {
        if (causaMuerteC != null)
            causaMuerteC = causaMuerteC.trim();
        this.causaMuerteC = causaMuerteC;
    }

    @Column(name = "causa_muerte_d")
    public String getCausaMuerteD() {
        return this.causaMuerteD;
    }

    public void setCausaMuerteD(String causaMuerteD) {
        if (causaMuerteD != null)
            causaMuerteD = causaMuerteD.trim();
        this.causaMuerteD = causaMuerteD;
    }

    @Column(name = "causa_muerte_otras")
    public String getCausaMuerteOtras() {
        return this.causaMuerteOtras;
    }

    public void setCausaMuerteOtras(String causaMuerteOtras) {
        if (causaMuerteOtras != null)
            causaMuerteOtras = causaMuerteOtras.trim();
        this.causaMuerteOtras = causaMuerteOtras;
    }

    @Column(name = "confirmacion_clinica")
    public Boolean getConfirmacionClinica() {
        return this.confirmacionClinica;
    }

    public void setConfirmacionClinica(Boolean confirmacionClinica) {
        this.confirmacionClinica = confirmacionClinica;
    }

    @Column(name = "confirmacion_investigacion")
    public Boolean getConfirmacionInvestigacion() {
        return this.confirmacionInvestigacion;
    }

    public void setConfirmacionInvestigacion(Boolean confirmacionInvestigacion) {
        this.confirmacionInvestigacion = confirmacionInvestigacion;
    }

    @Column(name = "confirmacion_operacion")
    public Boolean getConfirmacionOperacion() {
        return this.confirmacionOperacion;
    }

    public void setConfirmacionOperacion(Boolean confirmacionOperacion) {
        this.confirmacionOperacion = confirmacionOperacion;
    }

    @Column(name = "confirmacion_biopsia")
    public Boolean getConfirmacionBiopsia() {
        return this.confirmacionBiopsia;
    }

    public void setConfirmacionBiopsia(Boolean confirmacionBiopsia) {
        this.confirmacionBiopsia = confirmacionBiopsia;
    }

    @Column(name = "confirmacion_necropsia")
    public Boolean getConfirmacionNecropsia() {
        return this.confirmacionNecropsia;
    }

    public void setConfirmacionNecropsia(Boolean confirmacionNecropsia) {
        this.confirmacionNecropsia = confirmacionNecropsia;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "fallecimiento")
    public Set<Egreso_estadisticas> getEgresos() {
        return this.egresos;
    }

    public void setEgresos(Set<Egreso_estadisticas> egresos) {
        this.egresos = egresos;
    }

}
