package cu.uci.cesim.hce_back.estadisticas.model.entity.auto;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

// Generated Apr 18, 2012 10:46:48 AM by Hibernate Tools 3.4.0.CR1


/**
 * GrupoSanguineo generated by hbm2java
 */
@Entity
@Table(name = "grupo_sanguineo", schema = "nomencladores")
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "id")
public class GrupoSanguineo_estadisticas implements java.io.Serializable {

    private long id;
    private int version;
    private FactorSanguineo_estadisticas factorSanguineo;
    private String valor;
    private long cid;
    private boolean eliminado;
    private String codigo;
    private Set<PersonaHist_estadisticas> personaHists = new HashSet<PersonaHist_estadisticas>(
            0);
    private Set<BolsaSangre_estadisticas> bolsaSangres = new HashSet<BolsaSangre_estadisticas>(
            0);
    private Set<HojaFrontal_estadisticas> hojaFrontals = new HashSet<HojaFrontal_estadisticas>(
            0);

    public GrupoSanguineo_estadisticas() {
    }

    public GrupoSanguineo_estadisticas(long id,
                                       FactorSanguineo_estadisticas factorSanguineo, String valor,
                                       long cid, boolean eliminado) {
        this.id = id;
        this.factorSanguineo = factorSanguineo;
        this.valor = valor;
        this.cid = cid;
        this.eliminado = eliminado;
    }

    public GrupoSanguineo_estadisticas(long id,
                                       FactorSanguineo_estadisticas factorSanguineo, String valor,
                                       long cid, boolean eliminado, String codigo,
                                       Set<PersonaHist_estadisticas> personaHists,
                                       Set<BolsaSangre_estadisticas> bolsaSangres,
                                       Set<HojaFrontal_estadisticas> hojaFrontals) {
        this.id = id;
        this.factorSanguineo = factorSanguineo;
        this.valor = valor;
        this.cid = cid;
        this.eliminado = eliminado;
        this.codigo = codigo;
        this.personaHists = personaHists;
        this.bolsaSangres = bolsaSangres;
        this.hojaFrontals = hojaFrontals;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @Version
    @Column(name = "version", nullable = false)

    public int getVersion() {
        return this.version;
    }

    public void setVersion(int version) {
        this.version = version;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_factor", nullable = false)

    public FactorSanguineo_estadisticas getFactorSanguineo() {
        return this.factorSanguineo;
    }

    public void setFactorSanguineo(FactorSanguineo_estadisticas factorSanguineo) {
        this.factorSanguineo = factorSanguineo;
    }

    @Column(name = "valor", nullable = false)

    public String getValor() {
        return this.valor;
    }

    public void setValor(String valor) {
        if (valor != null)
            valor = valor.trim();
        this.valor = valor;
    }

    @Column(name = "cid", nullable = false)

    public long getCid() {
        return this.cid;
    }

    public void setCid(long cid) {
        this.cid = cid;
    }

    @Column(name = "eliminado", nullable = false)

    public boolean isEliminado() {
        return this.eliminado;
    }

    public void setEliminado(boolean eliminado) {
        this.eliminado = eliminado;
    }

    @Column(name = "codigo")
    public String getCodigo() {
        return this.codigo;
    }

    public void setCodigo(String codigo) {
        if (codigo != null)
            codigo = codigo.trim();
        this.codigo = codigo;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "grupoSanguineo")
    public Set<PersonaHist_estadisticas> getPersonaHists() {
        return this.personaHists;
    }

    public void setPersonaHists(Set<PersonaHist_estadisticas> personaHists) {
        this.personaHists = personaHists;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "grupoSanguineo")
    public Set<BolsaSangre_estadisticas> getBolsaSangres() {
        return this.bolsaSangres;
    }

    public void setBolsaSangres(Set<BolsaSangre_estadisticas> bolsaSangres) {
        this.bolsaSangres = bolsaSangres;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "grupoSanguineo")
    public Set<HojaFrontal_estadisticas> getHojaFrontals() {
        return this.hojaFrontals;
    }

    public void setHojaFrontals(Set<HojaFrontal_estadisticas> hojaFrontals) {
        this.hojaFrontals = hojaFrontals;
    }

}
