package cu.uci.cesim.hce_back.estadisticas.model.entity.auto;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

import javax.persistence.*;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

// Generated Apr 18, 2012 10:46:48 AM by Hibernate Tools 3.4.0.CR1


/**
 * HorarioCita generated by hbm2java
 */
@Entity
@Table(name = "horario_cita", schema = "publico")
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "id")
public class HorarioCita_estadisticas implements java.io.Serializable {

    private long id;
    private Integer version;
    private TipoCita_estadisticas tipoCita;
    private Date horaInicio;
    private Date horaFin;
    private int cantPacientes;
    private Boolean eliminado;
    private Long cid;
    private Date fechaInicio;
    private Date fechaFin;
    private Set<PlanificacionMedico_estadisticas> planificacionMedicos = new HashSet<PlanificacionMedico_estadisticas>(
            0);
    private Set<Cita_estadisticas> citas = new HashSet<Cita_estadisticas>(0);

    public HorarioCita_estadisticas() {
    }

    public HorarioCita_estadisticas(long id, TipoCita_estadisticas tipoCita,
                                    Date horaInicio, Date horaFin, int cantPacientes, Date fechaInicio,
                                    Date fechaFin) {
        this.id = id;
        this.tipoCita = tipoCita;
        this.horaInicio = horaInicio;
        this.horaFin = horaFin;
        this.cantPacientes = cantPacientes;
        this.fechaInicio = fechaInicio;
        this.fechaFin = fechaFin;
    }

    public HorarioCita_estadisticas(long id, TipoCita_estadisticas tipoCita,
                                    Date horaInicio, Date horaFin, int cantPacientes,
                                    Boolean eliminado, Long cid, Date fechaInicio, Date fechaFin,
                                    Set<PlanificacionMedico_estadisticas> planificacionMedicos,
                                    Set<Cita_estadisticas> citas) {
        this.id = id;
        this.tipoCita = tipoCita;
        this.horaInicio = horaInicio;
        this.horaFin = horaFin;
        this.cantPacientes = cantPacientes;
        this.eliminado = eliminado;
        this.cid = cid;
        this.fechaInicio = fechaInicio;
        this.fechaFin = fechaFin;
        this.planificacionMedicos = planificacionMedicos;
        this.citas = citas;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @Version
    @Column(name = "version")
    public Integer getVersion() {
        return this.version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_tipo_cita", nullable = false)

    public TipoCita_estadisticas getTipoCita() {
        return this.tipoCita;
    }

    public void setTipoCita(TipoCita_estadisticas tipoCita) {
        this.tipoCita = tipoCita;
    }

    @Temporal(TemporalType.TIME)
    @Column(name = "hora_inicio", nullable = false, length = 8)

    public Date getHoraInicio() {
        return this.horaInicio;
    }

    public void setHoraInicio(Date horaInicio) {
        this.horaInicio = horaInicio;
    }

    @Temporal(TemporalType.TIME)
    @Column(name = "hora_fin", nullable = false, length = 8)

    public Date getHoraFin() {
        return this.horaFin;
    }

    public void setHoraFin(Date horaFin) {
        this.horaFin = horaFin;
    }

    @Column(name = "cant_pacientes", nullable = false)

    public int getCantPacientes() {
        return this.cantPacientes;
    }

    public void setCantPacientes(int cantPacientes) {
        this.cantPacientes = cantPacientes;
    }

    @Column(name = "eliminado")
    public Boolean getEliminado() {
        return this.eliminado;
    }

    public void setEliminado(Boolean eliminado) {
        this.eliminado = eliminado;
    }

    @Column(name = "cid")
    public Long getCid() {
        return this.cid;
    }

    public void setCid(Long cid) {
        this.cid = cid;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "fecha_inicio", nullable = false, length = 13)

    public Date getFechaInicio() {
        return this.fechaInicio;
    }

    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "fecha_fin", nullable = false, length = 13)

    public Date getFechaFin() {
        return this.fechaFin;
    }

    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "horarioCita")
    public Set<PlanificacionMedico_estadisticas> getPlanificacionMedicos() {
        return this.planificacionMedicos;
    }

    public void setPlanificacionMedicos(
            Set<PlanificacionMedico_estadisticas> planificacionMedicos) {
        this.planificacionMedicos = planificacionMedicos;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "horarioCita")
    public Set<Cita_estadisticas> getCitas() {
        return this.citas;
    }

    public void setCitas(Set<Cita_estadisticas> citas) {
        this.citas = citas;
    }

}
