package cu.uci.cesim.hce_back.estadisticas.model.entity.auto;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

import javax.persistence.*;
import java.util.Date;

// Generated Jun 4, 2012 4:59:22 PM by Hibernate Tools 3.4.0.CR1


/**
 * IndicacionMedicaTratamiento generated by hbm2java
 */
@Entity
@Table(name = "indicacion_medica_tratamiento", schema = "hc_local")
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "id")
public class IndicacionMedicaTratamiento_estadisticas implements
        java.io.Serializable {

    private long id;
    private Integer version;
    private TratamientoMedico_estadisticas tratamientoMedico;
    private UnidadTiempo_estadisticas unidadTiempo;
    private Long indicacionMedica;
    private Long viaAdministracionMedicamento;
    private MedicinaNaturalTradicional_estadisticas medicinaNaturalTradicional;
    private Date fechaSuspension;
    private Boolean cumpEnfermera;
    private Integer valorUnidadTiempo;
    private Long cid;
    private Boolean eliminado;
    private String descripcion;
    private Integer cantidadDias;

    public IndicacionMedicaTratamiento_estadisticas() {
    }

    public IndicacionMedicaTratamiento_estadisticas(long id, String descripcion) {
        this.id = id;
        this.descripcion = descripcion;
    }

    public IndicacionMedicaTratamiento_estadisticas(long id,
                                                    TratamientoMedico_estadisticas tratamientoMedico,
                                                    UnidadTiempo_estadisticas unidadTiempo,
                                                    Long indicacionMedica,
                                                    Long viaAdministracionMedicamento,
                                                    MedicinaNaturalTradicional_estadisticas medicinaNaturalTradicional,
                                                    Date fechaSuspension, Boolean cumpEnfermera,
                                                    Integer valorUnidadTiempo, Long cid, Boolean eliminado,
                                                    String descripcion, Integer cantidadDias) {
        this.id = id;
        this.tratamientoMedico = tratamientoMedico;
        this.unidadTiempo = unidadTiempo;
        this.indicacionMedica = indicacionMedica;
        this.viaAdministracionMedicamento = viaAdministracionMedicamento;
        this.medicinaNaturalTradicional = medicinaNaturalTradicional;
        this.fechaSuspension = fechaSuspension;
        this.cumpEnfermera = cumpEnfermera;
        this.valorUnidadTiempo = valorUnidadTiempo;
        this.cid = cid;
        this.eliminado = eliminado;
        this.descripcion = descripcion;
        this.cantidadDias = cantidadDias;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @Version
    @Column(name = "version")
    public Integer getVersion() {
        return this.version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_tratamiento_medico")
    public TratamientoMedico_estadisticas getTratamientoMedico() {
        return this.tratamientoMedico;
    }

    public void setTratamientoMedico(
            TratamientoMedico_estadisticas tratamientoMedico) {
        this.tratamientoMedico = tratamientoMedico;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_unidad_tiempo")
    public UnidadTiempo_estadisticas getUnidadTiempo() {
        return this.unidadTiempo;
    }

    public void setUnidadTiempo(UnidadTiempo_estadisticas unidadTiempo) {
        this.unidadTiempo = unidadTiempo;
    }


    @Column(name = "id_indicacion_medica", nullable = false)
    public Long getIndicacionMedica() {
        return this.indicacionMedica;
    }

    public void setIndicacionMedica(Long indicacionMedica) {
        this.indicacionMedica = indicacionMedica;
    }

    @Column(name = "id_via", nullable = false)
    public Long getViaAdministracionMedicamento() {
        return this.viaAdministracionMedicamento;
    }

    public void setViaAdministracionMedicamento(
            Long viaAdministracionMedicamento) {
        this.viaAdministracionMedicamento = viaAdministracionMedicamento;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_mnt")
    public MedicinaNaturalTradicional_estadisticas getMedicinaNaturalTradicional() {
        return this.medicinaNaturalTradicional;
    }

    public void setMedicinaNaturalTradicional(
            MedicinaNaturalTradicional_estadisticas medicinaNaturalTradicional) {
        this.medicinaNaturalTradicional = medicinaNaturalTradicional;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "fecha_suspension", length = 13)
    public Date getFechaSuspension() {
        return this.fechaSuspension;
    }

    public void setFechaSuspension(Date fechaSuspension) {
        this.fechaSuspension = fechaSuspension;
    }

    @Column(name = "cump_enfermera")
    public Boolean getCumpEnfermera() {
        return this.cumpEnfermera;
    }

    public void setCumpEnfermera(Boolean cumpEnfermera) {
        this.cumpEnfermera = cumpEnfermera;
    }

    @Column(name = "valor_unidad_tiempo")
    public Integer getValorUnidadTiempo() {
        return this.valorUnidadTiempo;
    }

    public void setValorUnidadTiempo(Integer valorUnidadTiempo) {
        this.valorUnidadTiempo = valorUnidadTiempo;
    }

    @Column(name = "cid")
    public Long getCid() {
        return this.cid;
    }

    public void setCid(Long cid) {
        this.cid = cid;
    }

    @Column(name = "eliminado")
    public Boolean getEliminado() {
        return this.eliminado;
    }

    public void setEliminado(Boolean eliminado) {
        this.eliminado = eliminado;
    }

    @Column(name = "descripcion", nullable = false)

    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        if (descripcion != null)
            descripcion = descripcion.trim();
        this.descripcion = descripcion;
    }

    @Column(name = "cantidad_dias")
    public Integer getCantidadDias() {
        return this.cantidadDias;
    }

    public void setCantidadDias(Integer cantidadDias) {
        this.cantidadDias = cantidadDias;
    }

}
