package cu.uci.cesim.hce_back.estadisticas.model.entity.auto;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

import javax.persistence.*;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

// Generated Apr 18, 2012 10:46:48 AM by Hibernate Tools 3.4.0.CR1

/**
 * InfecMonitoreo generated by hbm2java
 */
@Entity
@Table(name = "infec_monitoreo", schema = "epidemiologia")
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "id")
public class InfecMonitoreo_estadisticas implements java.io.Serializable {

    private long id;
    private Integer version;
    private Cama_estadisticas cama;
    private Long cid;
    private Boolean eliminado;
    private Boolean hayInfeccionIngreso;
    private Date fechaEgreso;
    private Long idTipoIngreso;
    private String observaciones;
    private String tipoInfeccion;
    private Long idFormulario;
    private String sintomas;
    private String cultivo;
    private String antibioticos;
    private String otros;
    private String factoresEndogenos;
    private String factoresExogenos;
    private Boolean tieneInfeccion;
    private Set<InfecFicha_estadisticas> infecFichas = new HashSet<InfecFicha_estadisticas>(
            0);

    public InfecMonitoreo_estadisticas() {
    }

    public InfecMonitoreo_estadisticas(long id) {
        this.id = id;
    }

    public InfecMonitoreo_estadisticas(long id, Cama_estadisticas cama,
                                       Long cid, Boolean eliminado, Boolean hayInfeccionIngreso,
                                       Date fechaEgreso, Long idTipoIngreso, String observaciones,
                                       String tipoInfeccion, Long idFormulario, String sintomas,
                                       String cultivo, String antibioticos, String otros,
                                       String factoresEndogenos, String factoresExogenos,
                                       Boolean tieneInfeccion, Set<InfecFicha_estadisticas> infecFichas) {
        this.id = id;
        this.cama = cama;
        this.cid = cid;
        this.eliminado = eliminado;
        this.hayInfeccionIngreso = hayInfeccionIngreso;
        this.fechaEgreso = fechaEgreso;
        this.idTipoIngreso = idTipoIngreso;
        this.observaciones = observaciones;
        this.tipoInfeccion = tipoInfeccion;
        this.idFormulario = idFormulario;
        this.sintomas = sintomas;
        this.cultivo = cultivo;
        this.antibioticos = antibioticos;
        this.otros = otros;
        this.factoresEndogenos = factoresEndogenos;
        this.factoresExogenos = factoresExogenos;
        this.tieneInfeccion = tieneInfeccion;
        this.infecFichas = infecFichas;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @Version
    @Column(name = "version")
    public Integer getVersion() {
        return this.version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_cama")
    public Cama_estadisticas getCama() {
        return this.cama;
    }

    public void setCama(Cama_estadisticas cama) {
        this.cama = cama;
    }

    @Column(name = "cid")
    public Long getCid() {
        return this.cid;
    }

    public void setCid(Long cid) {
        this.cid = cid;
    }

    @Column(name = "eliminado")
    public Boolean getEliminado() {
        return this.eliminado;
    }

    public void setEliminado(Boolean eliminado) {
        this.eliminado = eliminado;
    }

    @Column(name = "hay_infeccion_ingreso")
    public Boolean getHayInfeccionIngreso() {
        return this.hayInfeccionIngreso;
    }

    public void setHayInfeccionIngreso(Boolean hayInfeccionIngreso) {
        this.hayInfeccionIngreso = hayInfeccionIngreso;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "fecha_egreso", length = 13)
    public Date getFechaEgreso() {
        return this.fechaEgreso;
    }

    public void setFechaEgreso(Date fechaEgreso) {
        this.fechaEgreso = fechaEgreso;
    }

    @Column(name = "id_tipo_ingreso")
    public Long getIdTipoIngreso() {
        return this.idTipoIngreso;
    }

    public void setIdTipoIngreso(Long idTipoIngreso) {
        this.idTipoIngreso = idTipoIngreso;
    }

    @Column(name = "observaciones")
    public String getObservaciones() {
        return this.observaciones;
    }

    public void setObservaciones(String observaciones) {
        if (observaciones != null)
            observaciones = observaciones.trim();
        this.observaciones = observaciones;
    }

    @Column(name = "tipo_infeccion")
    public String getTipoInfeccion() {
        return this.tipoInfeccion;
    }

    public void setTipoInfeccion(String tipoInfeccion) {
        if (tipoInfeccion != null)
            tipoInfeccion = tipoInfeccion.trim();
        this.tipoInfeccion = tipoInfeccion;
    }

    @Column(name = "id_formulario")
    public Long getIdFormulario() {
        return this.idFormulario;
    }

    public void setIdFormulario(Long idFormulario) {
        this.idFormulario = idFormulario;
    }

    @Column(name = "sintomas")
    public String getSintomas() {
        return this.sintomas;
    }

    public void setSintomas(String sintomas) {
        if (sintomas != null)
            sintomas = sintomas.trim();
        this.sintomas = sintomas;
    }

    @Column(name = "cultivo")
    public String getCultivo() {
        return this.cultivo;
    }

    public void setCultivo(String cultivo) {
        if (cultivo != null)
            cultivo = cultivo.trim();
        this.cultivo = cultivo;
    }

    @Column(name = "antibioticos")
    public String getAntibioticos() {
        return this.antibioticos;
    }

    public void setAntibioticos(String antibioticos) {
        if (antibioticos != null)
            antibioticos = antibioticos.trim();
        this.antibioticos = antibioticos;
    }

    @Column(name = "otros")
    public String getOtros() {
        return this.otros;
    }

    public void setOtros(String otros) {
        if (otros != null)
            otros = otros.trim();
        this.otros = otros;
    }

    @Column(name = "factores_endogenos")
    public String getFactoresEndogenos() {
        return this.factoresEndogenos;
    }

    public void setFactoresEndogenos(String factoresEndogenos) {
        if (factoresEndogenos != null)
            factoresEndogenos = factoresEndogenos.trim();
        this.factoresEndogenos = factoresEndogenos;
    }

    @Column(name = "factores_exogenos")
    public String getFactoresExogenos() {
        return this.factoresExogenos;
    }

    public void setFactoresExogenos(String factoresExogenos) {
        if (factoresExogenos != null)
            factoresExogenos = factoresExogenos.trim();
        this.factoresExogenos = factoresExogenos;
    }

    @Column(name = "tiene_infeccion")
    public Boolean getTieneInfeccion() {
        return this.tieneInfeccion;
    }

    public void setTieneInfeccion(Boolean tieneInfeccion) {
        this.tieneInfeccion = tieneInfeccion;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "infecMonitoreo")
    public Set<InfecFicha_estadisticas> getInfecFichas() {
        return this.infecFichas;
    }

    public void setInfecFichas(Set<InfecFicha_estadisticas> infecFichas) {
        this.infecFichas = infecFichas;
    }

}
