package cu.uci.cesim.hce_back.estadisticas.model.entity.auto;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

import javax.persistence.*;
import java.util.Date;

// Generated Apr 18, 2012 10:46:48 AM by Hibernate Tools 3.4.0.CR1


/**
 * Inmunizaciones generated by hbm2java
 */
@Entity
@Table(name = "inmunizaciones", schema = "hc_local")
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "id")
public class Inmunizaciones_estadisticas implements java.io.Serializable {

    private long id;
    private Integer version;
    private HojaFrontal_estadisticas hojaFrontal;
    private long idVacuna;
    private Date fechaRecienNacido;
    private Date fechaPrimeraDosis;
    private Date fechaSegundaDosis;
    private Date fechaTerceraDosis;
    private Date fechaCuartaDosis;
    private Date fechaPrimerRefuerzo;
    private Date fechaSegundoRefuerzo;
    private Date fechaTercerRefuerzo;
    private Date fechaCuartoRefuerzo;
    private Boolean eliminado;
    private Long cid;

    public Inmunizaciones_estadisticas() {
    }

    public Inmunizaciones_estadisticas(long id,
                                       HojaFrontal_estadisticas hojaFrontal, long idVacuna) {
        this.id = id;
        this.hojaFrontal = hojaFrontal;
        this.idVacuna = idVacuna;
    }

    public Inmunizaciones_estadisticas(long id,
                                       HojaFrontal_estadisticas hojaFrontal, long idVacuna,
                                       Date fechaRecienNacido, Date fechaPrimeraDosis,
                                       Date fechaSegundaDosis, Date fechaTerceraDosis,
                                       Date fechaCuartaDosis, Date fechaPrimerRefuerzo,
                                       Date fechaSegundoRefuerzo, Date fechaTercerRefuerzo,
                                       Date fechaCuartoRefuerzo, Boolean eliminado, Long cid) {
        this.id = id;
        this.hojaFrontal = hojaFrontal;
        this.idVacuna = idVacuna;
        this.fechaRecienNacido = fechaRecienNacido;
        this.fechaPrimeraDosis = fechaPrimeraDosis;
        this.fechaSegundaDosis = fechaSegundaDosis;
        this.fechaTerceraDosis = fechaTerceraDosis;
        this.fechaCuartaDosis = fechaCuartaDosis;
        this.fechaPrimerRefuerzo = fechaPrimerRefuerzo;
        this.fechaSegundoRefuerzo = fechaSegundoRefuerzo;
        this.fechaTercerRefuerzo = fechaTercerRefuerzo;
        this.fechaCuartoRefuerzo = fechaCuartoRefuerzo;
        this.eliminado = eliminado;
        this.cid = cid;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @Version
    @Column(name = "version")
    public Integer getVersion() {
        return this.version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_hoja_frontal", nullable = false)

    public HojaFrontal_estadisticas getHojaFrontal() {
        return this.hojaFrontal;
    }

    public void setHojaFrontal(HojaFrontal_estadisticas hojaFrontal) {
        this.hojaFrontal = hojaFrontal;
    }

    @Column(name = "id_vacuna", nullable = false)

    public long getIdVacuna() {
        return this.idVacuna;
    }

    public void setIdVacuna(long idVacuna) {
        this.idVacuna = idVacuna;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "fecha_recien_nacido", length = 13)
    public Date getFechaRecienNacido() {
        return this.fechaRecienNacido;
    }

    public void setFechaRecienNacido(Date fechaRecienNacido) {
        this.fechaRecienNacido = fechaRecienNacido;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "fecha_primera_dosis", length = 13)
    public Date getFechaPrimeraDosis() {
        return this.fechaPrimeraDosis;
    }

    public void setFechaPrimeraDosis(Date fechaPrimeraDosis) {
        this.fechaPrimeraDosis = fechaPrimeraDosis;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "fecha_segunda_dosis", length = 13)
    public Date getFechaSegundaDosis() {
        return this.fechaSegundaDosis;
    }

    public void setFechaSegundaDosis(Date fechaSegundaDosis) {
        this.fechaSegundaDosis = fechaSegundaDosis;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "fecha_tercera_dosis", length = 13)
    public Date getFechaTerceraDosis() {
        return this.fechaTerceraDosis;
    }

    public void setFechaTerceraDosis(Date fechaTerceraDosis) {
        this.fechaTerceraDosis = fechaTerceraDosis;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "fecha_cuarta_dosis", length = 13)
    public Date getFechaCuartaDosis() {
        return this.fechaCuartaDosis;
    }

    public void setFechaCuartaDosis(Date fechaCuartaDosis) {
        this.fechaCuartaDosis = fechaCuartaDosis;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "fecha_primer_refuerzo", length = 13)
    public Date getFechaPrimerRefuerzo() {
        return this.fechaPrimerRefuerzo;
    }

    public void setFechaPrimerRefuerzo(Date fechaPrimerRefuerzo) {
        this.fechaPrimerRefuerzo = fechaPrimerRefuerzo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "fecha_segundo_refuerzo", length = 13)
    public Date getFechaSegundoRefuerzo() {
        return this.fechaSegundoRefuerzo;
    }

    public void setFechaSegundoRefuerzo(Date fechaSegundoRefuerzo) {
        this.fechaSegundoRefuerzo = fechaSegundoRefuerzo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "fecha_tercer_refuerzo", length = 13)
    public Date getFechaTercerRefuerzo() {
        return this.fechaTercerRefuerzo;
    }

    public void setFechaTercerRefuerzo(Date fechaTercerRefuerzo) {
        this.fechaTercerRefuerzo = fechaTercerRefuerzo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "fecha_cuarto_refuerzo", length = 13)
    public Date getFechaCuartoRefuerzo() {
        return this.fechaCuartoRefuerzo;
    }

    public void setFechaCuartoRefuerzo(Date fechaCuartoRefuerzo) {
        this.fechaCuartoRefuerzo = fechaCuartoRefuerzo;
    }

    @Column(name = "eliminado")
    public Boolean getEliminado() {
        return this.eliminado;
    }

    public void setEliminado(Boolean eliminado) {
        this.eliminado = eliminado;
    }

    @Column(name = "cid")
    public Long getCid() {
        return this.cid;
    }

    public void setCid(Long cid) {
        this.cid = cid;
    }

}
