package cu.uci.cesim.hce_back.estadisticas.model.entity.auto;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

// Generated Apr 18, 2012 10:46:48 AM by Hibernate Tools 3.4.0.CR1


/**
 * Laboratorio generated by hbm2java
 */
@Entity
@Table(name = "laboratorio", schema = "bancosangre")
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "id")
public class Laboratorio_estadisticas implements java.io.Serializable {

    private long id;
    private Integer version;
    private Funcionalidad_estadisticas funcionalidad;
    private String nombre;
    private String descripcion;
    private Boolean eliminado;
    private Long cid;
    private long idAlmacen;
    private Set<MovimientoSanguineo_estadisticas> movimientoSanguineos = new HashSet<MovimientoSanguineo_estadisticas>(
            0);

    public Laboratorio_estadisticas() {
    }

    public Laboratorio_estadisticas(long id, String nombre, String descripcion,
                                    long idAlmacen) {
        this.id = id;
        this.nombre = nombre;
        this.descripcion = descripcion;
        this.idAlmacen = idAlmacen;
    }

    public Laboratorio_estadisticas(long id,
                                    Funcionalidad_estadisticas funcionalidad, String nombre,
                                    String descripcion, Boolean eliminado, Long cid, long idAlmacen,
                                    Set<MovimientoSanguineo_estadisticas> movimientoSanguineos) {
        this.id = id;
        this.funcionalidad = funcionalidad;
        this.nombre = nombre;
        this.descripcion = descripcion;
        this.eliminado = eliminado;
        this.cid = cid;
        this.idAlmacen = idAlmacen;
        this.movimientoSanguineos = movimientoSanguineos;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @Version
    @Column(name = "version")
    public Integer getVersion() {
        return this.version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_entidad")
    public Funcionalidad_estadisticas getFuncionalidad() {
        return this.funcionalidad;
    }

    public void setFuncionalidad(Funcionalidad_estadisticas funcionalidad) {
        this.funcionalidad = funcionalidad;
    }

    @Column(name = "nombre", nullable = false)

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        if (nombre != null)
            nombre = nombre.trim();
        this.nombre = nombre;
    }

    @Column(name = "descripcion", nullable = false)

    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        if (descripcion != null)
            descripcion = descripcion.trim();
        this.descripcion = descripcion;
    }

    @Column(name = "eliminado")
    public Boolean getEliminado() {
        return this.eliminado;
    }

    public void setEliminado(Boolean eliminado) {
        this.eliminado = eliminado;
    }

    @Column(name = "cid")
    public Long getCid() {
        return this.cid;
    }

    public void setCid(Long cid) {
        this.cid = cid;
    }

    @Column(name = "id_almacen", nullable = false)

    public long getIdAlmacen() {
        return this.idAlmacen;
    }

    public void setIdAlmacen(long idAlmacen) {
        this.idAlmacen = idAlmacen;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "laboratorio")
    public Set<MovimientoSanguineo_estadisticas> getMovimientoSanguineos() {
        return this.movimientoSanguineos;
    }

    public void setMovimientoSanguineos(
            Set<MovimientoSanguineo_estadisticas> movimientoSanguineos) {
        this.movimientoSanguineos = movimientoSanguineos;
    }

}
