package cu.uci.cesim.hce_back.estadisticas.model.entity.auto;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

// Generated Apr 18, 2012 10:46:48 AM by Hibernate Tools 3.4.0.CR1


/**
 * Localidad generated by hbm2java
 */
@Entity
@Table(name = "localidad", schema = "nomencladores")
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "id")
public class Localidad_estadisticas implements java.io.Serializable {

    private long id;
    private Integer version;
    private Municipio_estadisticas municipio;
    private String valor;
    private Boolean eliminado;
    private Long cid;
    private String codigo;
    private Set<Entidad_estadisticas> entidads = new HashSet<Entidad_estadisticas>(
            0);
    private Set<Direccion_estadisticas> direccions = new HashSet<Direccion_estadisticas>(
            0);
    private Set<DistritoSanitario_estadisticas> distritoSanitarios = new HashSet<DistritoSanitario_estadisticas>(
            0);

    public Localidad_estadisticas() {
    }

    public Localidad_estadisticas(long id, Municipio_estadisticas municipio,
                                  String valor) {
        this.id = id;
        this.municipio = municipio;
        this.valor = valor;
    }

    public Localidad_estadisticas(long id, Municipio_estadisticas municipio,
                                  String valor, Boolean eliminado, Long cid, String codigo,
                                  Set<Entidad_estadisticas> entidads,
                                  Set<Direccion_estadisticas> direccions,
                                  Set<DistritoSanitario_estadisticas> distritoSanitarios) {
        this.id = id;
        this.municipio = municipio;
        this.valor = valor;
        this.eliminado = eliminado;
        this.cid = cid;
        this.codigo = codigo;
        this.entidads = entidads;
        this.direccions = direccions;
        this.distritoSanitarios = distritoSanitarios;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @Version
    @Column(name = "version")
    public Integer getVersion() {
        return this.version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_municipio", nullable = false)

    public Municipio_estadisticas getMunicipio() {
        return this.municipio;
    }

    public void setMunicipio(Municipio_estadisticas municipio) {
        this.municipio = municipio;
    }

    @Column(name = "valor", nullable = false)

    public String getValor() {
        return this.valor;
    }

    public void setValor(String valor) {
        if (valor != null)
            valor = valor.trim();
        this.valor = valor;
    }

    @Column(name = "eliminado")
    public Boolean getEliminado() {
        return this.eliminado;
    }

    public void setEliminado(Boolean eliminado) {
        this.eliminado = eliminado;
    }

    @Column(name = "cid")
    public Long getCid() {
        return this.cid;
    }

    public void setCid(Long cid) {
        this.cid = cid;
    }

    @Column(name = "codigo")
    public String getCodigo() {
        return this.codigo;
    }

    public void setCodigo(String codigo) {
        if (codigo != null)
            codigo = codigo.trim();
        this.codigo = codigo;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "localidad")
    public Set<Entidad_estadisticas> getEntidads() {
        return this.entidads;
    }

    public void setEntidads(Set<Entidad_estadisticas> entidads) {
        this.entidads = entidads;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "localidad")
    public Set<Direccion_estadisticas> getDireccions() {
        return this.direccions;
    }

    public void setDireccions(Set<Direccion_estadisticas> direccions) {
        this.direccions = direccions;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "localidad")
    public Set<DistritoSanitario_estadisticas> getDistritoSanitarios() {
        return this.distritoSanitarios;
    }

    public void setDistritoSanitarios(
            Set<DistritoSanitario_estadisticas> distritoSanitarios) {
        this.distritoSanitarios = distritoSanitarios;
    }

}
