package cu.uci.cesim.hce_back.estadisticas.model.entity.auto;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

import javax.persistence.*;
import java.util.Date;

// Generated Apr 18, 2012 10:46:48 AM by Hibernate Tools 3.4.0.CR1


/**
 * MovimientoSanguineo generated by hbm2java
 */
@Entity
@Table(name = "movimiento_sanguineo", schema = "bancosangre")
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "id")
public class MovimientoSanguineo_estadisticas implements java.io.Serializable {

    private long id;
    private int version;
    private BolsaSangre_estadisticas bolsaSangre;
    private Laboratorio_estadisticas laboratorio;
    private DesechoSangre_estadisticas desechoSangre;
    private EntregaSangre_estadisticas entregaSangre;
    private Date fecha;
    private Date hora;
    private boolean entrada;
    private Long idRegistroDonacion;
    private Long idSeparacion;
    private Long idIntercambio;
    private Long idEnvio;
    private Boolean eliminado;
    private long cid;
    private Long idDevolucion;

    public MovimientoSanguineo_estadisticas() {
    }

    public MovimientoSanguineo_estadisticas(long id,
                                            BolsaSangre_estadisticas bolsaSangre,
                                            Laboratorio_estadisticas laboratorio, Date fecha, Date hora,
                                            boolean entrada, long cid) {
        this.id = id;
        this.bolsaSangre = bolsaSangre;
        this.laboratorio = laboratorio;
        this.fecha = fecha;
        this.hora = hora;
        this.entrada = entrada;
        this.cid = cid;
    }

    public MovimientoSanguineo_estadisticas(long id,
                                            BolsaSangre_estadisticas bolsaSangre,
                                            Laboratorio_estadisticas laboratorio,
                                            DesechoSangre_estadisticas desechoSangre,
                                            EntregaSangre_estadisticas entregaSangre, Date fecha, Date hora,
                                            boolean entrada, Long idRegistroDonacion, Long idSeparacion,
                                            Long idIntercambio, Long idEnvio, Boolean eliminado, long cid,
                                            Long idDevolucion) {
        this.id = id;
        this.bolsaSangre = bolsaSangre;
        this.laboratorio = laboratorio;
        this.desechoSangre = desechoSangre;
        this.entregaSangre = entregaSangre;
        this.fecha = fecha;
        this.hora = hora;
        this.entrada = entrada;
        this.idRegistroDonacion = idRegistroDonacion;
        this.idSeparacion = idSeparacion;
        this.idIntercambio = idIntercambio;
        this.idEnvio = idEnvio;
        this.eliminado = eliminado;
        this.cid = cid;
        this.idDevolucion = idDevolucion;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @Version
    @Column(name = "version", nullable = false)

    public int getVersion() {
        return this.version;
    }

    public void setVersion(int version) {
        this.version = version;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_bolsa", nullable = false)

    public BolsaSangre_estadisticas getBolsaSangre() {
        return this.bolsaSangre;
    }

    public void setBolsaSangre(BolsaSangre_estadisticas bolsaSangre) {
        this.bolsaSangre = bolsaSangre;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_laboratorio", nullable = false)

    public Laboratorio_estadisticas getLaboratorio() {
        return this.laboratorio;
    }

    public void setLaboratorio(Laboratorio_estadisticas laboratorio) {
        this.laboratorio = laboratorio;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_desecho")
    public DesechoSangre_estadisticas getDesechoSangre() {
        return this.desechoSangre;
    }

    public void setDesechoSangre(DesechoSangre_estadisticas desechoSangre) {
        this.desechoSangre = desechoSangre;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_entrega")
    public EntregaSangre_estadisticas getEntregaSangre() {
        return this.entregaSangre;
    }

    public void setEntregaSangre(EntregaSangre_estadisticas entregaSangre) {
        this.entregaSangre = entregaSangre;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "fecha", nullable = false, length = 13)

    public Date getFecha() {
        return this.fecha;
    }

    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    @Temporal(TemporalType.TIME)
    @Column(name = "hora", nullable = false, length = 8)

    public Date getHora() {
        return this.hora;
    }

    public void setHora(Date hora) {
        this.hora = hora;
    }

    @Column(name = "entrada", nullable = false)

    public boolean isEntrada() {
        return this.entrada;
    }

    public void setEntrada(boolean entrada) {
        this.entrada = entrada;
    }

    @Column(name = "id_registro_donacion")
    public Long getIdRegistroDonacion() {
        return this.idRegistroDonacion;
    }

    public void setIdRegistroDonacion(Long idRegistroDonacion) {
        this.idRegistroDonacion = idRegistroDonacion;
    }

    @Column(name = "id_separacion")
    public Long getIdSeparacion() {
        return this.idSeparacion;
    }

    public void setIdSeparacion(Long idSeparacion) {
        this.idSeparacion = idSeparacion;
    }

    @Column(name = "id_intercambio")
    public Long getIdIntercambio() {
        return this.idIntercambio;
    }

    public void setIdIntercambio(Long idIntercambio) {
        this.idIntercambio = idIntercambio;
    }

    @Column(name = "id_envio")
    public Long getIdEnvio() {
        return this.idEnvio;
    }

    public void setIdEnvio(Long idEnvio) {
        this.idEnvio = idEnvio;
    }

    @Column(name = "eliminado")
    public Boolean getEliminado() {
        return this.eliminado;
    }

    public void setEliminado(Boolean eliminado) {
        this.eliminado = eliminado;
    }

    @Column(name = "cid", nullable = false)

    public long getCid() {
        return this.cid;
    }

    public void setCid(long cid) {
        this.cid = cid;
    }

    @Column(name = "id_devolucion")
    public Long getIdDevolucion() {
        return this.idDevolucion;
    }

    public void setIdDevolucion(Long idDevolucion) {
        this.idDevolucion = idDevolucion;
    }

}
