package cu.uci.cesim.hce_back.estadisticas.model.entity.auto;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

// Generated Jan 3, 2013 4:54:45 PM by Hibernate Tools 3.4.0.CR1


/**
 * Parentesco generated by hbm2java
 */
@Entity
@Table(name = "parentesco", schema = "nomencladores", uniqueConstraints = @UniqueConstraint(columnNames = "codigo_sap"))
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "id")
public class Parentesco_estadisticas implements java.io.Serializable {

    private long id;
    private Integer version;
    private Boolean eliminado;
    private Long cid;
    private String codigo;
    private String valor;
    private String codigoSap;
    private Set<TitularBeneficiario_estadisticas> titularBeneficiarios = new HashSet<TitularBeneficiario_estadisticas>(
            0);
    private Set<Antecedentes_estadisticas> antecedenteses = new HashSet<Antecedentes_estadisticas>(
            0);

    public Parentesco_estadisticas() {
    }

    public Parentesco_estadisticas(long id, String valor) {
        this.id = id;
        this.valor = valor;
    }

    public Parentesco_estadisticas(long id, Boolean eliminado, Long cid,
                                   String codigo, String valor, String codigoSap,
                                   Set<TitularBeneficiario_estadisticas> titularBeneficiarios,
                                   Set<Antecedentes_estadisticas> antecedenteses) {
        this.id = id;
        this.eliminado = eliminado;
        this.cid = cid;
        this.codigo = codigo;
        this.valor = valor;
        this.codigoSap = codigoSap;
        this.titularBeneficiarios = titularBeneficiarios;
        this.antecedenteses = antecedenteses;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @Version
    @Column(name = "version")
    public Integer getVersion() {
        return this.version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    @Column(name = "eliminado")
    public Boolean getEliminado() {
        return this.eliminado;
    }

    public void setEliminado(Boolean eliminado) {
        this.eliminado = eliminado;
    }

    @Column(name = "cid")
    public Long getCid() {
        return this.cid;
    }

    public void setCid(Long cid) {
        this.cid = cid;
    }

    @Column(name = "codigo")
    public String getCodigo() {
        return this.codigo;
    }

    public void setCodigo(String codigo) {
        if (codigo != null)
            codigo = codigo.trim();
        this.codigo = codigo;
    }

    @Column(name = "valor", nullable = false)

    public String getValor() {
        return this.valor;
    }

    public void setValor(String valor) {
        if (valor != null)
            valor = valor.trim();
        this.valor = valor;
    }

    @Column(name = "codigo_sap", unique = true)
    public String getCodigoSap() {
        return this.codigoSap;
    }

    public void setCodigoSap(String codigoSap) {
        if (codigoSap != null)
            codigoSap = codigoSap.trim();
        this.codigoSap = codigoSap;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "parentesco")
    public Set<TitularBeneficiario_estadisticas> getTitularBeneficiarios() {
        return this.titularBeneficiarios;
    }

    public void setTitularBeneficiarios(
            Set<TitularBeneficiario_estadisticas> titularBeneficiarios) {
        this.titularBeneficiarios = titularBeneficiarios;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "parentesco")
    public Set<Antecedentes_estadisticas> getAntecedenteses() {
        return this.antecedenteses;
    }

    public void setAntecedenteses(Set<Antecedentes_estadisticas> antecedenteses) {
        this.antecedenteses = antecedenteses;
    }

}
