package cu.uci.cesim.hce_back.estadisticas.model.entity.auto;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

import javax.persistence.*;

// Generated Apr 18, 2012 10:46:48 AM by Hibernate Tools 3.4.0.CR1


/**
 * PlanificacionMedico generated by hbm2java
 */
@Entity
@Table(name = "planificacion_medico", schema = "publico")
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "id")
public class PlanificacionMedico_estadisticas implements java.io.Serializable {

    private long id;
    private Integer version;
    private HorarioCita_estadisticas horarioCita;
    private EspecialidadInEntidad_estadisticas especialidadInEntidad;
    private Medico_estadisticas medico;
    private Boolean eliminado;
    private Long cid;

    public PlanificacionMedico_estadisticas() {
    }

    public PlanificacionMedico_estadisticas(long id,
                                            HorarioCita_estadisticas horarioCita,
                                            EspecialidadInEntidad_estadisticas especialidadInEntidad,
                                            Medico_estadisticas medico) {
        this.id = id;
        this.horarioCita = horarioCita;
        this.especialidadInEntidad = especialidadInEntidad;
        this.medico = medico;
    }

    public PlanificacionMedico_estadisticas(long id,
                                            HorarioCita_estadisticas horarioCita,
                                            EspecialidadInEntidad_estadisticas especialidadInEntidad,
                                            Medico_estadisticas medico, Boolean eliminado, Long cid) {
        this.id = id;
        this.horarioCita = horarioCita;
        this.especialidadInEntidad = especialidadInEntidad;
        this.medico = medico;
        this.eliminado = eliminado;
        this.cid = cid;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @Version
    @Column(name = "version")
    public Integer getVersion() {
        return this.version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_horario_cita", nullable = false)

    public HorarioCita_estadisticas getHorarioCita() {
        return this.horarioCita;
    }

    public void setHorarioCita(HorarioCita_estadisticas horarioCita) {
        this.horarioCita = horarioCita;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_especialidad", nullable = false)

    public EspecialidadInEntidad_estadisticas getEspecialidadInEntidad() {
        return this.especialidadInEntidad;
    }

    public void setEspecialidadInEntidad(
            EspecialidadInEntidad_estadisticas especialidadInEntidad) {
        this.especialidadInEntidad = especialidadInEntidad;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_medico", nullable = false)

    public Medico_estadisticas getMedico() {
        return this.medico;
    }

    public void setMedico(Medico_estadisticas medico) {
        this.medico = medico;
    }

    @Column(name = "eliminado")
    public Boolean getEliminado() {
        return this.eliminado;
    }

    public void setEliminado(Boolean eliminado) {
        this.eliminado = eliminado;
    }

    @Column(name = "cid")
    public Long getCid() {
        return this.cid;
    }

    public void setCid(Long cid) {
        this.cid = cid;
    }

}
