package cu.uci.cesim.hce_back.estadisticas.model.entity.auto;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

import javax.persistence.*;
import java.util.Date;

// Generated Apr 18, 2012 10:46:48 AM by Hibernate Tools 3.4.0.CR1


/**
 * PoblacionAreaInfluencia generated by hbm2java
 */
@Entity
@Table(name = "poblacion_area_influencia", schema = "comun")
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "id")
public class PoblacionAreaInfluencia_estadisticas implements
        java.io.Serializable {

    private long id;
    private Integer version;
    private Entidad_estadisticas entidad;
    private Integer valor;
    private Boolean eliminado;
    private Long cid;
    private Date fecha;
    private Integer valorOtros;

    public PoblacionAreaInfluencia_estadisticas() {
    }

    public PoblacionAreaInfluencia_estadisticas(long id,
                                                Entidad_estadisticas entidad) {
        this.id = id;
        this.entidad = entidad;
    }

    public PoblacionAreaInfluencia_estadisticas(long id,
                                                Entidad_estadisticas entidad, Integer valor, Boolean eliminado,
                                                Long cid, Date fecha, Integer valorOtros) {
        this.id = id;
        this.entidad = entidad;
        this.valor = valor;
        this.eliminado = eliminado;
        this.cid = cid;
        this.fecha = fecha;
        this.valorOtros = valorOtros;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @Version
    @Column(name = "version")
    public Integer getVersion() {
        return this.version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_entidad", nullable = false)

    public Entidad_estadisticas getEntidad() {
        return this.entidad;
    }

    public void setEntidad(Entidad_estadisticas entidad) {
        this.entidad = entidad;
    }

    @Column(name = "valor")
    public Integer getValor() {
        return this.valor;
    }

    public void setValor(Integer valor) {
        this.valor = valor;
    }

    @Column(name = "eliminado")
    public Boolean getEliminado() {
        return this.eliminado;
    }

    public void setEliminado(Boolean eliminado) {
        this.eliminado = eliminado;
    }

    @Column(name = "cid")
    public Long getCid() {
        return this.cid;
    }

    public void setCid(Long cid) {
        this.cid = cid;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "fecha", length = 13)
    public Date getFecha() {
        return this.fecha;
    }

    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    @Column(name = "valor_otros")
    public Integer getValorOtros() {
        return this.valorOtros;
    }

    public void setValorOtros(Integer valorOtros) {
        this.valorOtros = valorOtros;
    }

}
