package cu.uci.cesim.hce_back.estadisticas.model.entity.auto;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

import javax.persistence.*;

// Generated Apr 18, 2012 10:46:48 AM by Hibernate Tools 3.4.0.CR1

/**
 * PoblacionCalcSource generated by hbm2java
 */
@Entity
@Table(name = "poblacion_calc_source", schema = "estadisticas")
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "id")
public class PoblacionCalcSource_estadisticas implements java.io.Serializable {

    private long id;
    private PoblacionStatus_estadisticas poblacionStatus;
    private Status_estadisticas status;
    private Integer anno;
    private Double porciento;

    public PoblacionCalcSource_estadisticas() {
    }

    public PoblacionCalcSource_estadisticas(long id) {
        this.id = id;
    }

    public PoblacionCalcSource_estadisticas(long id,
                                            PoblacionStatus_estadisticas poblacionStatus,
                                            Status_estadisticas status, Integer anno,
                                            Double porciento) {
        this.id = id;
        this.poblacionStatus = poblacionStatus;
        this.status = status;
        this.anno = anno;
        this.porciento = porciento;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_poblacion_status")
    public PoblacionStatus_estadisticas getPoblacionStatus() {
        return this.poblacionStatus;
    }

    public void setPoblacionStatus(PoblacionStatus_estadisticas poblacionStatus) {
        this.poblacionStatus = poblacionStatus;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_status")
    public Status_estadisticas getStatus() {
        return this.status;
    }

    public void setStatus(Status_estadisticas status) {
        this.status = status;
    }

    @Column(name = "anno")
    public Integer getAnno() {
        return this.anno;
    }

    public void setAnno(Integer anno) {
        this.anno = anno;
    }

    @Column(name = "porciento", precision = 17, scale = 17)
    public Double getPorciento() {
        return this.porciento;
    }

    public void setPorciento(Double porciento) {
        this.porciento = porciento;
    }

}
