package cu.uci.cesim.hce_back.estadisticas.model.entity.auto;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

// Generated Apr 18, 2012 10:46:48 AM by Hibernate Tools 3.4.0.CR1

/**
 * PoblacionStatus generated by hbm2java
 */
@Entity
@Table(name = "poblacion_status", schema = "estadisticas")
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "id")
public class PoblacionStatus_estadisticas implements java.io.Serializable {

    private long id;
    private Integer version;
    private Entidad_estadisticas entidad;
    private Status_estadisticas status;
    private Integer anno;
    private Boolean calculado;
    private Boolean eliminado;
    private Long cid;
    private Set<PoblacionCalcSource_estadisticas> poblacionCalcSources = new HashSet<PoblacionCalcSource_estadisticas>(
            0);
    private Set<PoblacionEdad_estadisticas> poblacionEdads = new HashSet<PoblacionEdad_estadisticas>(
            0);

    public PoblacionStatus_estadisticas() {
    }

    public PoblacionStatus_estadisticas(long id) {
        this.id = id;
    }

    public PoblacionStatus_estadisticas(long id, Entidad_estadisticas entidad,
                                        Status_estadisticas status, Integer anno, Boolean calculado,
                                        Boolean eliminado, Long cid,
                                        Set<PoblacionCalcSource_estadisticas> poblacionCalcSources,
                                        Set<PoblacionEdad_estadisticas> poblacionEdads) {
        this.id = id;
        this.entidad = entidad;
        this.status = status;
        this.anno = anno;
        this.calculado = calculado;
        this.eliminado = eliminado;
        this.cid = cid;
        this.poblacionCalcSources = poblacionCalcSources;
        this.poblacionEdads = poblacionEdads;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @Version
    @Column(name = "version")
    public Integer getVersion() {
        return this.version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_entidad")
    public Entidad_estadisticas getEntidad() {
        return this.entidad;
    }

    public void setEntidad(Entidad_estadisticas entidad) {
        this.entidad = entidad;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_status")
    public Status_estadisticas getStatus() {
        return this.status;
    }

    public void setStatus(Status_estadisticas status) {
        this.status = status;
    }

    @Column(name = "anno")
    public Integer getAnno() {
        return this.anno;
    }

    public void setAnno(Integer anno) {
        this.anno = anno;
    }

    @Column(name = "calculado")
    public Boolean getCalculado() {
        return this.calculado;
    }

    public void setCalculado(Boolean calculado) {
        this.calculado = calculado;
    }

    @Column(name = "eliminado")
    public Boolean getEliminado() {
        return this.eliminado;
    }

    public void setEliminado(Boolean eliminado) {
        this.eliminado = eliminado;
    }

    @Column(name = "cid")
    public Long getCid() {
        return this.cid;
    }

    public void setCid(Long cid) {
        this.cid = cid;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "poblacionStatus")
    public Set<PoblacionCalcSource_estadisticas> getPoblacionCalcSources() {
        return this.poblacionCalcSources;
    }

    public void setPoblacionCalcSources(
            Set<PoblacionCalcSource_estadisticas> poblacionCalcSources) {
        this.poblacionCalcSources = poblacionCalcSources;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "poblacionStatus")
    public Set<PoblacionEdad_estadisticas> getPoblacionEdads() {
        return this.poblacionEdads;
    }

    public void setPoblacionEdads(Set<PoblacionEdad_estadisticas> poblacionEdads) {
        this.poblacionEdads = poblacionEdads;
    }

}
