package cu.uci.cesim.hce_back.estadisticas.model.entity.auto;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

import javax.persistence.*;
import java.util.Date;

// Generated Apr 18, 2012 10:46:48 AM by Hibernate Tools 3.4.0.CR1


/**
 * RegistroTransfusion generated by hbm2java
 */
@Entity
@Table(name = "registro_transfusion", schema = "publico")
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "id")
public class RegistroTransfusion_estadisticas implements java.io.Serializable {

    private long id;
    private Integer version;
    private TipoReaccionTransfusional_estadisticas tipoReaccionTransfusional;
    private EntregaSangre_estadisticas entregaSangre;
    private String observaciones;
    private Boolean eliminado;
    private Long cid;
    private Date fecha;
    private Date hora;

    public RegistroTransfusion_estadisticas() {
    }

    public RegistroTransfusion_estadisticas(long id,
                                            EntregaSangre_estadisticas entregaSangre, String observaciones,
                                            Date fecha, Date hora) {
        this.id = id;
        this.entregaSangre = entregaSangre;
        this.observaciones = observaciones;
        this.fecha = fecha;
        this.hora = hora;
    }

    public RegistroTransfusion_estadisticas(long id,
                                            TipoReaccionTransfusional_estadisticas tipoReaccionTransfusional,
                                            EntregaSangre_estadisticas entregaSangre, String observaciones,
                                            Boolean eliminado, Long cid, Date fecha, Date hora) {
        this.id = id;
        this.tipoReaccionTransfusional = tipoReaccionTransfusional;
        this.entregaSangre = entregaSangre;
        this.observaciones = observaciones;
        this.eliminado = eliminado;
        this.cid = cid;
        this.fecha = fecha;
        this.hora = hora;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @Version
    @Column(name = "version")
    public Integer getVersion() {
        return this.version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_reaccion")
    public TipoReaccionTransfusional_estadisticas getTipoReaccionTransfusional() {
        return this.tipoReaccionTransfusional;
    }

    public void setTipoReaccionTransfusional(
            TipoReaccionTransfusional_estadisticas tipoReaccionTransfusional) {
        this.tipoReaccionTransfusional = tipoReaccionTransfusional;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_entrega", nullable = false)

    public EntregaSangre_estadisticas getEntregaSangre() {
        return this.entregaSangre;
    }

    public void setEntregaSangre(EntregaSangre_estadisticas entregaSangre) {
        this.entregaSangre = entregaSangre;
    }

    @Column(name = "observaciones", nullable = false)

    public String getObservaciones() {
        return this.observaciones;
    }

    public void setObservaciones(String observaciones) {
        if (observaciones != null)
            observaciones = observaciones.trim();
        this.observaciones = observaciones;
    }

    @Column(name = "eliminado")
    public Boolean getEliminado() {
        return this.eliminado;
    }

    public void setEliminado(Boolean eliminado) {
        this.eliminado = eliminado;
    }

    @Column(name = "cid")
    public Long getCid() {
        return this.cid;
    }

    public void setCid(Long cid) {
        this.cid = cid;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "fecha", nullable = false, length = 13)

    public Date getFecha() {
        return this.fecha;
    }

    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    @Temporal(TemporalType.TIME)
    @Column(name = "hora", nullable = false, length = 15)

    public Date getHora() {
        return this.hora;
    }

    public void setHora(Date hora) {
        this.hora = hora;
    }

}
