package cu.uci.cesim.hce_back.estadisticas.model.entity.auto;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

import javax.persistence.*;
import java.util.Date;

// Generated Apr 18, 2012 10:46:48 AM by Hibernate Tools 3.4.0.CR1

/**
 * ResultadoUsuarioLab generated by hbm2java
 */
@Entity
@Table(name = "resultado_usuario_lab", schema = "publico")
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "id")
public class ResultadoUsuarioLab_estadisticas implements java.io.Serializable {

    private long id;
    private Integer version;
    private SolicitudInExamenLab_estadisticas solicitudInExamenLab;
    private Long idUsuario;
    private String accion;
    private Date fechaEmision;
    private Date horaEmision;
    private Boolean eliminado;
    private Long cid;
    private String turno;
    private String equipo;

    public ResultadoUsuarioLab_estadisticas() {
    }

    public ResultadoUsuarioLab_estadisticas(long id) {
        this.id = id;
    }

    public ResultadoUsuarioLab_estadisticas(long id,
                                            SolicitudInExamenLab_estadisticas solicitudInExamenLab,
                                            Long idUsuario, String accion, Date fechaEmision, Date horaEmision,
                                            Boolean eliminado, Long cid, String turno, String equipo) {
        this.id = id;
        this.solicitudInExamenLab = solicitudInExamenLab;
        this.idUsuario = idUsuario;
        this.accion = accion;
        this.fechaEmision = fechaEmision;
        this.horaEmision = horaEmision;
        this.eliminado = eliminado;
        this.cid = cid;
        this.turno = turno;
        this.equipo = equipo;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @Version
    @Column(name = "version")
    public Integer getVersion() {
        return this.version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_solicitud_in_examen_lab")
    public SolicitudInExamenLab_estadisticas getSolicitudInExamenLab() {
        return this.solicitudInExamenLab;
    }

    public void setSolicitudInExamenLab(
            SolicitudInExamenLab_estadisticas solicitudInExamenLab) {
        this.solicitudInExamenLab = solicitudInExamenLab;
    }

    @Column(name = "id_usuario")
    public Long getIdUsuario() {
        return this.idUsuario;
    }

    public void setIdUsuario(Long idUsuario) {
        this.idUsuario = idUsuario;
    }

    @Column(name = "accion")
    public String getAccion() {
        return this.accion;
    }

    public void setAccion(String accion) {
        if (accion != null)
            accion = accion.trim();
        this.accion = accion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "fecha_emision", length = 13)
    public Date getFechaEmision() {
        return this.fechaEmision;
    }

    public void setFechaEmision(Date fechaEmision) {
        this.fechaEmision = fechaEmision;
    }

    @Temporal(TemporalType.TIME)
    @Column(name = "hora_emision", length = 8)
    public Date getHoraEmision() {
        return this.horaEmision;
    }

    public void setHoraEmision(Date horaEmision) {
        this.horaEmision = horaEmision;
    }

    @Column(name = "eliminado")
    public Boolean getEliminado() {
        return this.eliminado;
    }

    public void setEliminado(Boolean eliminado) {
        this.eliminado = eliminado;
    }

    @Column(name = "cid")
    public Long getCid() {
        return this.cid;
    }

    public void setCid(Long cid) {
        this.cid = cid;
    }

    @Column(name = "turno")
    public String getTurno() {
        return this.turno;
    }

    public void setTurno(String turno) {
        if (turno != null)
            turno = turno.trim();
        this.turno = turno;
    }

    @Column(name = "equipo")
    public String getEquipo() {
        return this.equipo;
    }

    public void setEquipo(String equipo) {
        if (equipo != null)
            equipo = equipo.trim();
        this.equipo = equipo;
    }

}
