package cu.uci.cesim.hce_back.estadisticas.model.entity.auto;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;
import org.hibernate.validator.constraints.Length;

import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

// Generated 31-ene-2009 13:29:41 by Hibernate Tools 3.2.2.GA


/**
 * Role generated by hbm2java
 */
@Entity
@Table(name = "role", schema = "seguridad", uniqueConstraints = @UniqueConstraint(columnNames = "name"))
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "id")
public class Role_estadisticas implements java.io.Serializable {

    private Long id;
    private Integer version;
    private String name;
    private Boolean eliminado;
    private Long cid;
    private Set<Usuario_estadisticas> usuarios = new HashSet<Usuario_estadisticas>(0);

    public Role_estadisticas() {
    }

    public Role_estadisticas(Long id, String name) {
        this.id = id;
        this.name = name;
    }

    public Role_estadisticas(Long id, String name, Boolean eliminado, Long cid,
                             Set<Usuario_estadisticas> usuarios) {
        this.id = id;
        this.name = name;
        this.eliminado = eliminado;
        this.cid = cid;
        this.usuarios = usuarios;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)

    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Version
    @Column(name = "version")
    public Integer getVersion() {
        return this.version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    @Column(name = "name", unique = true, nullable = false, length = 50)

    @Length(max = 50)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "eliminado")
    public Boolean getEliminado() {
        return this.eliminado;
    }

    public void setEliminado(Boolean eliminado) {
        this.eliminado = eliminado;
    }

    @Column(name = "cid")
    public Long getCid() {
        return this.cid;
    }

    public void setCid(Long cid) {
        this.cid = cid;
    }

    @ManyToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    @JoinTable(name = "user_in_role", schema = "seguridad", joinColumns = {@JoinColumn(name = "id_role", nullable = false, updatable = false)}, inverseJoinColumns = {@JoinColumn(name = "id_user", nullable = false, updatable = false)})
    public Set<Usuario_estadisticas> getUsuarios() {
        return this.usuarios;
    }

    public void setUsuarios(Set<Usuario_estadisticas> usuarios) {
        this.usuarios = usuarios;
    }

}
