package cu.uci.cesim.hce_back.estadisticas.model.entity.auto;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

// Generated Apr 18, 2012 10:46:48 AM by Hibernate Tools 3.4.0.CR1

/**
 * SeccionLaboratorio generated by hbm2java
 */
@Entity
@Table(name = "seccion_laboratorio", schema = "nomencladores")
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "id")
public class SeccionLaboratorio_estadisticas implements java.io.Serializable {

    private long id;
    private Integer version;
    private String valor;
    private Boolean eliminado;
    private Long cid;
    private String codigo;
    private Boolean antibiograma;
    private Boolean placa;
    private Set<ExamenLab_estadisticas> examenLabs = new HashSet<ExamenLab_estadisticas>(
            0);

    public SeccionLaboratorio_estadisticas() {
    }

    public SeccionLaboratorio_estadisticas(long id) {
        this.id = id;
    }

    public SeccionLaboratorio_estadisticas(long id, String valor,
                                           Boolean eliminado, Long cid, String codigo, Boolean antibiograma,
                                           Boolean placa, Set<ExamenLab_estadisticas> examenLabs) {
        this.id = id;
        this.valor = valor;
        this.eliminado = eliminado;
        this.cid = cid;
        this.codigo = codigo;
        this.antibiograma = antibiograma;
        this.placa = placa;
        this.examenLabs = examenLabs;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @Version
    @Column(name = "version")
    public Integer getVersion() {
        return this.version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    @Column(name = "valor")
    public String getValor() {
        return this.valor;
    }

    public void setValor(String valor) {
        if (valor != null)
            valor = valor.trim();
        this.valor = valor;
    }

    @Column(name = "eliminado")
    public Boolean getEliminado() {
        return this.eliminado;
    }

    public void setEliminado(Boolean eliminado) {
        this.eliminado = eliminado;
    }

    @Column(name = "cid")
    public Long getCid() {
        return this.cid;
    }

    public void setCid(Long cid) {
        this.cid = cid;
    }

    @Column(name = "codigo")
    public String getCodigo() {
        return this.codigo;
    }

    public void setCodigo(String codigo) {
        if (codigo != null)
            codigo = codigo.trim();
        this.codigo = codigo;
    }

    @Column(name = "antibiograma")
    public Boolean getAntibiograma() {
        return this.antibiograma;
    }

    public void setAntibiograma(Boolean antibiograma) {
        this.antibiograma = antibiograma;
    }

    @Column(name = "placa")
    public Boolean getPlaca() {
        return this.placa;
    }

    public void setPlaca(Boolean placa) {
        this.placa = placa;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "seccionLaboratorio")
    public Set<ExamenLab_estadisticas> getExamenLabs() {
        return this.examenLabs;
    }

    public void setExamenLabs(Set<ExamenLab_estadisticas> examenLabs) {
        this.examenLabs = examenLabs;
    }

}
