package cu.uci.cesim.hce_back.estadisticas.model.entity.auto;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

import javax.persistence.*;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

// Generated Apr 18, 2012 10:46:48 AM by Hibernate Tools 3.4.0.CR1


/**
 * SolicitudIntervencion generated by hbm2java
 */
@Entity
@Table(name = "solicitud_intervencion", schema = "publico")
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "id")
public class SolicitudIntervencion_estadisticas implements java.io.Serializable {

    private long id;
    private Integer version;
    private Funcionalidad_estadisticas funcionalidad;
    private OrdenAdmision_estadisticas ordenAdmision;
    private CaracterIntervencion_estadisticas caracterIntervencion;
    private DiagnosticoMedico_estadisticas diagnosticoMedico;
    private CipProcedimiento_estadisticas cipProcedimiento;
    private Quirofano_estadisticas quirofano;
    private HojaFrontal_estadisticas hojaFrontal;
    private ServicioInEntidad_estadisticas servicioInEntidad;
    private Date fechaSolicitud;
    private boolean electiva;
    private Date duracionAproximada;
    private Date fechaFijada;
    private Long idFuncionarioAprueba;
    private Boolean eliminado;
    private Long cid;
    private Boolean aprobada;
    private boolean emergencia;
    private String causaModificacionQx;
    private String causaRechazoSolicitud;
    private String otrosAnestesiologos;
    private String otrasEnfermeras;
    private boolean realizada;
    private Boolean enCreacion;
    private Integer horaDuracion;
    private Integer minutoDuracion;
    private Boolean notificacion;
    private Boolean rayosX;
    private Boolean biopsiaCongelacion;
    private Boolean camaUci;
    private Long idTipoRiesgoIntervencion;
    private Long idRiesgoInfeccion;
    private Long idTipoQuirofano;
    private Long idTipoAnestesia;
    private TipoIntervencionQuirurgica_estadisticas tipoIntervencionQuirurgica;

    private Date horaPlanificada;
    private Set<InfecFicha_estadisticas> infecFichas = new HashSet<InfecFicha_estadisticas>(
            0);
    private Set<SolicitudBiopsia_estadisticas> solicitudBiopsias = new HashSet<SolicitudBiopsia_estadisticas>(
            0);
    private Set<HojaEmergencia_estadisticas> hojaEmergencias = new HashSet<HojaEmergencia_estadisticas>(
            0);
    private Set<SolicitudCausas_estadisticas> solicitudCausases = new HashSet<SolicitudCausas_estadisticas>(
            0);
    private Set<HojaConsulta_estadisticas> hojaConsultas = new HashSet<HojaConsulta_estadisticas>(
            0);
    private Set<SolicitudTransfusion_estadisticas> solicitudTransfusions = new HashSet<SolicitudTransfusion_estadisticas>(
            0);
    private Set<EvolucionMedica_estadisticas> evolucionMedicas = new HashSet<EvolucionMedica_estadisticas>(
            0);

    public SolicitudIntervencion_estadisticas() {
    }

    public SolicitudIntervencion_estadisticas(long id,
                                              HojaFrontal_estadisticas hojaFrontal, Date fechaSolicitud,
                                              boolean electiva, Date fechaFijada, boolean emergencia,
                                              boolean realizada) {
        this.id = id;
        this.hojaFrontal = hojaFrontal;
        this.fechaSolicitud = fechaSolicitud;
        this.electiva = electiva;
        this.fechaFijada = fechaFijada;
        this.emergencia = emergencia;
        this.realizada = realizada;
    }

    public SolicitudIntervencion_estadisticas(long id,
                                              Funcionalidad_estadisticas funcionalidad,
                                              OrdenAdmision_estadisticas ordenAdmision,
                                              CaracterIntervencion_estadisticas caracterIntervencion,
                                              DiagnosticoMedico_estadisticas diagnosticoMedico,
                                              CipProcedimiento_estadisticas cipProcedimiento,
                                              Quirofano_estadisticas quirofano,
                                              HojaFrontal_estadisticas hojaFrontal,
                                              ServicioInEntidad_estadisticas servicioInEntidad,
                                              Date fechaSolicitud, boolean electiva, Date duracionAproximada,
                                              Date fechaFijada, Long idFuncionarioAprueba, Boolean eliminado,
                                              Long cid, Boolean aprobada, boolean emergencia,
                                              String causaModificacionQx, String causaRechazoSolicitud,
                                              String otrosAnestesiologos, String otrasEnfermeras,
                                              boolean realizada, Boolean enCreacion, Integer horaDuracion,
                                              Integer minutoDuracion, Boolean notificacion, Boolean rayosX,
                                              Boolean biopsiaCongelacion, Boolean camaUci,
                                              Long idTipoRiesgoIntervencion, Long idRiesgoInfeccion,
                                              Long idTipoQuirofano, Long idTipoAnestesia,
                                              TipoIntervencionQuirurgica_estadisticas tipoIntervencionQuirurgica, Date horaPlanificada,
                                              Set<InfecFicha_estadisticas> infecFichas,
                                              Set<SolicitudBiopsia_estadisticas> solicitudBiopsias,
                                              Set<HojaEmergencia_estadisticas> hojaEmergencias,
                                              Set<SolicitudCausas_estadisticas> solicitudCausases,
                                              Set<HojaConsulta_estadisticas> hojaConsultas,
                                              Set<SolicitudTransfusion_estadisticas> solicitudTransfusions,
                                              Set<EvolucionMedica_estadisticas> evolucionMedicas) {
        this.id = id;
        this.funcionalidad = funcionalidad;
        this.ordenAdmision = ordenAdmision;
        this.caracterIntervencion = caracterIntervencion;
        this.diagnosticoMedico = diagnosticoMedico;
        this.cipProcedimiento = cipProcedimiento;
        this.quirofano = quirofano;
        this.hojaFrontal = hojaFrontal;
        this.servicioInEntidad = servicioInEntidad;
        this.fechaSolicitud = fechaSolicitud;
        this.electiva = electiva;
        this.duracionAproximada = duracionAproximada;
        this.fechaFijada = fechaFijada;
        this.idFuncionarioAprueba = idFuncionarioAprueba;
        this.eliminado = eliminado;
        this.cid = cid;
        this.aprobada = aprobada;
        this.emergencia = emergencia;
        this.causaModificacionQx = causaModificacionQx;
        this.causaRechazoSolicitud = causaRechazoSolicitud;
        this.otrosAnestesiologos = otrosAnestesiologos;
        this.otrasEnfermeras = otrasEnfermeras;
        this.realizada = realizada;
        this.enCreacion = enCreacion;
        this.horaDuracion = horaDuracion;
        this.minutoDuracion = minutoDuracion;
        this.notificacion = notificacion;
        this.rayosX = rayosX;
        this.biopsiaCongelacion = biopsiaCongelacion;
        this.camaUci = camaUci;
        this.idTipoRiesgoIntervencion = idTipoRiesgoIntervencion;
        this.idRiesgoInfeccion = idRiesgoInfeccion;
        this.idTipoQuirofano = idTipoQuirofano;
        this.idTipoAnestesia = idTipoAnestesia;
        this.tipoIntervencionQuirurgica = tipoIntervencionQuirurgica;
        this.horaPlanificada = horaPlanificada;
        this.infecFichas = infecFichas;
        this.solicitudBiopsias = solicitudBiopsias;
        this.hojaEmergencias = hojaEmergencias;
        this.solicitudCausases = solicitudCausases;
        this.hojaConsultas = hojaConsultas;
        this.solicitudTransfusions = solicitudTransfusions;
        this.evolucionMedicas = evolucionMedicas;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @Version
    @Column(name = "version")
    public Integer getVersion() {
        return this.version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_entidad")
    public Funcionalidad_estadisticas getFuncionalidad() {
        return this.funcionalidad;
    }

    public void setFuncionalidad(Funcionalidad_estadisticas funcionalidad) {
        this.funcionalidad = funcionalidad;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_orden_admision")
    public OrdenAdmision_estadisticas getOrdenAdmision() {
        return this.ordenAdmision;
    }

    public void setOrdenAdmision(OrdenAdmision_estadisticas ordenAdmision) {
        this.ordenAdmision = ordenAdmision;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_caracter")
    public CaracterIntervencion_estadisticas getCaracterIntervencion() {
        return this.caracterIntervencion;
    }

    public void setCaracterIntervencion(
            CaracterIntervencion_estadisticas caracterIntervencion) {
        this.caracterIntervencion = caracterIntervencion;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_diagnostico")
    public DiagnosticoMedico_estadisticas getDiagnosticoMedico() {
        return this.diagnosticoMedico;
    }

    public void setDiagnosticoMedico(
            DiagnosticoMedico_estadisticas diagnosticoMedico) {
        this.diagnosticoMedico = diagnosticoMedico;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_procedimiento")
    public CipProcedimiento_estadisticas getCipProcedimiento() {
        return this.cipProcedimiento;
    }

    public void setCipProcedimiento(
            CipProcedimiento_estadisticas cipProcedimiento) {
        this.cipProcedimiento = cipProcedimiento;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_quirofano")
    public Quirofano_estadisticas getQuirofano() {
        return this.quirofano;
    }

    public void setQuirofano(Quirofano_estadisticas quirofano) {
        this.quirofano = quirofano;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_hoja_frontal", nullable = false)

    public HojaFrontal_estadisticas getHojaFrontal() {
        return this.hojaFrontal;
    }

    public void setHojaFrontal(HojaFrontal_estadisticas hojaFrontal) {
        this.hojaFrontal = hojaFrontal;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_servicio_quirurgico")
    public ServicioInEntidad_estadisticas getServicioInEntidad() {
        return this.servicioInEntidad;
    }

    public void setServicioInEntidad(
            ServicioInEntidad_estadisticas servicioInEntidad) {
        this.servicioInEntidad = servicioInEntidad;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "fecha_solicitud", nullable = false, length = 13)

    public Date getFechaSolicitud() {
        return this.fechaSolicitud;
    }

    public void setFechaSolicitud(Date fechaSolicitud) {
        this.fechaSolicitud = fechaSolicitud;
    }

    @Column(name = "electiva", nullable = false)

    public boolean isElectiva() {
        return this.electiva;
    }

    public void setElectiva(boolean electiva) {
        this.electiva = electiva;
    }

    @Temporal(TemporalType.TIME)
    @Column(name = "duracion_aproximada", length = 8)
    public Date getDuracionAproximada() {
        return this.duracionAproximada;
    }

    public void setDuracionAproximada(Date duracionAproximada) {
        this.duracionAproximada = duracionAproximada;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "fecha_fijada", nullable = false, length = 13)

    public Date getFechaFijada() {
        return this.fechaFijada;
    }

    public void setFechaFijada(Date fechaFijada) {
        this.fechaFijada = fechaFijada;
    }

    @Column(name = "id_funcionario_aprueba")
    public Long getIdFuncionarioAprueba() {
        return this.idFuncionarioAprueba;
    }

    public void setIdFuncionarioAprueba(Long idFuncionarioAprueba) {
        this.idFuncionarioAprueba = idFuncionarioAprueba;
    }

    @Column(name = "eliminado")
    public Boolean getEliminado() {
        return this.eliminado;
    }

    public void setEliminado(Boolean eliminado) {
        this.eliminado = eliminado;
    }

    @Column(name = "cid")
    public Long getCid() {
        return this.cid;
    }

    public void setCid(Long cid) {
        this.cid = cid;
    }

    @Column(name = "aprobada")
    public Boolean getAprobada() {
        return this.aprobada;
    }

    public void setAprobada(Boolean aprobada) {
        this.aprobada = aprobada;
    }

    @Column(name = "emergencia", nullable = false)

    public boolean isEmergencia() {
        return this.emergencia;
    }

    public void setEmergencia(boolean emergencia) {
        this.emergencia = emergencia;
    }

    @Column(name = "causa_modificacion_qx")
    public String getCausaModificacionQx() {
        return this.causaModificacionQx;
    }

    public void setCausaModificacionQx(String causaModificacionQx) {
        if (causaModificacionQx != null)
            causaModificacionQx = causaModificacionQx.trim();
        this.causaModificacionQx = causaModificacionQx;
    }

    @Column(name = "causa_rechazo_solicitud")
    public String getCausaRechazoSolicitud() {
        return this.causaRechazoSolicitud;
    }

    public void setCausaRechazoSolicitud(String causaRechazoSolicitud) {
        if (causaRechazoSolicitud != null)
            causaRechazoSolicitud = causaRechazoSolicitud.trim();
        this.causaRechazoSolicitud = causaRechazoSolicitud;
    }

    @Column(name = "otros_anestesiologos")
    public String getOtrosAnestesiologos() {
        return this.otrosAnestesiologos;
    }

    public void setOtrosAnestesiologos(String otrosAnestesiologos) {
        if (otrosAnestesiologos != null)
            otrosAnestesiologos = otrosAnestesiologos.trim();
        this.otrosAnestesiologos = otrosAnestesiologos;
    }

    @Column(name = "otras_enfermeras")
    public String getOtrasEnfermeras() {
        return this.otrasEnfermeras;
    }

    public void setOtrasEnfermeras(String otrasEnfermeras) {
        if (otrasEnfermeras != null)
            otrasEnfermeras = otrasEnfermeras.trim();
        this.otrasEnfermeras = otrasEnfermeras;
    }

    @Column(name = "realizada", nullable = false)

    public boolean isRealizada() {
        return this.realizada;
    }

    public void setRealizada(boolean realizada) {
        this.realizada = realizada;
    }

    @Column(name = "en_creacion")
    public Boolean getEnCreacion() {
        return this.enCreacion;
    }

    public void setEnCreacion(Boolean enCreacion) {
        this.enCreacion = enCreacion;
    }

    @Column(name = "hora_duracion")
    public Integer getHoraDuracion() {
        return this.horaDuracion;
    }

    public void setHoraDuracion(Integer horaDuracion) {
        this.horaDuracion = horaDuracion;
    }

    @Column(name = "minuto_duracion")
    public Integer getMinutoDuracion() {
        return this.minutoDuracion;
    }

    public void setMinutoDuracion(Integer minutoDuracion) {
        this.minutoDuracion = minutoDuracion;
    }

    @Column(name = "notificacion")
    public Boolean getNotificacion() {
        return this.notificacion;
    }

    public void setNotificacion(Boolean notificacion) {
        this.notificacion = notificacion;
    }

    @Column(name = "rayos_x")
    public Boolean getRayosX() {
        return this.rayosX;
    }

    public void setRayosX(Boolean rayosX) {
        this.rayosX = rayosX;
    }

    @Column(name = "biopsia_congelacion")
    public Boolean getBiopsiaCongelacion() {
        return this.biopsiaCongelacion;
    }

    public void setBiopsiaCongelacion(Boolean biopsiaCongelacion) {
        this.biopsiaCongelacion = biopsiaCongelacion;
    }

    @Column(name = "cama_uci")
    public Boolean getCamaUci() {
        return this.camaUci;
    }

    public void setCamaUci(Boolean camaUci) {
        this.camaUci = camaUci;
    }

    @Column(name = "id_tipo_riesgo_intervencion")
    public Long getIdTipoRiesgoIntervencion() {
        return this.idTipoRiesgoIntervencion;
    }

    public void setIdTipoRiesgoIntervencion(Long idTipoRiesgoIntervencion) {
        this.idTipoRiesgoIntervencion = idTipoRiesgoIntervencion;
    }

    @Column(name = "id_riesgo_infeccion")
    public Long getIdRiesgoInfeccion() {
        return this.idRiesgoInfeccion;
    }

    public void setIdRiesgoInfeccion(Long idRiesgoInfeccion) {
        this.idRiesgoInfeccion = idRiesgoInfeccion;
    }

    @Column(name = "id_tipo_quirofano")
    public Long getIdTipoQuirofano() {
        return this.idTipoQuirofano;
    }

    public void setIdTipoQuirofano(Long idTipoQuirofano) {
        this.idTipoQuirofano = idTipoQuirofano;
    }

    @Column(name = "id_tipo_anestesia")
    public Long getIdTipoAnestesia() {
        return this.idTipoAnestesia;
    }

    public void setIdTipoAnestesia(Long idTipoAnestesia) {
        this.idTipoAnestesia = idTipoAnestesia;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_tipo_intervencion")
    public TipoIntervencionQuirurgica_estadisticas getTipoIntervencionQuirurgica() {
        return this.tipoIntervencionQuirurgica;
    }

    public void setTipoIntervencionQuirurgica(
            TipoIntervencionQuirurgica_estadisticas tipoIntervencionQuirurgica) {
        this.tipoIntervencionQuirurgica = tipoIntervencionQuirurgica;
    }

    @Temporal(TemporalType.TIME)
    @Column(name = "hora_planificada", length = 8)
    public Date getHoraPlanificada() {
        return this.horaPlanificada;
    }

    public void setHoraPlanificada(Date horaPlanificada) {
        this.horaPlanificada = horaPlanificada;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "solicitudIntervencion")
    public Set<InfecFicha_estadisticas> getInfecFichas() {
        return this.infecFichas;
    }

    public void setInfecFichas(Set<InfecFicha_estadisticas> infecFichas) {
        this.infecFichas = infecFichas;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "solicitudIntervencion")
    public Set<SolicitudBiopsia_estadisticas> getSolicitudBiopsias() {
        return this.solicitudBiopsias;
    }

    public void setSolicitudBiopsias(
            Set<SolicitudBiopsia_estadisticas> solicitudBiopsias) {
        this.solicitudBiopsias = solicitudBiopsias;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "solicitudIntervencion")
    public Set<HojaEmergencia_estadisticas> getHojaEmergencias() {
        return this.hojaEmergencias;
    }

    public void setHojaEmergencias(
            Set<HojaEmergencia_estadisticas> hojaEmergencias) {
        this.hojaEmergencias = hojaEmergencias;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "solicitudIntervencion")
    public Set<SolicitudCausas_estadisticas> getSolicitudCausases() {
        return this.solicitudCausases;
    }

    public void setSolicitudCausases(
            Set<SolicitudCausas_estadisticas> solicitudCausases) {
        this.solicitudCausases = solicitudCausases;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "solicitudIntervencion")
    public Set<HojaConsulta_estadisticas> getHojaConsultas() {
        return this.hojaConsultas;
    }

    public void setHojaConsultas(Set<HojaConsulta_estadisticas> hojaConsultas) {
        this.hojaConsultas = hojaConsultas;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "solicitudIntervencion")
    public Set<SolicitudTransfusion_estadisticas> getSolicitudTransfusions() {
        return this.solicitudTransfusions;
    }

    public void setSolicitudTransfusions(
            Set<SolicitudTransfusion_estadisticas> solicitudTransfusions) {
        this.solicitudTransfusions = solicitudTransfusions;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "solicitudIntervencion")
    public Set<EvolucionMedica_estadisticas> getEvolucionMedicas() {
        return this.evolucionMedicas;
    }

    public void setEvolucionMedicas(
            Set<EvolucionMedica_estadisticas> evolucionMedicas) {
        this.evolucionMedicas = evolucionMedicas;
    }

}
