package cu.uci.cesim.hce_back.estadisticas.model.entity.auto;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

// Generated Apr 18, 2012 10:46:48 AM by Hibernate Tools 3.4.0.CR1


/**
 * Status generated by hbm2java
 */
@Entity
@Table(name = "status", schema = "nomencladores", uniqueConstraints = {
        @UniqueConstraint(columnNames = "valor"),
        @UniqueConstraint(columnNames = "codigo")})
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "id")
public class Status_estadisticas implements java.io.Serializable {

    private long id;
    private Integer version;
    private String codigo;
    private String valor;
    private Boolean eliminado;
    private Long cid;
    private Set<HojaFrontal_estadisticas> hojaFrontals = new HashSet<HojaFrontal_estadisticas>(
            0);
    private Set<PoblacionCalcSource_estadisticas> poblacionCalcSources = new HashSet<PoblacionCalcSource_estadisticas>(
            0);
    private Set<TipersStatInEntidad_estadisticas> tipersStatInEntidads = new HashSet<TipersStatInEntidad_estadisticas>(
            0);
    private Set<PersonaHist_estadisticas> personaHists = new HashSet<PersonaHist_estadisticas>(
            0);
    private Set<PoblacionStatus_estadisticas> poblacionStatuses = new HashSet<PoblacionStatus_estadisticas>(
            0);

    public Status_estadisticas() {
    }

    public Status_estadisticas(long id, String codigo, String valor) {
        this.id = id;
        this.codigo = codigo;
        this.valor = valor;
    }

    public Status_estadisticas(long id, String codigo, String valor,
                               Boolean eliminado, Long cid,
                               Set<HojaFrontal_estadisticas> hojaFrontals,
                               Set<PoblacionCalcSource_estadisticas> poblacionCalcSources,
                               Set<TipersStatInEntidad_estadisticas> tipersStatInEntidads,
                               Set<PersonaHist_estadisticas> personaHists,
                               Set<PoblacionStatus_estadisticas> poblacionStatuses) {
        this.id = id;
        this.codigo = codigo;
        this.valor = valor;
        this.eliminado = eliminado;
        this.cid = cid;
        this.hojaFrontals = hojaFrontals;
        this.poblacionCalcSources = poblacionCalcSources;
        this.tipersStatInEntidads = tipersStatInEntidads;
        this.personaHists = personaHists;
        this.poblacionStatuses = poblacionStatuses;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @Version
    @Column(name = "version")
    public Integer getVersion() {
        return this.version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    @Column(name = "codigo", unique = true, nullable = false)

    public String getCodigo() {
        return this.codigo;
    }

    public void setCodigo(String codigo) {
        if (codigo != null)
            codigo = codigo.trim();
        this.codigo = codigo;
    }

    @Column(name = "valor", unique = true, nullable = false)

    public String getValor() {
        return this.valor;
    }

    public void setValor(String valor) {
        if (valor != null)
            valor = valor.trim();
        this.valor = valor;
    }

    @Column(name = "eliminado")
    public Boolean getEliminado() {
        return this.eliminado;
    }

    public void setEliminado(Boolean eliminado) {
        this.eliminado = eliminado;
    }

    @Column(name = "cid")
    public Long getCid() {
        return this.cid;
    }

    public void setCid(Long cid) {
        this.cid = cid;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "status")
    public Set<HojaFrontal_estadisticas> getHojaFrontals() {
        return this.hojaFrontals;
    }

    public void setHojaFrontals(Set<HojaFrontal_estadisticas> hojaFrontals) {
        this.hojaFrontals = hojaFrontals;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "status")
    public Set<PoblacionCalcSource_estadisticas> getPoblacionCalcSources() {
        return this.poblacionCalcSources;
    }

    public void setPoblacionCalcSources(
            Set<PoblacionCalcSource_estadisticas> poblacionCalcSources) {
        this.poblacionCalcSources = poblacionCalcSources;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "status")
    public Set<TipersStatInEntidad_estadisticas> getTipersStatInEntidads() {
        return this.tipersStatInEntidads;
    }

    public void setTipersStatInEntidads(
            Set<TipersStatInEntidad_estadisticas> tipersStatInEntidads) {
        this.tipersStatInEntidads = tipersStatInEntidads;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "status")
    public Set<PersonaHist_estadisticas> getPersonaHists() {
        return this.personaHists;
    }

    public void setPersonaHists(Set<PersonaHist_estadisticas> personaHists) {
        this.personaHists = personaHists;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "status")
    public Set<PoblacionStatus_estadisticas> getPoblacionStatuses() {
        return this.poblacionStatuses;
    }

    public void setPoblacionStatuses(
            Set<PoblacionStatus_estadisticas> poblacionStatuses) {
        this.poblacionStatuses = poblacionStatuses;
    }

}
