package cu.uci.cesim.hce_back.estadisticas.model.entity.auto;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

import javax.persistence.*;

// Generated Apr 18, 2012 10:46:48 AM by Hibernate Tools 3.4.0.CR1

/**
 * TipersStatInEntidad generated by hbm2java
 */
@Entity
@Table(name = "tipers_stat_in_entidad", schema = "estadisticas")
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "id")
public class TipersStatInEntidad_estadisticas implements java.io.Serializable {

    private long id;
    private Integer version;
    private Entidad_estadisticas entidad;
    private Status_estadisticas status;
    private TipoPoblacion_estadisticas tipoPoblacion;
    private Long cid;
    private Boolean eliminado;

    public TipersStatInEntidad_estadisticas() {
    }

    public TipersStatInEntidad_estadisticas(long id) {
        this.id = id;
    }

    public TipersStatInEntidad_estadisticas(long id,
                                            Entidad_estadisticas entidad, Status_estadisticas status,
                                            TipoPoblacion_estadisticas tipoPoblacion, Long cid,
                                            Boolean eliminado) {
        this.id = id;
        this.entidad = entidad;
        this.status = status;
        this.tipoPoblacion = tipoPoblacion;
        this.cid = cid;
        this.eliminado = eliminado;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @Version
    @Column(name = "version")
    public Integer getVersion() {
        return this.version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_entidad")
    public Entidad_estadisticas getEntidad() {
        return this.entidad;
    }

    public void setEntidad(Entidad_estadisticas entidad) {
        this.entidad = entidad;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_status")
    public Status_estadisticas getStatus() {
        return this.status;
    }

    public void setStatus(Status_estadisticas status) {
        this.status = status;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_tipo_poblacion")
    public TipoPoblacion_estadisticas getTipoPoblacion() {
        return this.tipoPoblacion;
    }

    public void setTipoPoblacion(TipoPoblacion_estadisticas tipoPoblacion) {
        this.tipoPoblacion = tipoPoblacion;
    }

    @Column(name = "cid")
    public Long getCid() {
        return this.cid;
    }

    public void setCid(Long cid) {
        this.cid = cid;
    }

    @Column(name = "eliminado")
    public Boolean getEliminado() {
        return this.eliminado;
    }

    public void setEliminado(Boolean eliminado) {
        this.eliminado = eliminado;
    }

}
