package cu.uci.cesim.hce_back.estadisticas.model.entity.auto;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

// Generated Jan 3, 2013 4:54:45 PM by Hibernate Tools 3.4.0.CR1


/**
 * TipoAntecedente generated by hbm2java
 */
@Entity
@Table(name = "tipo_antecedente", schema = "nomencladores", uniqueConstraints = @UniqueConstraint(columnNames = "valor"))
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "id")
public class TipoAntecedente_estadisticas implements java.io.Serializable {

    private long id;
    private Integer version;
    private String valor;
    private Boolean eliminado;
    private Long cid;
    private String codigo;
    private Set<Antecedentes_estadisticas> antecedenteses = new HashSet<Antecedentes_estadisticas>(
            0);

    public TipoAntecedente_estadisticas() {
    }

    public TipoAntecedente_estadisticas(long id, String valor) {
        this.id = id;
        this.valor = valor;
    }

    public TipoAntecedente_estadisticas(long id, String valor,
                                        Boolean eliminado, Long cid, String codigo,
                                        Set<Antecedentes_estadisticas> antecedenteses) {
        this.id = id;
        this.valor = valor;
        this.eliminado = eliminado;
        this.cid = cid;
        this.codigo = codigo;
        this.antecedenteses = antecedenteses;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @Version
    @Column(name = "version")
    public Integer getVersion() {
        return this.version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    @Column(name = "valor", unique = true, nullable = false)

    public String getValor() {
        return this.valor;
    }

    public void setValor(String valor) {
        if (valor != null)
            valor = valor.trim();
        this.valor = valor;
    }

    @Column(name = "eliminado")
    public Boolean getEliminado() {
        return this.eliminado;
    }

    public void setEliminado(Boolean eliminado) {
        this.eliminado = eliminado;
    }

    @Column(name = "cid")
    public Long getCid() {
        return this.cid;
    }

    public void setCid(Long cid) {
        this.cid = cid;
    }

    @Column(name = "codigo")
    public String getCodigo() {
        return this.codigo;
    }

    public void setCodigo(String codigo) {
        if (codigo != null)
            codigo = codigo.trim();
        this.codigo = codigo;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoAntecedente")
    public Set<Antecedentes_estadisticas> getAntecedenteses() {
        return this.antecedenteses;
    }

    public void setAntecedenteses(Set<Antecedentes_estadisticas> antecedenteses) {
        this.antecedenteses = antecedenteses;
    }

}
