package cu.uci.cesim.hce_back.estadisticas.model.entity.auto;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

// Generated Apr 18, 2012 10:46:48 AM by Hibernate Tools 3.4.0.CR1


/**
 * TipoDiagnosticoEnfermedad generated by hbm2java
 */
@Entity
@Table(name = "tipo_diagnostico_enfermedad", schema = "nomencladores", uniqueConstraints = {
        @UniqueConstraint(columnNames = "codigo"),
        @UniqueConstraint(columnNames = "valor")})
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "id")
public class TipoDiagnosticoEnfermedad_estadisticas implements
        java.io.Serializable {

    private long id;
    private Integer version;
    private String valor;
    private Long cid;
    private String codigo;
    private Boolean eliminado;
    private Set<DiagnosticoMedicoEnfermedad_estadisticas> diagnosticoMedicoEnfermedads = new HashSet<DiagnosticoMedicoEnfermedad_estadisticas>(
            0);

    public TipoDiagnosticoEnfermedad_estadisticas() {
    }

    public TipoDiagnosticoEnfermedad_estadisticas(long id, String valor,
                                                  String codigo) {
        this.id = id;
        this.valor = valor;
        this.codigo = codigo;
    }

    public TipoDiagnosticoEnfermedad_estadisticas(
            long id,
            String valor,
            Long cid,
            String codigo,
            Boolean eliminado,
            Set<DiagnosticoMedicoEnfermedad_estadisticas> diagnosticoMedicoEnfermedads) {
        this.id = id;
        this.valor = valor;
        this.cid = cid;
        this.codigo = codigo;
        this.eliminado = eliminado;
        this.diagnosticoMedicoEnfermedads = diagnosticoMedicoEnfermedads;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @Version
    @Column(name = "version")
    public Integer getVersion() {
        return this.version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    @Column(name = "valor", unique = true, nullable = false)

    public String getValor() {
        return this.valor;
    }

    public void setValor(String valor) {
        if (valor != null)
            valor = valor.trim();
        this.valor = valor;
    }

    @Column(name = "cid")
    public Long getCid() {
        return this.cid;
    }

    public void setCid(Long cid) {
        this.cid = cid;
    }

    @Column(name = "codigo", unique = true, nullable = false)

    public String getCodigo() {
        return this.codigo;
    }

    public void setCodigo(String codigo) {
        if (codigo != null)
            codigo = codigo.trim();
        this.codigo = codigo;
    }

    @Column(name = "eliminado")
    public Boolean getEliminado() {
        return this.eliminado;
    }

    public void setEliminado(Boolean eliminado) {
        this.eliminado = eliminado;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoDiagnosticoEnfermedad")
    public Set<DiagnosticoMedicoEnfermedad_estadisticas> getDiagnosticoMedicoEnfermedads() {
        return this.diagnosticoMedicoEnfermedads;
    }

    public void setDiagnosticoMedicoEnfermedads(
            Set<DiagnosticoMedicoEnfermedad_estadisticas> diagnosticoMedicoEnfermedads) {
        this.diagnosticoMedicoEnfermedads = diagnosticoMedicoEnfermedads;
    }

}
