package cu.uci.cesim.hce_back.estadisticas.model.entity.auto;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

// Generated Apr 18, 2012 10:46:48 AM by Hibernate Tools 3.4.0.CR1


/**
 * TipoEstablecimientoSalud generated by hbm2java
 */
@Entity
@Table(name = "tipo_establecimiento_salud", schema = "comun", uniqueConstraints = @UniqueConstraint(columnNames = "valor"))
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "id")
public class TipoEstablecimientoSalud_estadisticas implements
        java.io.Serializable {

    private long id;
    private Integer version;
    private String valor;
    private Boolean eliminado;
    private Long cid;
    private Set<CertificadoDefuncion_estadisticas> certificadoDefuncions = new HashSet<CertificadoDefuncion_estadisticas>(
            0);

    public TipoEstablecimientoSalud_estadisticas() {
    }

    public TipoEstablecimientoSalud_estadisticas(long id, String valor) {
        this.id = id;
        this.valor = valor;
    }

    public TipoEstablecimientoSalud_estadisticas(long id, String valor,
                                                 Boolean eliminado, Long cid,
                                                 Set<CertificadoDefuncion_estadisticas> certificadoDefuncions) {
        this.id = id;
        this.valor = valor;
        this.eliminado = eliminado;
        this.cid = cid;
        this.certificadoDefuncions = certificadoDefuncions;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @Version
    @Column(name = "version")
    public Integer getVersion() {
        return this.version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    @Column(name = "valor", unique = true, nullable = false)

    public String getValor() {
        return this.valor;
    }

    public void setValor(String valor) {
        if (valor != null)
            valor = valor.trim();
        this.valor = valor;
    }

    @Column(name = "eliminado")
    public Boolean getEliminado() {
        return this.eliminado;
    }

    public void setEliminado(Boolean eliminado) {
        this.eliminado = eliminado;
    }

    @Column(name = "cid")
    public Long getCid() {
        return this.cid;
    }

    public void setCid(Long cid) {
        this.cid = cid;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoEstablecimientoSalud")
    public Set<CertificadoDefuncion_estadisticas> getCertificadoDefuncions() {
        return this.certificadoDefuncions;
    }

    public void setCertificadoDefuncions(
            Set<CertificadoDefuncion_estadisticas> certificadoDefuncions) {
        this.certificadoDefuncions = certificadoDefuncions;
    }

}
