package cu.uci.cesim.hce_back.estadisticas.model.entity.auto;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

// Generated Apr 18, 2012 10:46:48 AM by Hibernate Tools 3.4.0.CR1


/**
 * TipoPoblacion generated by hbm2java
 */
@Entity
@Table(name = "tipo_poblacion", schema = "nomencladores")
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "id")
public class TipoPoblacion_estadisticas implements java.io.Serializable {

    private long id;
    private Integer version;
    private Entidad_estadisticas entidad;
    private String valor;
    private Boolean eliminado;
    private Long cid;
    private String codigo;
    private Set<TpobPinfluSexInEnt_estadisticas> tpobPinfluSexInEnts = new HashSet<TpobPinfluSexInEnt_estadisticas>(
            0);
    private Set<TipersStatInEntidad_estadisticas> tipersStatInEntidads = new HashSet<TipersStatInEntidad_estadisticas>(
            0);
    private Set<TpobPinfluAgeInEnt_estadisticas> tpobPinfluAgeInEnts = new HashSet<TpobPinfluAgeInEnt_estadisticas>(
            0);

    public TipoPoblacion_estadisticas() {
    }

    public TipoPoblacion_estadisticas(long id, String valor, String codigo) {
        this.id = id;
        this.valor = valor;
        this.codigo = codigo;
    }

    public TipoPoblacion_estadisticas(long id, Entidad_estadisticas entidad,
                                      String valor, Boolean eliminado, Long cid, String codigo,
                                      Set<TpobPinfluSexInEnt_estadisticas> tpobPinfluSexInEnts,
                                      Set<TipersStatInEntidad_estadisticas> tipersStatInEntidads,
                                      Set<TpobPinfluAgeInEnt_estadisticas> tpobPinfluAgeInEnts) {
        this.id = id;
        this.entidad = entidad;
        this.valor = valor;
        this.eliminado = eliminado;
        this.cid = cid;
        this.codigo = codigo;
        this.tpobPinfluSexInEnts = tpobPinfluSexInEnts;
        this.tipersStatInEntidads = tipersStatInEntidads;
        this.tpobPinfluAgeInEnts = tpobPinfluAgeInEnts;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @Version
    @Column(name = "version")
    public Integer getVersion() {
        return this.version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_entidad")
    public Entidad_estadisticas getEntidad() {
        return this.entidad;
    }

    public void setEntidad(Entidad_estadisticas entidad) {
        this.entidad = entidad;
    }

    @Column(name = "valor", nullable = false)

    public String getValor() {
        return this.valor;
    }

    public void setValor(String valor) {
        if (valor != null)
            valor = valor.trim();
        this.valor = valor;
    }

    @Column(name = "eliminado")
    public Boolean getEliminado() {
        return this.eliminado;
    }

    public void setEliminado(Boolean eliminado) {
        this.eliminado = eliminado;
    }

    @Column(name = "cid")
    public Long getCid() {
        return this.cid;
    }

    public void setCid(Long cid) {
        this.cid = cid;
    }

    @Column(name = "codigo", nullable = false)

    public String getCodigo() {
        return this.codigo;
    }

    public void setCodigo(String codigo) {
        if (codigo != null)
            codigo = codigo.trim();
        this.codigo = codigo;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoPoblacion")
    public Set<TpobPinfluSexInEnt_estadisticas> getTpobPinfluSexInEnts() {
        return this.tpobPinfluSexInEnts;
    }

    public void setTpobPinfluSexInEnts(
            Set<TpobPinfluSexInEnt_estadisticas> tpobPinfluSexInEnts) {
        this.tpobPinfluSexInEnts = tpobPinfluSexInEnts;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoPoblacion")
    public Set<TipersStatInEntidad_estadisticas> getTipersStatInEntidads() {
        return this.tipersStatInEntidads;
    }

    public void setTipersStatInEntidads(
            Set<TipersStatInEntidad_estadisticas> tipersStatInEntidads) {
        this.tipersStatInEntidads = tipersStatInEntidads;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoPoblacion")
    public Set<TpobPinfluAgeInEnt_estadisticas> getTpobPinfluAgeInEnts() {
        return this.tpobPinfluAgeInEnts;
    }

    public void setTpobPinfluAgeInEnts(
            Set<TpobPinfluAgeInEnt_estadisticas> tpobPinfluAgeInEnts) {
        this.tpobPinfluAgeInEnts = tpobPinfluAgeInEnts;
    }

}
