package cu.uci.cesim.hce_back.estadisticas.model.entity.auto;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

import javax.persistence.*;

// Generated Jan 3, 2013 4:54:45 PM by Hibernate Tools 3.4.0.CR1


/**
 * TitularBeneficiario generated by hbm2java
 */
@Entity
@Table(name = "titular_beneficiario", schema = "hc_local")
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "id")
public class TitularBeneficiario_estadisticas implements java.io.Serializable {

    private long id;
    private Integer version;
    private Parentesco_estadisticas parentesco;
    private Persona_estadisticas personaByIdBeneficiario;
    private Persona_estadisticas personaByIdTitular;
    private Long cid;
    private Boolean benefPlanSalud;
    private Boolean eliminado;
    private String codigoRelacion;

    public TitularBeneficiario_estadisticas() {
    }

    public TitularBeneficiario_estadisticas(long id,
                                            Persona_estadisticas personaByIdBeneficiario,
                                            Persona_estadisticas personaByIdTitular) {
        this.id = id;
        this.personaByIdBeneficiario = personaByIdBeneficiario;
        this.personaByIdTitular = personaByIdTitular;
    }

    public TitularBeneficiario_estadisticas(long id,
                                            Parentesco_estadisticas parentesco,
                                            Persona_estadisticas personaByIdBeneficiario,
                                            Persona_estadisticas personaByIdTitular, Long cid,
                                            Boolean benefPlanSalud, Boolean eliminado, String codigoRelacion) {
        this.id = id;
        this.parentesco = parentesco;
        this.personaByIdBeneficiario = personaByIdBeneficiario;
        this.personaByIdTitular = personaByIdTitular;
        this.cid = cid;
        this.benefPlanSalud = benefPlanSalud;
        this.eliminado = eliminado;
        this.codigoRelacion = codigoRelacion;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @Version
    @Column(name = "version")
    public Integer getVersion() {
        return this.version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_parentesco")
    public Parentesco_estadisticas getParentesco() {
        return this.parentesco;
    }

    public void setParentesco(Parentesco_estadisticas parentesco) {
        this.parentesco = parentesco;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_beneficiario", nullable = false)

    public Persona_estadisticas getPersonaByIdBeneficiario() {
        return this.personaByIdBeneficiario;
    }

    public void setPersonaByIdBeneficiario(
            Persona_estadisticas personaByIdBeneficiario) {
        this.personaByIdBeneficiario = personaByIdBeneficiario;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_titular", nullable = false)

    public Persona_estadisticas getPersonaByIdTitular() {
        return this.personaByIdTitular;
    }

    public void setPersonaByIdTitular(Persona_estadisticas personaByIdTitular) {
        this.personaByIdTitular = personaByIdTitular;
    }

    @Column(name = "cid")
    public Long getCid() {
        return this.cid;
    }

    public void setCid(Long cid) {
        this.cid = cid;
    }

    @Column(name = "benef_plan_salud")
    public Boolean getBenefPlanSalud() {
        return this.benefPlanSalud;
    }

    public void setBenefPlanSalud(Boolean benefPlanSalud) {
        this.benefPlanSalud = benefPlanSalud;
    }

    @Column(name = "eliminado")
    public Boolean getEliminado() {
        return this.eliminado;
    }

    public void setEliminado(Boolean eliminado) {
        this.eliminado = eliminado;
    }

    @Column(name = "codigo_relacion")
    public String getCodigoRelacion() {
        return this.codigoRelacion;
    }

    public void setCodigoRelacion(String codigoRelacion) {
        if (codigoRelacion != null)
            codigoRelacion = codigoRelacion.trim();
        this.codigoRelacion = codigoRelacion;
    }

}
