package cu.uci.cesim.hce_back.estadisticas.model.entity.auto;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

import javax.persistence.*;

// Generated Apr 18, 2012 10:46:48 AM by Hibernate Tools 3.4.0.CR1


/**
 * TpobPinfluAgeInEnt generated by hbm2java
 */
@Entity
@Table(name = "tpob_pinflu_age_in_ent", schema = "estadisticas")
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "id")
public class TpobPinfluAgeInEnt_estadisticas implements java.io.Serializable {

    private long id;
    private Integer version;
    private Entidad_estadisticas entidad;
    private Sexo_estadisticas sexo;
    private GrupoEdad_estadisticas grupoEdad;
    private TipoPoblacion_estadisticas tipoPoblacion;
    private Long valor;
    private Long cid;
    private Boolean eliminado;
    private long anno;

    public TpobPinfluAgeInEnt_estadisticas() {
    }

    public TpobPinfluAgeInEnt_estadisticas(long id, long anno) {
        this.id = id;
        this.anno = anno;
    }

    public TpobPinfluAgeInEnt_estadisticas(long id,
                                           Entidad_estadisticas entidad, Sexo_estadisticas sexo,
                                           GrupoEdad_estadisticas grupoEdad,
                                           TipoPoblacion_estadisticas tipoPoblacion, Long valor, Long cid,
                                           Boolean eliminado, long anno) {
        this.id = id;
        this.entidad = entidad;
        this.sexo = sexo;
        this.grupoEdad = grupoEdad;
        this.tipoPoblacion = tipoPoblacion;
        this.valor = valor;
        this.cid = cid;
        this.eliminado = eliminado;
        this.anno = anno;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @Version
    @Column(name = "version")
    public Integer getVersion() {
        return this.version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_entidad")
    public Entidad_estadisticas getEntidad() {
        return this.entidad;
    }

    public void setEntidad(Entidad_estadisticas entidad) {
        this.entidad = entidad;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_sexo")
    public Sexo_estadisticas getSexo() {
        return this.sexo;
    }

    public void setSexo(Sexo_estadisticas sexo) {
        this.sexo = sexo;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_grupo_edad")
    public GrupoEdad_estadisticas getGrupoEdad() {
        return this.grupoEdad;
    }

    public void setGrupoEdad(GrupoEdad_estadisticas grupoEdad) {
        this.grupoEdad = grupoEdad;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_tipo_poblacion")
    public TipoPoblacion_estadisticas getTipoPoblacion() {
        return this.tipoPoblacion;
    }

    public void setTipoPoblacion(TipoPoblacion_estadisticas tipoPoblacion) {
        this.tipoPoblacion = tipoPoblacion;
    }

    @Column(name = "valor")
    public Long getValor() {
        return this.valor;
    }

    public void setValor(Long valor) {
        this.valor = valor;
    }

    @Column(name = "cid")
    public Long getCid() {
        return this.cid;
    }

    public void setCid(Long cid) {
        this.cid = cid;
    }

    @Column(name = "eliminado")
    public Boolean getEliminado() {
        return this.eliminado;
    }

    public void setEliminado(Boolean eliminado) {
        this.eliminado = eliminado;
    }

    @Column(name = "anno", nullable = false)

    public long getAnno() {
        return this.anno;
    }

    public void setAnno(long anno) {
        this.anno = anno;
    }

}
