package cu.uci.cesim.hce_back.estadisticas.model.entity.auto;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

import javax.persistence.*;
import java.util.Date;

// Generated Apr 18, 2012 10:46:48 AM by Hibernate Tools 3.4.0.CR1


/**
 * Transferencia generated by hbm2java
 */
@Entity
@Table(name = "transferencia", schema = "hc_local")
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "id")
public class Transferencia_estadisticas implements java.io.Serializable {

    private long id;
    private Integer version;
    private Funcionalidad_estadisticas funcionalidad;
    private Medico_estadisticas medico;
    private Cama_estadisticas cama;
    private OrdenTransferencia_estadisticas ordenTransferencia;
    private Date fecha;
    private Date hora;
    private Boolean eliminado;
    private Long cid;

    public Transferencia_estadisticas() {
    }

    public Transferencia_estadisticas(long id,
                                      Funcionalidad_estadisticas funcionalidad,
                                      Medico_estadisticas medico, Cama_estadisticas cama,
                                      OrdenTransferencia_estadisticas ordenTransferencia, Date fecha,
                                      Date hora) {
        this.id = id;
        this.funcionalidad = funcionalidad;
        this.medico = medico;
        this.cama = cama;
        this.ordenTransferencia = ordenTransferencia;
        this.fecha = fecha;
        this.hora = hora;
    }

    public Transferencia_estadisticas(long id,
                                      Funcionalidad_estadisticas funcionalidad,
                                      Medico_estadisticas medico, Cama_estadisticas cama,
                                      OrdenTransferencia_estadisticas ordenTransferencia, Date fecha,
                                      Date hora, Boolean eliminado, Long cid) {
        this.id = id;
        this.funcionalidad = funcionalidad;
        this.medico = medico;
        this.cama = cama;
        this.ordenTransferencia = ordenTransferencia;
        this.fecha = fecha;
        this.hora = hora;
        this.eliminado = eliminado;
        this.cid = cid;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @Version
    @Column(name = "version")
    public Integer getVersion() {
        return this.version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_entidad", nullable = false)

    public Funcionalidad_estadisticas getFuncionalidad() {
        return this.funcionalidad;
    }

    public void setFuncionalidad(Funcionalidad_estadisticas funcionalidad) {
        this.funcionalidad = funcionalidad;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_medico", nullable = false)

    public Medico_estadisticas getMedico() {
        return this.medico;
    }

    public void setMedico(Medico_estadisticas medico) {
        this.medico = medico;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_cama", nullable = false)

    public Cama_estadisticas getCama() {
        return this.cama;
    }

    public void setCama(Cama_estadisticas cama) {
        this.cama = cama;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_orden_transferencia", nullable = false)

    public OrdenTransferencia_estadisticas getOrdenTransferencia() {
        return this.ordenTransferencia;
    }

    public void setOrdenTransferencia(
            OrdenTransferencia_estadisticas ordenTransferencia) {
        this.ordenTransferencia = ordenTransferencia;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "fecha", nullable = false, length = 13)

    public Date getFecha() {
        return this.fecha;
    }

    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    @Temporal(TemporalType.TIME)
    @Column(name = "hora", nullable = false, length = 8)

    public Date getHora() {
        return this.hora;
    }

    public void setHora(Date hora) {
        this.hora = hora;
    }

    @Column(name = "eliminado")
    public Boolean getEliminado() {
        return this.eliminado;
    }

    public void setEliminado(Boolean eliminado) {
        this.eliminado = eliminado;
    }

    @Column(name = "cid")
    public Long getCid() {
        return this.cid;
    }

    public void setCid(Long cid) {
        this.cid = cid;
    }

}
