package cu.uci.cesim.hce_back.estadisticas.model.entity.auto;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

import javax.persistence.*;

// Generated Apr 18, 2012 10:46:48 AM by Hibernate Tools 3.4.0.CR1


/**
 * UnidadOrganizativaInPosicion generated by hbm2java
 */
@Entity
@Table(name = "unidad_organizativa_in_posicion", schema = "nomencladores")
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "id")
public class UnidadOrganizativaInPosicion_estadisticas implements
        java.io.Serializable {

    private long id;
    private UnidadOrganizativa_estadisticas unidadOrganizativa;
    private Posicion_estadisticas posicion;

    public UnidadOrganizativaInPosicion_estadisticas() {
    }

    public UnidadOrganizativaInPosicion_estadisticas(long id,
                                                     UnidadOrganizativa_estadisticas unidadOrganizativa,
                                                     Posicion_estadisticas posicion) {
        this.id = id;
        this.unidadOrganizativa = unidadOrganizativa;
        this.posicion = posicion;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_unidad_organizativa", nullable = false)

    public UnidadOrganizativa_estadisticas getUnidadOrganizativa() {
        return this.unidadOrganizativa;
    }

    public void setUnidadOrganizativa(
            UnidadOrganizativa_estadisticas unidadOrganizativa) {
        this.unidadOrganizativa = unidadOrganizativa;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_posicion", nullable = false)

    public Posicion_estadisticas getPosicion() {
        return this.posicion;
    }

    public void setPosicion(Posicion_estadisticas posicion) {
        this.posicion = posicion;
    }

}
