package cu.uci.cesim.hce_back.visorhc.model.entity.auto;

// Generated May 10, 2013 1:18:35 PM by Hibernate Tools 3.4.0.CR1

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * HcConfig generated by hbm2java
 */
@Entity
@Table(name = "hc_config", schema = "hc")
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "id")
public class HcConfig_visorhc implements java.io.Serializable {

    private long id;
    private Integer version;
    private String pixServer;
    private String qedServer;
    private String xdsServer;
    private String ctsServer;
    private Boolean eliminado;
    private Long cid;

    public HcConfig_visorhc() {
    }

    public HcConfig_visorhc(long id) {
        this.id = id;
    }

    public HcConfig_visorhc(long id, String pixServer, String qedServer,
                            String xdsServer, String ctsServer, Boolean eliminado, Long cid) {
        this.id = id;
        this.pixServer = pixServer;
        this.qedServer = qedServer;
        this.xdsServer = xdsServer;
        this.ctsServer = ctsServer;
        this.eliminado = eliminado;
        this.cid = cid;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @Version
    @Column(name = "version")
    public Integer getVersion() {
        return this.version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    @Column(name = "pix_server")
    public String getPixServer() {
        return this.pixServer;
    }

    public void setPixServer(String pixServer) {
        if (pixServer != null)
            pixServer = pixServer.trim();
        this.pixServer = pixServer;
    }

    @Column(name = "qed_server")
    public String getQedServer() {
        return this.qedServer;
    }

    public void setQedServer(String qedServer) {
        if (qedServer != null)
            qedServer = qedServer.trim();
        this.qedServer = qedServer;
    }

    @Column(name = "xds_server")
    public String getXdsServer() {
        return this.xdsServer;
    }

    public void setXdsServer(String xdsServer) {
        if (xdsServer != null)
            xdsServer = xdsServer.trim();
        this.xdsServer = xdsServer;
    }

    @Column(name = "cts_server")
    public String getCtsServer() {
        return this.ctsServer;
    }

    public void setCtsServer(String ctsServer) {
        if (ctsServer != null)
            ctsServer = ctsServer.trim();
        this.ctsServer = ctsServer;
    }

    @Column(name = "eliminado")
    public Boolean getEliminado() {
        return this.eliminado;
    }

    public void setEliminado(Boolean eliminado) {
        this.eliminado = eliminado;
    }

    @Column(name = "cid")
    public Long getCid() {
        return this.cid;
    }

    public void setCid(Long cid) {
        this.cid = cid;
    }

}
