package cu.uci.cesim.hce_back.visorhc.model.entity.auto;

// Generated May 10, 2013 1:18:35 PM by Hibernate Tools 3.4.0.CR1

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * HcDocumentoClinico generated by hbm2java
 */
@Entity
@Table(name = "hc_documento_clinico", schema = "hc")
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "id")
public class HcDocumentoClinico_visorhc implements java.io.Serializable {

    private long id;
    private Integer version;
    private HcTipoDocumento_visorhc hcTipoDocumento;
    private HcMedico_visorhc hcMedico;
    private HcPersona_visorhc hcPersona;
    private HcDocumentoClinico_visorhc hcDocumentoClinico;
    private String titulo;
    private String identificadorDocumento;
    private String docXml;
    private Date fechaCreacion;
    private Date horaCreacion;
    private boolean firmado;
    private String referencia;
    private int versionNumber;
    private boolean ultimaRevision;
    private Long cid;
    @JsonIgnore
    private Set<HcTrazaDocumento_visorhc> hcTrazaDocumentos = new HashSet<HcTrazaDocumento_visorhc>(
            0);
    private Set<HcDocumentosAsociados_visorhc> hcDocumentosAsociadosesForIdDoc1 = new HashSet<HcDocumentosAsociados_visorhc>(
            0);
    private Set<HcDocumentosAsociados_visorhc> hcDocumentosAsociadosesForIdDoc2 = new HashSet<HcDocumentosAsociados_visorhc>(
            0);
    private Set<HcDocumentoClinico_visorhc> hcDocumentoClinicos = new HashSet<HcDocumentoClinico_visorhc>(
            0);

    public HcDocumentoClinico_visorhc() {
    }

    public HcDocumentoClinico_visorhc(long id,
                                      HcTipoDocumento_visorhc hcTipoDocumento, HcMedico_visorhc hcMedico,
                                      HcPersona_visorhc hcPersona, String identificadorDocumento,
                                      Date fechaCreacion, Date horaCreacion, boolean firmado,
                                      String referencia, int versionNumber, boolean ultimaRevision) {
        this.id = id;
        this.hcTipoDocumento = hcTipoDocumento;
        this.hcMedico = hcMedico;
        this.hcPersona = hcPersona;
        this.identificadorDocumento = identificadorDocumento;
        this.fechaCreacion = fechaCreacion;
        this.horaCreacion = horaCreacion;
        this.firmado = firmado;
        this.referencia = referencia;
        this.versionNumber = versionNumber;
        this.ultimaRevision = ultimaRevision;
    }

    public HcDocumentoClinico_visorhc(
            long id,
            HcTipoDocumento_visorhc hcTipoDocumento,
            HcMedico_visorhc hcMedico,
            HcPersona_visorhc hcPersona,
            HcDocumentoClinico_visorhc hcDocumentoClinico,
            String titulo,
            String identificadorDocumento,
            String docXml,
            Date fechaCreacion,
            Date horaCreacion,
            boolean firmado,
            String referencia,
            int versionNumber,
            boolean ultimaRevision,
            Long cid,
            Set<HcTrazaDocumento_visorhc> hcTrazaDocumentos,
            Set<HcDocumentosAsociados_visorhc> hcDocumentosAsociadosesForIdDoc1,
            Set<HcDocumentosAsociados_visorhc> hcDocumentosAsociadosesForIdDoc2,
            Set<HcDocumentoClinico_visorhc> hcDocumentoClinicos) {
        this.id = id;
        this.hcTipoDocumento = hcTipoDocumento;
        this.hcMedico = hcMedico;
        this.hcPersona = hcPersona;
        this.hcDocumentoClinico = hcDocumentoClinico;
        this.titulo = titulo;
        this.identificadorDocumento = identificadorDocumento;
        this.docXml = docXml;
        this.fechaCreacion = fechaCreacion;
        this.horaCreacion = horaCreacion;
        this.firmado = firmado;
        this.referencia = referencia;
        this.versionNumber = versionNumber;
        this.ultimaRevision = ultimaRevision;
        this.cid = cid;
        this.hcTrazaDocumentos = hcTrazaDocumentos;
        this.hcDocumentosAsociadosesForIdDoc1 = hcDocumentosAsociadosesForIdDoc1;
        this.hcDocumentosAsociadosesForIdDoc2 = hcDocumentosAsociadosesForIdDoc2;
        this.hcDocumentoClinicos = hcDocumentoClinicos;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @Version
    @Column(name = "version")
    public Integer getVersion() {
        return this.version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_tipo_documento", nullable = false)
    public HcTipoDocumento_visorhc getHcTipoDocumento() {
        return this.hcTipoDocumento;
    }

    public void setHcTipoDocumento(HcTipoDocumento_visorhc hcTipoDocumento) {
        this.hcTipoDocumento = hcTipoDocumento;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_autor", nullable = false)
    public HcMedico_visorhc getHcMedico() {
        return this.hcMedico;
    }

    public void setHcMedico(HcMedico_visorhc hcMedico) {
        this.hcMedico = hcMedico;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_persona", nullable = false)
    public HcPersona_visorhc getHcPersona() {
        return this.hcPersona;
    }

    public void setHcPersona(HcPersona_visorhc hcPersona) {
        this.hcPersona = hcPersona;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_documento_relacionado")
    public HcDocumentoClinico_visorhc getHcDocumentoClinico() {
        return this.hcDocumentoClinico;
    }

    public void setHcDocumentoClinico(
            HcDocumentoClinico_visorhc hcDocumentoClinico) {
        this.hcDocumentoClinico = hcDocumentoClinico;
    }

    @Column(name = "titulo")
    public String getTitulo() {
        return this.titulo;
    }

    public void setTitulo(String titulo) {
        if (titulo != null)
            titulo = titulo.trim();
        this.titulo = titulo;
    }

    @Column(name = "identificador_documento", nullable = false)
    public String getIdentificadorDocumento() {
        return this.identificadorDocumento;
    }

    public void setIdentificadorDocumento(String identificadorDocumento) {
        if (identificadorDocumento != null)
            identificadorDocumento = identificadorDocumento.trim();
        this.identificadorDocumento = identificadorDocumento;
    }

    @Column(name = "doc_xml")
    public String getDocXml() {
        return this.docXml;
    }

    public void setDocXml(String docXml) {
        if (docXml != null)
            docXml = docXml.trim();
        this.docXml = docXml;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "fecha_creacion", nullable = false, length = 13)
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }

    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    @Temporal(TemporalType.TIME)
    @Column(name = "hora_creacion", nullable = false, length = 15)
    public Date getHoraCreacion() {
        return this.horaCreacion;
    }

    public void setHoraCreacion(Date horaCreacion) {
        this.horaCreacion = horaCreacion;
    }

    @Column(name = "firmado", nullable = false)
    public boolean isFirmado() {
        return this.firmado;
    }

    public void setFirmado(boolean firmado) {
        this.firmado = firmado;
    }

    @Column(name = "referencia", nullable = false)
    public String getReferencia() {
        return this.referencia;
    }

    public void setReferencia(String referencia) {
        if (referencia != null)
            referencia = referencia.trim();
        this.referencia = referencia;
    }

    @Column(name = "version_number", nullable = false)
    public int getVersionNumber() {
        return this.versionNumber;
    }

    public void setVersionNumber(int versionNumber) {
        this.versionNumber = versionNumber;
    }

    @Column(name = "ultima_revision", nullable = false)
    public boolean isUltimaRevision() {
        return this.ultimaRevision;
    }

    public void setUltimaRevision(boolean ultimaRevision) {
        this.ultimaRevision = ultimaRevision;
    }

    @Column(name = "cid")
    public Long getCid() {
        return this.cid;
    }

    public void setCid(Long cid) {
        this.cid = cid;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "hcDocumentoClinico")
    public Set<HcTrazaDocumento_visorhc> getHcTrazaDocumentos() {
        return this.hcTrazaDocumentos;
    }

    public void setHcTrazaDocumentos(
            Set<HcTrazaDocumento_visorhc> hcTrazaDocumentos) {
        this.hcTrazaDocumentos = hcTrazaDocumentos;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "hcDocumentoClinicoByIdDoc1")
    public Set<HcDocumentosAsociados_visorhc> getHcDocumentosAsociadosesForIdDoc1() {
        return this.hcDocumentosAsociadosesForIdDoc1;
    }

    public void setHcDocumentosAsociadosesForIdDoc1(
            Set<HcDocumentosAsociados_visorhc> hcDocumentosAsociadosesForIdDoc1) {
        this.hcDocumentosAsociadosesForIdDoc1 = hcDocumentosAsociadosesForIdDoc1;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "hcDocumentoClinicoByIdDoc2")
    public Set<HcDocumentosAsociados_visorhc> getHcDocumentosAsociadosesForIdDoc2() {
        return this.hcDocumentosAsociadosesForIdDoc2;
    }

    public void setHcDocumentosAsociadosesForIdDoc2(
            Set<HcDocumentosAsociados_visorhc> hcDocumentosAsociadosesForIdDoc2) {
        this.hcDocumentosAsociadosesForIdDoc2 = hcDocumentosAsociadosesForIdDoc2;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "hcDocumentoClinico")
    public Set<HcDocumentoClinico_visorhc> getHcDocumentoClinicos() {
        return this.hcDocumentoClinicos;
    }

    public void setHcDocumentoClinicos(
            Set<HcDocumentoClinico_visorhc> hcDocumentoClinicos) {
        this.hcDocumentoClinicos = hcDocumentoClinicos;
    }

}
