package cu.uci.cesim.hce_back.visorhc.model.entity.auto;

// Generated May 10, 2013 1:18:35 PM by Hibernate Tools 3.4.0.CR1

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * HcDocumentosAsociados generated by hbm2java
 */
@Entity
@Table(name = "hc_documentos_asociados", schema = "hc")
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "id")
public class HcDocumentosAsociados_visorhc implements java.io.Serializable {

    private long id;
    private Integer version;
    private HcDocumentoClinico_visorhc hcDocumentoClinicoByIdDoc2;
    private HcDocumentoClinico_visorhc hcDocumentoClinicoByIdDoc1;
    private Long cid;

    public HcDocumentosAsociados_visorhc() {
    }

    public HcDocumentosAsociados_visorhc(long id) {
        this.id = id;
    }

    public HcDocumentosAsociados_visorhc(long id,
                                         HcDocumentoClinico_visorhc hcDocumentoClinicoByIdDoc2,
                                         HcDocumentoClinico_visorhc hcDocumentoClinicoByIdDoc1, Long cid) {
        this.id = id;
        this.hcDocumentoClinicoByIdDoc2 = hcDocumentoClinicoByIdDoc2;
        this.hcDocumentoClinicoByIdDoc1 = hcDocumentoClinicoByIdDoc1;
        this.cid = cid;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @Version
    @Column(name = "version")
    public Integer getVersion() {
        return this.version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_doc2")
    public HcDocumentoClinico_visorhc getHcDocumentoClinicoByIdDoc2() {
        return this.hcDocumentoClinicoByIdDoc2;
    }

    public void setHcDocumentoClinicoByIdDoc2(
            HcDocumentoClinico_visorhc hcDocumentoClinicoByIdDoc2) {
        this.hcDocumentoClinicoByIdDoc2 = hcDocumentoClinicoByIdDoc2;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_doc1")
    public HcDocumentoClinico_visorhc getHcDocumentoClinicoByIdDoc1() {
        return this.hcDocumentoClinicoByIdDoc1;
    }

    public void setHcDocumentoClinicoByIdDoc1(
            HcDocumentoClinico_visorhc hcDocumentoClinicoByIdDoc1) {
        this.hcDocumentoClinicoByIdDoc1 = hcDocumentoClinicoByIdDoc1;
    }

    @Column(name = "cid")
    public Long getCid() {
        return this.cid;
    }

    public void setCid(Long cid) {
        this.cid = cid;
    }

}
