package cu.uci.cesim.hce_back.visorhc.model.entity.auto;

// Generated May 10, 2013 1:18:35 PM by Hibernate Tools 3.4.0.CR1

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * HcMedico generated by hbm2java
 */
@Entity
@Table(name = "hc_medico", schema = "hc")
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "id")
public class HcMedico_visorhc implements java.io.Serializable {

    private long id;
    private Integer version;
    private String matricula;
    private String nombre;
    private String apellido1;
    private String apellido2;
    private Long cid;
    @JsonIgnore
    private Set<HcDocumentoClinico_visorhc> hcDocumentoClinicos = new HashSet<HcDocumentoClinico_visorhc>(
            0);

    public HcMedico_visorhc() {
    }

    public HcMedico_visorhc(long id, String matricula) {
        this.id = id;
        this.matricula = matricula;
    }

    public HcMedico_visorhc(long id, String matricula, String nombre,
                            String apellido1, String apellido2, Long cid,
                            Set<HcDocumentoClinico_visorhc> hcDocumentoClinicos) {
        this.id = id;
        this.matricula = matricula;
        this.nombre = nombre;
        this.apellido1 = apellido1;
        this.apellido2 = apellido2;
        this.cid = cid;
        this.hcDocumentoClinicos = hcDocumentoClinicos;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @Version
    @Column(name = "version")
    public Integer getVersion() {
        return this.version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    @Column(name = "matricula", nullable = false)
    public String getMatricula() {
        return this.matricula;
    }

    public void setMatricula(String matricula) {
        if (matricula != null)
            matricula = matricula.trim();
        this.matricula = matricula;
    }

    @Column(name = "nombre")
    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        if (nombre != null)
            nombre = nombre.trim();
        this.nombre = nombre;
    }

    @Column(name = "apellido1")
    public String getApellido1() {
        return this.apellido1;
    }

    public void setApellido1(String apellido1) {
        if (apellido1 != null)
            apellido1 = apellido1.trim();
        this.apellido1 = apellido1;
    }

    @Column(name = "apellido2")
    public String getApellido2() {
        return this.apellido2;
    }

    public void setApellido2(String apellido2) {
        if (apellido2 != null)
            apellido2 = apellido2.trim();
        this.apellido2 = apellido2;
    }

    @Column(name = "cid")
    public Long getCid() {
        return this.cid;
    }

    public void setCid(Long cid) {
        this.cid = cid;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "hcMedico")
    public Set<HcDocumentoClinico_visorhc> getHcDocumentoClinicos() {
        return this.hcDocumentoClinicos;
    }

    public void setHcDocumentoClinicos(
            Set<HcDocumentoClinico_visorhc> hcDocumentoClinicos) {
        this.hcDocumentoClinicos = hcDocumentoClinicos;
    }

}
