package cu.uci.cesim.hce_back.visorhc.model.entity.auto;

// Generated May 10, 2013 1:18:35 PM by Hibernate Tools 3.4.0.CR1

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * HcTrazaDocumento generated by hbm2java
 */
@Entity
@Table(name = "hc_traza_documento", schema = "hc")
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "id")
public class HcTrazaDocumento_visorhc implements java.io.Serializable {

    private long id;
    private int version;
    private HcPersona_visorhc hcPersonaByIdPersonaVieja;
    private HcPersona_visorhc hcPersonaByIdPersonaNueva;
    private HcDocumentoClinico_visorhc hcDocumentoClinico;
    private long idCambio;
    private boolean eliminado;
    private long cid;

    public HcTrazaDocumento_visorhc() {
    }

    public HcTrazaDocumento_visorhc(long id,
                                    HcPersona_visorhc hcPersonaByIdPersonaVieja,
                                    HcPersona_visorhc hcPersonaByIdPersonaNueva,
                                    HcDocumentoClinico_visorhc hcDocumentoClinico, long idCambio,
                                    boolean eliminado, long cid) {
        this.id = id;
        this.hcPersonaByIdPersonaVieja = hcPersonaByIdPersonaVieja;
        this.hcPersonaByIdPersonaNueva = hcPersonaByIdPersonaNueva;
        this.hcDocumentoClinico = hcDocumentoClinico;
        this.idCambio = idCambio;
        this.eliminado = eliminado;
        this.cid = cid;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @Version
    @Column(name = "version", nullable = false)
    public int getVersion() {
        return this.version;
    }

    public void setVersion(int version) {
        this.version = version;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_persona_vieja", nullable = false)
    public HcPersona_visorhc getHcPersonaByIdPersonaVieja() {
        return this.hcPersonaByIdPersonaVieja;
    }

    public void setHcPersonaByIdPersonaVieja(
            HcPersona_visorhc hcPersonaByIdPersonaVieja) {
        this.hcPersonaByIdPersonaVieja = hcPersonaByIdPersonaVieja;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_persona_nueva", nullable = false)
    public HcPersona_visorhc getHcPersonaByIdPersonaNueva() {
        return this.hcPersonaByIdPersonaNueva;
    }

    public void setHcPersonaByIdPersonaNueva(
            HcPersona_visorhc hcPersonaByIdPersonaNueva) {
        this.hcPersonaByIdPersonaNueva = hcPersonaByIdPersonaNueva;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_documento", nullable = false)
    public HcDocumentoClinico_visorhc getHcDocumentoClinico() {
        return this.hcDocumentoClinico;
    }

    public void setHcDocumentoClinico(
            HcDocumentoClinico_visorhc hcDocumentoClinico) {
        this.hcDocumentoClinico = hcDocumentoClinico;
    }

    @Column(name = "id_cambio", nullable = false)
    public long getIdCambio() {
        return this.idCambio;
    }

    public void setIdCambio(long idCambio) {
        this.idCambio = idCambio;
    }

    @Column(name = "eliminado", nullable = false)
    public boolean isEliminado() {
        return this.eliminado;
    }

    public void setEliminado(boolean eliminado) {
        this.eliminado = eliminado;
    }

    @Column(name = "cid", nullable = false)
    public long getCid() {
        return this.cid;
    }

    public void setCid(long cid) {
        this.cid = cid;
    }

}
